# shellcheck shell=bash
# shellcheck disable=SC2034
# Generated by scripts/harness/generate-verify-steps.ts. Do not edit by hand.
#
# Source this file only after the verify wrapper has initialized runtime
# variables referenced by slot args/env values. The guards below intentionally
# fail loudly when a wrapper sources the generated arrays too early.
: "${LOG_DIR:?scripts/verify/steps.generated.sh requires LOG_DIR}"
: "${TIMINGS_FILE:?scripts/verify/steps.generated.sh requires TIMINGS_FILE}"

declare -ga MUSI_VERIFY_CONSUMERS=('verify' 'verify_changed' 'verify_parallel' 'pre_commit')
declare -ga MUSI_VERIFY_STEPS=('lint' 'ratchet' 'zero-baseline' 'coverage-map' 'format-check' 'typecheck' 'test' 'scripts')
declare -ga MUSI_VERIFY_CHANGED_STEPS=('lint' 'ratchet' 'zero-baseline' 'coverage-map' 'format-check' 'typecheck' 'test' 'scripts')
declare -ga MUSI_VERIFY_PARALLEL_STEPS=('lint' 'ratchet' 'zero-baseline' 'coverage-map' 'format-check' 'typecheck' 'test' 'scripts')
declare -ga MUSI_PRE_COMMIT_STEPS=('lint' 'ratchet' 'zero-baseline' 'coverage-map' 'format-check' 'typecheck' 'test' 'scripts')

declare -gA MUSI_VERIFY_SLOT_CMD_VAR=()
declare -gA MUSI_VERIFY_SLOT_DYNAMIC=()

MUSI_VERIFY_LINT_CMD=('bun' 'run' 'lint')
MUSI_VERIFY_SLOT_CMD_VAR['verify:lint']='MUSI_VERIFY_LINT_CMD'

MUSI_VERIFY_RATCHET_CMD=('env' "HARNESS_DIAGNOSTICS_OUTPUT=$LOG_DIR/ratchet-diagnostics.json" 'bun' 'run' 'lint:ratchet')
MUSI_VERIFY_SLOT_CMD_VAR['verify:ratchet']='MUSI_VERIFY_RATCHET_CMD'

MUSI_VERIFY_ZERO_BASELINE_CMD=('bun' 'run' 'lint:ratchet:zero-baseline')
MUSI_VERIFY_SLOT_CMD_VAR['verify:zero-baseline']='MUSI_VERIFY_ZERO_BASELINE_CMD'

MUSI_VERIFY_COVERAGE_MAP_CMD=('bun' 'run' 'docs:lint-coverage-map:check')
MUSI_VERIFY_SLOT_CMD_VAR['verify:coverage-map']='MUSI_VERIFY_COVERAGE_MAP_CMD'

MUSI_VERIFY_FORMAT_CHECK_CMD=('bun' 'run' 'format:check')
MUSI_VERIFY_SLOT_CMD_VAR['verify:format-check']='MUSI_VERIFY_FORMAT_CHECK_CMD'

MUSI_VERIFY_TYPECHECK_CMD=('bun' 'run' 'typecheck')
MUSI_VERIFY_SLOT_CMD_VAR['verify:typecheck']='MUSI_VERIFY_TYPECHECK_CMD'

MUSI_VERIFY_TEST_CMD=('bun' 'run' 'test' '--reporter=dot' '--reporter=json' "--outputFile.json=$TIMINGS_FILE")
MUSI_VERIFY_SLOT_CMD_VAR['verify:test']='MUSI_VERIFY_TEST_CMD'

MUSI_VERIFY_SCRIPTS_CMD=('bun' 'run' 'test:scripts')
MUSI_VERIFY_SLOT_CMD_VAR['verify:scripts']='MUSI_VERIFY_SCRIPTS_CMD'

MUSI_VERIFY_CHANGED_LINT_CMD=('bun' 'run' 'lint:changed')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:lint']='MUSI_VERIFY_CHANGED_LINT_CMD'

MUSI_VERIFY_CHANGED_RATCHET_CMD=('env' "HARNESS_DIAGNOSTICS_OUTPUT=$LOG_DIR/ratchet-diagnostics.json" 'bun' 'run' 'lint:ratchet')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:ratchet']='MUSI_VERIFY_CHANGED_RATCHET_CMD'

MUSI_VERIFY_CHANGED_ZERO_BASELINE_CMD=('bun' 'run' 'lint:ratchet:zero-baseline')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:zero-baseline']='MUSI_VERIFY_CHANGED_ZERO_BASELINE_CMD'

MUSI_VERIFY_CHANGED_COVERAGE_MAP_CMD=('bun' 'run' 'docs:lint-coverage-map:check' '--' '--staged')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:coverage-map']='MUSI_VERIFY_CHANGED_COVERAGE_MAP_CMD'

MUSI_VERIFY_CHANGED_FORMAT_CHECK_CMD=('bun' 'run' 'format:changed:check')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:format-check']='MUSI_VERIFY_CHANGED_FORMAT_CHECK_CMD'

MUSI_VERIFY_CHANGED_TYPECHECK_CMD=('bun' 'run' 'typecheck')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:typecheck']='MUSI_VERIFY_CHANGED_TYPECHECK_CMD'

MUSI_VERIFY_CHANGED_TEST_CMD=('bun' 'run' 'test:changed' '--reporter=dot' '--reporter=json' "--outputFile.json=$TIMINGS_FILE")
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:test']='MUSI_VERIFY_CHANGED_TEST_CMD'

MUSI_VERIFY_CHANGED_SCRIPTS_CMD=('bun' 'run' 'test:scripts:changed')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:scripts']='MUSI_VERIFY_CHANGED_SCRIPTS_CMD'
MUSI_VERIFY_SLOT_DYNAMIC['verify_changed:scripts']='staged-script-classifier'

MUSI_VERIFY_PARALLEL_LINT_CMD=('bun' 'run' 'lint')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:lint']='MUSI_VERIFY_PARALLEL_LINT_CMD'

MUSI_VERIFY_PARALLEL_RATCHET_CMD=('env' "HARNESS_DIAGNOSTICS_OUTPUT=$LOG_DIR/ratchet-diagnostics.json" 'bun' 'run' 'lint:ratchet')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:ratchet']='MUSI_VERIFY_PARALLEL_RATCHET_CMD'

MUSI_VERIFY_PARALLEL_ZERO_BASELINE_CMD=('bun' 'run' 'lint:ratchet:zero-baseline')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:zero-baseline']='MUSI_VERIFY_PARALLEL_ZERO_BASELINE_CMD'

MUSI_VERIFY_PARALLEL_COVERAGE_MAP_CMD=('bun' 'run' 'docs:lint-coverage-map:check')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:coverage-map']='MUSI_VERIFY_PARALLEL_COVERAGE_MAP_CMD'

MUSI_VERIFY_PARALLEL_FORMAT_CHECK_CMD=('bun' 'run' 'format:check')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:format-check']='MUSI_VERIFY_PARALLEL_FORMAT_CHECK_CMD'

MUSI_VERIFY_PARALLEL_TYPECHECK_CMD=('bun' 'run' 'typecheck')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:typecheck']='MUSI_VERIFY_PARALLEL_TYPECHECK_CMD'

MUSI_VERIFY_PARALLEL_TEST_CMD=('bun' 'run' 'test' '--reporter=dot' '--reporter=json' "--outputFile.json=$TIMINGS_FILE")
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:test']='MUSI_VERIFY_PARALLEL_TEST_CMD'

MUSI_VERIFY_PARALLEL_SCRIPTS_CMD=('bun' 'run' 'test:scripts')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:scripts']='MUSI_VERIFY_PARALLEL_SCRIPTS_CMD'

MUSI_PRE_COMMIT_LINT_CMD=('bun' 'run' 'lint:changed')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:lint']='MUSI_PRE_COMMIT_LINT_CMD'

MUSI_PRE_COMMIT_RATCHET_CMD=('env' "HARNESS_DIAGNOSTICS_OUTPUT=$LOG_DIR/ratchet-diagnostics.json" 'bun' 'run' 'lint:ratchet')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:ratchet']='MUSI_PRE_COMMIT_RATCHET_CMD'

MUSI_PRE_COMMIT_ZERO_BASELINE_CMD=('bun' 'run' 'lint:ratchet:zero-baseline')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:zero-baseline']='MUSI_PRE_COMMIT_ZERO_BASELINE_CMD'

MUSI_PRE_COMMIT_COVERAGE_MAP_CMD=('bun' 'run' 'docs:lint-coverage-map:check' '--' '--staged')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:coverage-map']='MUSI_PRE_COMMIT_COVERAGE_MAP_CMD'

MUSI_PRE_COMMIT_FORMAT_CHECK_CMD=('bun' 'run' 'format:changed:check')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:format-check']='MUSI_PRE_COMMIT_FORMAT_CHECK_CMD'

MUSI_PRE_COMMIT_TYPECHECK_CMD=('bun' 'run' 'typecheck')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:typecheck']='MUSI_PRE_COMMIT_TYPECHECK_CMD'

MUSI_PRE_COMMIT_TEST_CMD=('bun' 'run' 'test:changed' '--reporter=dot')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:test']='MUSI_PRE_COMMIT_TEST_CMD'
MUSI_VERIFY_SLOT_DYNAMIC['pre_commit:test']='precommit-test-timings'

MUSI_PRE_COMMIT_SCRIPTS_CMD=('bun' 'run' 'test:scripts:changed')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:scripts']='MUSI_PRE_COMMIT_SCRIPTS_CMD'
MUSI_VERIFY_SLOT_DYNAMIC['pre_commit:scripts']='staged-script-classifier'
