# shellcheck shell=bash
# shellcheck disable=SC2034
# Generated by scripts/harness/generate-verify-steps.ts. Do not edit by hand.
#
# Source this file only after the verify wrapper has initialized runtime
# variables referenced by slot args/env values. The guards below intentionally
# fail loudly when a wrapper sources the generated arrays too early.
: "${LOG_DIR:?scripts/verify/steps.generated.sh requires LOG_DIR}"
: "${TIMINGS_FILE:?scripts/verify/steps.generated.sh requires TIMINGS_FILE}"

declare -ga MUSI_VERIFY_CONSUMERS=('verify' 'verify_changed' 'verify_parallel' 'pre_commit')
declare -ga MUSI_VERIFY_STEPS=('lint' 'suppressions' 'ratchet' 'zero-baseline' 'debt-accounting' 'local-rule-starter' 'knip-unused-exports' 'near-duplicates' 'max-lines-exceptions' 'coverage-map' 'format-check' 'typecheck' 'test' 'scripts')
declare -ga MUSI_VERIFY_CHANGED_STEPS=('lint' 'suppressions' 'ratchet' 'zero-baseline' 'debt-accounting' 'knip-unused-exports' 'near-duplicates' 'max-lines-exceptions' 'coverage-map' 'format-check' 'typecheck' 'test' 'scripts')
declare -ga MUSI_VERIFY_PARALLEL_STEPS=('lint' 'suppressions' 'ratchet' 'zero-baseline' 'debt-accounting' 'local-rule-starter' 'knip-unused-exports' 'near-duplicates' 'max-lines-exceptions' 'coverage-map' 'format-check' 'typecheck' 'test' 'scripts')
declare -ga MUSI_PRE_COMMIT_STEPS=('lint' 'suppressions' 'ratchet' 'zero-baseline' 'debt-accounting' 'knip-unused-exports' 'near-duplicates' 'max-lines-exceptions' 'coverage-map' 'format-check' 'typecheck' 'test' 'scripts')

declare -ga MUSI_FAST_COMMIT_SKIP_SLOTS=('test' 'scripts')

declare -gA MUSI_VERIFY_SLOT_CMD_VAR=()
declare -gA MUSI_VERIFY_SLOT_DYNAMIC=()
declare -gA MUSI_VERIFY_DYNAMIC_RESOLVER_FUNC=()

MUSI_VERIFY_LINT_CMD=('bun' 'run' 'lint')
MUSI_VERIFY_SLOT_CMD_VAR['verify:lint']='MUSI_VERIFY_LINT_CMD'

MUSI_VERIFY_SUPPRESSIONS_CMD=('bun' 'run' 'lint:suppressions')
MUSI_VERIFY_SLOT_CMD_VAR['verify:suppressions']='MUSI_VERIFY_SUPPRESSIONS_CMD'

MUSI_VERIFY_RATCHET_CMD=('env' "HARNESS_DIAGNOSTICS_OUTPUT=$LOG_DIR/ratchet-diagnostics.json" 'bun' 'run' 'lint:ratchet')
MUSI_VERIFY_SLOT_CMD_VAR['verify:ratchet']='MUSI_VERIFY_RATCHET_CMD'

MUSI_VERIFY_ZERO_BASELINE_CMD=('bun' 'run' 'lint:ratchet:zero-baseline')
MUSI_VERIFY_SLOT_CMD_VAR['verify:zero-baseline']='MUSI_VERIFY_ZERO_BASELINE_CMD'

MUSI_VERIFY_DEBT_ACCOUNTING_CMD=('bun' 'run' 'lint:ratchet:check-debt-accounting')
MUSI_VERIFY_SLOT_CMD_VAR['verify:debt-accounting']='MUSI_VERIFY_DEBT_ACCOUNTING_CMD'

MUSI_VERIFY_LOCAL_RULE_STARTER_CMD=('bun' 'run' 'docs:local-eslint-rule-starter:check')
MUSI_VERIFY_SLOT_CMD_VAR['verify:local-rule-starter']='MUSI_VERIFY_LOCAL_RULE_STARTER_CMD'

MUSI_VERIFY_KNIP_UNUSED_EXPORTS_CMD=('bun' 'run' 'sensor:knip-unused-exports')
MUSI_VERIFY_SLOT_CMD_VAR['verify:knip-unused-exports']='MUSI_VERIFY_KNIP_UNUSED_EXPORTS_CMD'

MUSI_VERIFY_NEAR_DUPLICATES_CMD=('bun' 'run' 'sensor:near-duplicates' '--' '--check-baseline')
MUSI_VERIFY_SLOT_CMD_VAR['verify:near-duplicates']='MUSI_VERIFY_NEAR_DUPLICATES_CMD'

MUSI_VERIFY_MAX_LINES_EXCEPTIONS_CMD=('bun' 'run' 'lint:max-lines-exceptions')
MUSI_VERIFY_SLOT_CMD_VAR['verify:max-lines-exceptions']='MUSI_VERIFY_MAX_LINES_EXCEPTIONS_CMD'

MUSI_VERIFY_COVERAGE_MAP_CMD=('bun' 'run' 'docs:lint-coverage-map:audit')
MUSI_VERIFY_SLOT_CMD_VAR['verify:coverage-map']='MUSI_VERIFY_COVERAGE_MAP_CMD'

MUSI_VERIFY_FORMAT_CHECK_CMD=('bun' 'run' 'format:check')
MUSI_VERIFY_SLOT_CMD_VAR['verify:format-check']='MUSI_VERIFY_FORMAT_CHECK_CMD'

MUSI_VERIFY_TYPECHECK_CMD=('bun' 'run' 'typecheck')
MUSI_VERIFY_SLOT_CMD_VAR['verify:typecheck']='MUSI_VERIFY_TYPECHECK_CMD'

MUSI_VERIFY_TEST_CMD=('bun' 'run' 'test' '--reporter=dot' '--reporter=json' "--outputFile.json=$TIMINGS_FILE")
MUSI_VERIFY_SLOT_CMD_VAR['verify:test']='MUSI_VERIFY_TEST_CMD'

MUSI_VERIFY_SCRIPTS_CMD=('bun' 'run' 'test:scripts')
MUSI_VERIFY_SLOT_CMD_VAR['verify:scripts']='MUSI_VERIFY_SCRIPTS_CMD'

MUSI_VERIFY_CHANGED_LINT_CMD=('bun' 'run' 'lint:changed')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:lint']='MUSI_VERIFY_CHANGED_LINT_CMD'

MUSI_VERIFY_CHANGED_SUPPRESSIONS_CMD=('bun' 'run' 'lint:suppressions:changed')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:suppressions']='MUSI_VERIFY_CHANGED_SUPPRESSIONS_CMD'

MUSI_VERIFY_CHANGED_RATCHET_CMD=('env' "HARNESS_DIAGNOSTICS_OUTPUT=$LOG_DIR/ratchet-diagnostics.json" 'bun' 'run' 'lint:ratchet')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:ratchet']='MUSI_VERIFY_CHANGED_RATCHET_CMD'

MUSI_VERIFY_CHANGED_ZERO_BASELINE_CMD=('bun' 'run' 'lint:ratchet:zero-baseline')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:zero-baseline']='MUSI_VERIFY_CHANGED_ZERO_BASELINE_CMD'

MUSI_VERIFY_CHANGED_DEBT_ACCOUNTING_CMD=('bun' 'run' 'lint:ratchet:check-debt-accounting' '--' '--staged')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:debt-accounting']='MUSI_VERIFY_CHANGED_DEBT_ACCOUNTING_CMD'

MUSI_VERIFY_CHANGED_KNIP_UNUSED_EXPORTS_CMD=('bun' 'run' 'sensor:knip-unused-exports')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:knip-unused-exports']='MUSI_VERIFY_CHANGED_KNIP_UNUSED_EXPORTS_CMD'

MUSI_VERIFY_CHANGED_NEAR_DUPLICATES_CMD=('bun' 'run' 'sensor:near-duplicates')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:near-duplicates']='MUSI_VERIFY_CHANGED_NEAR_DUPLICATES_CMD'

MUSI_VERIFY_CHANGED_MAX_LINES_EXCEPTIONS_CMD=('bun' 'run' 'lint:max-lines-exceptions')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:max-lines-exceptions']='MUSI_VERIFY_CHANGED_MAX_LINES_EXCEPTIONS_CMD'

MUSI_VERIFY_CHANGED_COVERAGE_MAP_CMD=('bun' 'run' 'docs:lint-coverage-map:check' '--' '--staged')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:coverage-map']='MUSI_VERIFY_CHANGED_COVERAGE_MAP_CMD'

MUSI_VERIFY_CHANGED_FORMAT_CHECK_CMD=('bun' 'run' 'format:changed:check')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:format-check']='MUSI_VERIFY_CHANGED_FORMAT_CHECK_CMD'

MUSI_VERIFY_CHANGED_TYPECHECK_CMD=('bun' 'run' 'typecheck')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:typecheck']='MUSI_VERIFY_CHANGED_TYPECHECK_CMD'

MUSI_VERIFY_CHANGED_TEST_CMD=('bun' 'run' 'test:changed' '--reporter=dot' '--reporter=json' "--outputFile.json=$TIMINGS_FILE")
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:test']='MUSI_VERIFY_CHANGED_TEST_CMD'

MUSI_VERIFY_CHANGED_SCRIPTS_CMD=('bun' 'run' 'test:scripts:changed')
MUSI_VERIFY_SLOT_CMD_VAR['verify_changed:scripts']='MUSI_VERIFY_CHANGED_SCRIPTS_CMD'
MUSI_VERIFY_SLOT_DYNAMIC['verify_changed:scripts']='staged-script-classifier'

MUSI_VERIFY_PARALLEL_LINT_CMD=('bun' 'run' 'lint')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:lint']='MUSI_VERIFY_PARALLEL_LINT_CMD'

MUSI_VERIFY_PARALLEL_SUPPRESSIONS_CMD=('bun' 'run' 'lint:suppressions')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:suppressions']='MUSI_VERIFY_PARALLEL_SUPPRESSIONS_CMD'

MUSI_VERIFY_PARALLEL_RATCHET_CMD=('env' "HARNESS_DIAGNOSTICS_OUTPUT=$LOG_DIR/ratchet-diagnostics.json" 'bun' 'run' 'lint:ratchet')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:ratchet']='MUSI_VERIFY_PARALLEL_RATCHET_CMD'

MUSI_VERIFY_PARALLEL_ZERO_BASELINE_CMD=('bun' 'run' 'lint:ratchet:zero-baseline')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:zero-baseline']='MUSI_VERIFY_PARALLEL_ZERO_BASELINE_CMD'

MUSI_VERIFY_PARALLEL_DEBT_ACCOUNTING_CMD=('bun' 'run' 'lint:ratchet:check-debt-accounting')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:debt-accounting']='MUSI_VERIFY_PARALLEL_DEBT_ACCOUNTING_CMD'

MUSI_VERIFY_PARALLEL_LOCAL_RULE_STARTER_CMD=('bun' 'run' 'docs:local-eslint-rule-starter:check')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:local-rule-starter']='MUSI_VERIFY_PARALLEL_LOCAL_RULE_STARTER_CMD'

MUSI_VERIFY_PARALLEL_KNIP_UNUSED_EXPORTS_CMD=('bun' 'run' 'sensor:knip-unused-exports')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:knip-unused-exports']='MUSI_VERIFY_PARALLEL_KNIP_UNUSED_EXPORTS_CMD'

MUSI_VERIFY_PARALLEL_NEAR_DUPLICATES_CMD=('bun' 'run' 'sensor:near-duplicates' '--' '--check-baseline')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:near-duplicates']='MUSI_VERIFY_PARALLEL_NEAR_DUPLICATES_CMD'

MUSI_VERIFY_PARALLEL_MAX_LINES_EXCEPTIONS_CMD=('bun' 'run' 'lint:max-lines-exceptions')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:max-lines-exceptions']='MUSI_VERIFY_PARALLEL_MAX_LINES_EXCEPTIONS_CMD'

MUSI_VERIFY_PARALLEL_COVERAGE_MAP_CMD=('bun' 'run' 'docs:lint-coverage-map:audit')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:coverage-map']='MUSI_VERIFY_PARALLEL_COVERAGE_MAP_CMD'

MUSI_VERIFY_PARALLEL_FORMAT_CHECK_CMD=('bun' 'run' 'format:check')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:format-check']='MUSI_VERIFY_PARALLEL_FORMAT_CHECK_CMD'

MUSI_VERIFY_PARALLEL_TYPECHECK_CMD=('bun' 'run' 'typecheck')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:typecheck']='MUSI_VERIFY_PARALLEL_TYPECHECK_CMD'

MUSI_VERIFY_PARALLEL_TEST_CMD=('bun' 'run' 'test' '--reporter=dot' '--reporter=json' "--outputFile.json=$TIMINGS_FILE")
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:test']='MUSI_VERIFY_PARALLEL_TEST_CMD'

MUSI_VERIFY_PARALLEL_SCRIPTS_CMD=('bun' 'run' 'test:scripts')
MUSI_VERIFY_SLOT_CMD_VAR['verify_parallel:scripts']='MUSI_VERIFY_PARALLEL_SCRIPTS_CMD'

MUSI_PRE_COMMIT_LINT_CMD=('bun' 'run' 'lint:changed')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:lint']='MUSI_PRE_COMMIT_LINT_CMD'

MUSI_PRE_COMMIT_SUPPRESSIONS_CMD=('bun' 'run' 'lint:suppressions:changed')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:suppressions']='MUSI_PRE_COMMIT_SUPPRESSIONS_CMD'

MUSI_PRE_COMMIT_RATCHET_CMD=('env' "HARNESS_DIAGNOSTICS_OUTPUT=$LOG_DIR/ratchet-diagnostics.json" 'bun' 'run' 'lint:ratchet')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:ratchet']='MUSI_PRE_COMMIT_RATCHET_CMD'

MUSI_PRE_COMMIT_ZERO_BASELINE_CMD=('bun' 'run' 'lint:ratchet:zero-baseline')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:zero-baseline']='MUSI_PRE_COMMIT_ZERO_BASELINE_CMD'

MUSI_PRE_COMMIT_DEBT_ACCOUNTING_CMD=('bun' 'run' 'lint:ratchet:check-debt-accounting' '--' '--staged')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:debt-accounting']='MUSI_PRE_COMMIT_DEBT_ACCOUNTING_CMD'

MUSI_PRE_COMMIT_KNIP_UNUSED_EXPORTS_CMD=('bun' 'run' 'sensor:knip-unused-exports')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:knip-unused-exports']='MUSI_PRE_COMMIT_KNIP_UNUSED_EXPORTS_CMD'

MUSI_PRE_COMMIT_NEAR_DUPLICATES_CMD=('bun' 'run' 'sensor:near-duplicates')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:near-duplicates']='MUSI_PRE_COMMIT_NEAR_DUPLICATES_CMD'

MUSI_PRE_COMMIT_MAX_LINES_EXCEPTIONS_CMD=('bun' 'run' 'lint:max-lines-exceptions')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:max-lines-exceptions']='MUSI_PRE_COMMIT_MAX_LINES_EXCEPTIONS_CMD'

MUSI_PRE_COMMIT_COVERAGE_MAP_CMD=('bun' 'run' 'docs:lint-coverage-map:check' '--' '--staged')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:coverage-map']='MUSI_PRE_COMMIT_COVERAGE_MAP_CMD'

MUSI_PRE_COMMIT_FORMAT_CHECK_CMD=('bun' 'run' 'format:changed:check')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:format-check']='MUSI_PRE_COMMIT_FORMAT_CHECK_CMD'

MUSI_PRE_COMMIT_TYPECHECK_CMD=('bun' 'run' 'typecheck')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:typecheck']='MUSI_PRE_COMMIT_TYPECHECK_CMD'

MUSI_PRE_COMMIT_TEST_CMD=('bun' 'run' 'test:changed' '--reporter=dot')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:test']='MUSI_PRE_COMMIT_TEST_CMD'
MUSI_VERIFY_SLOT_DYNAMIC['pre_commit:test']='precommit-test-timings'

MUSI_PRE_COMMIT_SCRIPTS_CMD=('bun' 'run' 'test:scripts:changed')
MUSI_VERIFY_SLOT_CMD_VAR['pre_commit:scripts']='MUSI_PRE_COMMIT_SCRIPTS_CMD'
MUSI_VERIFY_SLOT_DYNAMIC['pre_commit:scripts']='staged-script-classifier'

MUSI_VERIFY_DYNAMIC_RESOLVER_FUNC['precommit-test-timings']='musi_resolve_precommit_test_timing_cmd'
MUSI_VERIFY_DYNAMIC_RESOLVER_FUNC['staged-script-classifier']='musi_resolve_staged_script_cmd'
