import { spawnSync } from "node:child_process";
import { chmodSync, existsSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import { renderMergeDriverBootstrap } from "./bootstrap.js";

describe("merge-driver bootstrap", () => {
  const roots: string[] = [];

  afterEach(() => {
    for (const root of roots) rmSync(root, { recursive: true, force: true });
    roots.length = 0;
  });

  it("resolves the active worktree and carries a regeneration marker", () => {
    const rendered = renderMergeDriverBootstrap(
      "scripts/lint-ratchet/engine-binding.ts",
      "@renamed/lint-ratchet/git-rail/executable-cli.js",
      "manual recovery recipe",
    );

    expect(rendered).toContain("generated by @musi/lint-ratchet");
    expect(rendered).toContain("repo_root=$(git rev-parse --show-toplevel)");
    expect(rendered).toContain("@renamed/lint-ratchet/git-rail/executable-cli.js");
    expect(rendered).not.toContain("@musi/lint-ratchet/git-rail/executable-cli.js");
    expect(rendered).toContain("-- _merge --adapter");
    expect(rendered).toContain("scripts/lint-ratchet/engine-binding.ts");
    expect(rendered).toContain('"$truth_up_marker" "$pre_merge_head_sha"');
  });

  it("rejects adapter paths that cannot be safely embedded in the generated shell", () => {
    expect(() =>
      renderMergeDriverBootstrap(
        "scripts/adapter with spaces.ts",
        "@renamed/lint-ratchet/git-rail/executable-cli.js",
        "manual recovery recipe",
      ),
    ).toThrow("portable repository-relative path");
  });

  it("prints the adopter recovery recipe when Bun is unavailable", () => {
    const root = mkdtempSync(join(tmpdir(), "lint-ratchet-bootstrap-no-bun-"));
    roots.push(root);
    const fakeBin = join(root, "fake-bin");
    const bootstrap = join(root, "bootstrap.sh");
    expect(spawnSync("mkdir", ["-p", fakeBin]).status).toBe(0);
    for (const command of ["bash", "dirname", "git", "mkdir"]) {
      const resolved = spawnSync("which", [command], { encoding: "utf8" }).stdout.trim();
      expect(resolved).not.toBe("");
      expect(spawnSync("ln", ["-s", resolved, join(fakeBin, command)]).status).toBe(0);
    }
    expect(spawnSync("git", ["init", "-q"], { cwd: root }).status).toBe(0);
    expect(
      spawnSync(
        "git",
        [
          "-c",
          "user.name=Test",
          "-c",
          "user.email=test@example.invalid",
          "commit",
          "--allow-empty",
          "-qm",
          "seed",
        ],
        { cwd: root },
      ).status,
    ).toBe(0);
    writeFileSync(
      bootstrap,
      renderMergeDriverBootstrap(
        "scripts/lint-ratchet/adapter.ts",
        "@musi/lint-ratchet/git-rail/executable-cli.js",
        "adopter recovery: run ratchet repair --reason 'required'",
      ),
    );
    chmodSync(bootstrap, 0o755);

    const result = spawnSync(
      "bash",
      [bootstrap, "base.tmp", "current.tmp", "other.tmp", "7", "lint-ratchet.baseline.json"],
      { cwd: root, env: { ...process.env, PATH: fakeBin }, encoding: "utf8" },
    );

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("adopter recovery: run ratchet repair --reason 'required'");
  });

  it("enriches Git merge placeholders with the display path, marker, and pre-merge head", () => {
    const root = mkdtempSync(join(tmpdir(), "lint-ratchet-bootstrap-"));
    roots.push(root);
    const fakeBin = join(root, "fake-bin");
    const bootstrap = join(root, "bootstrap.sh");
    const bun = join(fakeBin, "bun");
    const env = { ...process.env, PATH: `${fakeBin}:${process.env.PATH ?? ""}` };
    expect(spawnSync("mkdir", ["-p", fakeBin]).status).toBe(0);
    expect(spawnSync("git", ["init", "-q"], { cwd: root }).status).toBe(0);
    expect(
      spawnSync(
        "git",
        [
          "-c",
          "user.name=Test",
          "-c",
          "user.email=test@example.invalid",
          "commit",
          "--allow-empty",
          "-qm",
          "seed",
        ],
        { cwd: root },
      ).status,
    ).toBe(0);
    writeFileSync(bun, "#!/usr/bin/env bash\nprintf '%s\\n' \"$@\"\n");
    chmodSync(bun, 0o755);
    writeFileSync(
      bootstrap,
      renderMergeDriverBootstrap(
        "scripts/lint-ratchet/adapter.ts",
        "@musi/lint-ratchet/git-rail/executable-cli.js",
        "manual recovery recipe",
      ),
    );
    chmodSync(bootstrap, 0o755);

    const head = spawnSync("git", ["rev-parse", "HEAD"], {
      cwd: root,
      encoding: "utf8",
    }).stdout.trim();
    const result = spawnSync(
      "bash",
      [bootstrap, "base.tmp", "current.tmp", "other.tmp", "7", "lint-ratchet.baseline.json"],
      { cwd: root, env, encoding: "utf8" },
    );

    expect(result.status).toBe(0);
    expect(result.stdout.trim().split("\n").slice(-6)).toEqual([
      join(root, "base.tmp"),
      join(root, "current.tmp"),
      join(root, "other.tmp"),
      "lint-ratchet.baseline.json",
      join(root, ".git", "musi", "lint-ratchet-baseline-postmerge-truth-up-required"),
      head,
    ]);
  });

  it("places a linked-worktree marker in that worktree's Git directory", () => {
    const root = mkdtempSync(join(tmpdir(), "lint-ratchet-bootstrap-linked-"));
    roots.push(root);
    const linked = join(root, "linked");
    const primary = join(root, "primary");
    const fakeBin = join(root, "fake-bin");
    const bootstrap = join(root, "bootstrap.sh");
    const bun = join(fakeBin, "bun");
    expect(spawnSync("mkdir", ["-p", primary, fakeBin]).status).toBe(0);
    expect(spawnSync("git", ["init", "-q", "-b", "main"], { cwd: primary }).status).toBe(0);
    expect(
      spawnSync(
        "git",
        [
          "-c",
          "user.name=Test",
          "-c",
          "user.email=test@example.invalid",
          "commit",
          "--allow-empty",
          "-qm",
          "seed",
        ],
        { cwd: primary },
      ).status,
    ).toBe(0);
    expect(
      spawnSync("git", ["worktree", "add", "-q", "--detach", linked, "HEAD"], { cwd: primary })
        .status,
    ).toBe(0);
    writeFileSync(bun, "#!/usr/bin/env bash\nprintf '%s\\n' \"$@\"\n");
    chmodSync(bun, 0o755);
    writeFileSync(
      bootstrap,
      renderMergeDriverBootstrap(
        "scripts/lint-ratchet/adapter.ts",
        "@musi/lint-ratchet/git-rail/executable-cli.js",
        "manual recovery recipe",
      ),
    );
    chmodSync(bootstrap, 0o755);

    const result = spawnSync(
      "bash",
      [bootstrap, "base.tmp", "current.tmp", "other.tmp", "7", "lint-ratchet.baseline.json"],
      {
        cwd: linked,
        env: { ...process.env, PATH: `${fakeBin}:${process.env.PATH ?? ""}` },
        encoding: "utf8",
      },
    );
    const args = result.stdout.trim().split("\n");
    const gitDir = spawnSync("git", ["rev-parse", "--git-dir"], {
      cwd: linked,
      encoding: "utf8",
    }).stdout.trim();
    const commonDir = spawnSync("git", ["rev-parse", "--git-common-dir"], {
      cwd: linked,
      encoding: "utf8",
    }).stdout.trim();
    const marker = join(gitDir, "musi", "lint-ratchet-baseline-postmerge-truth-up-required");
    const sharedMarker = join(
      commonDir,
      "musi",
      "lint-ratchet-baseline-postmerge-truth-up-required",
    );

    expect(result.status).toBe(0);
    expect(args.at(-2)).toBe(marker);
    expect(marker).not.toBe(sharedMarker);
    expect(existsSync(sharedMarker)).toBe(false);
    expect(args.at(-6)).toBe(join(linked, "base.tmp"));
  });
});
