const PORTABLE_PATH = /^(?!\/)(?!.*(?:^|\/)\.\.(?:\/|$))[\w./-]+$/u;

const GENERATED_BOOTSTRAP_MARKER =
  "# generated by @musi/lint-ratchet; regenerate with the repository's lint:ratchet:install-merge-driver command";

function shellSingleQuote(value: string): string {
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

export function renderMergeDriverBootstrap(
  adapterModule: string,
  executableModuleSpecifier: string,
  conflictRecovery: string,
): string {
  if (!PORTABLE_PATH.test(adapterModule)) {
    throw new Error(`adapter module must be a portable repository-relative path: ${adapterModule}`);
  }
  const recovery = shellSingleQuote(conflictRecovery);
  const executableImport = shellSingleQuote(
    `import(${JSON.stringify(executableModuleSpecifier)}).then(module => module.runLintRatchetGitRailCliMain(process.argv.slice(1)))`,
  );
  return `#!/usr/bin/env bash
${GENERATED_BOOTSTRAP_MARKER}
set -euo pipefail

if [ "$#" -ne 5 ]; then
  printf 'lint-ratchet baseline merge driver: expected arguments %%O %%A %%B %%L %%P.\n' >&2
  exit 2
fi

absolute_path() {
  case "$1" in
    /*) printf '%s\n' "$1" ;;
    *) printf '%s/%s\n' "$PWD" "$1" ;;
  esac
}

base_file=$(absolute_path "$1")
current_file=$(absolute_path "$2")
other_file=$(absolute_path "$3")
path=$5
repo_root=$(git rev-parse --show-toplevel)
cd "$repo_root"
git_dir=$(git rev-parse --git-dir)
case "$git_dir" in
  /*) git_dir_abs=$git_dir ;;
  *) git_dir_abs="$repo_root/$git_dir" ;;
esac
truth_up_marker="$git_dir_abs/musi/lint-ratchet-baseline-postmerge-truth-up-required"
mkdir -p "$(dirname "$truth_up_marker")"
pre_merge_head_sha=$(git rev-parse --verify 'HEAD^{commit}')

print_recovery() {
  printf '%s\n' ${recovery} >&2
}

if ! command -v bun >/dev/null 2>&1; then
  print_recovery
  exit 1
fi

set +e
bun -e ${executableImport} -- _merge --adapter ${adapterModule} -- "$base_file" "$current_file" "$other_file" "$path" "$truth_up_marker" "$pre_merge_head_sha"
status=$?
set -e
if [ "$status" -ne 0 ]; then
  print_recovery
fi
exit "$status"
`;
}
