#!/usr/bin/env bash
# smoke-subjects: scripts/tests/test-lint-coverage-map-gen.sh
# smoke-subjects: scripts/lint-coverage-map-gen.ts
# smoke-subjects: scripts/lint-coverage-map-gen-core.ts
# smoke-subjects: scripts/lint-coverage-map-gen-core.test.ts
# smoke-subjects: scripts/lint-coverage-map-check-eslint-reach.ts
# smoke-subjects: scripts/lint-coverage-map-check-io.ts
# smoke-subjects: scripts/lint-coverage-map-check-types.ts
# smoke-subjects: scripts/lib/codepoint-compare.ts
# smoke-subjects: scripts/lib/doc-generator.ts
# smoke-subjects: scripts/lib/git.ts
# smoke-subjects: scripts/lint-ratchet/lint-ratchet-config.ts
# smoke-subjects: scripts/lint-ratchet/registry-builders.ts
# smoke-subjects: tools/lint-ratchet/package.json
# smoke-subjects: tools/lint-ratchet/src/kernel/ratchet-globs.ts
# smoke-subjects: docs/generated/lint-coverage-map.md
# smoke-subjects: scripts/drift-ai/
# smoke-subjects: eslint.config.js
# smoke-subjects: eslint-config/
# smoke-subjects: eslint-rules/
# smoke-subjects: tsconfig.scripts.json
# smoke-subjects: package.json
# smoke-subjects: harness.controls.json

set -euo pipefail

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
TMP_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/lint-coverage-map-gen-XXXXXX")
FIXTURE="$TMP_ROOT/repo"

cleanup() {
  rm -rf "$TMP_ROOT"
}
trap cleanup EXIT

copy_file() {
  local path=$1
  mkdir -p "$FIXTURE/$(dirname "$path")"
  cp "$REPO_ROOT/$path" "$FIXTURE/$path"
}

for path in \
  eslint-config/config-surface-manifest.json \
  eslint-config/config-surfaces.js \
  eslint-config/max-lines-exceptions-codec.js \
  eslint-config/max-lines-exceptions.baseline.json \
  eslint-config/shared-policy.js \
  scripts/lib/codepoint-compare.ts \
  scripts/lib/doc-generator.ts \
  scripts/lib/git.ts \
  scripts/lint-coverage-map-check-eslint-reach.ts \
  scripts/lint-coverage-map-check-io.ts \
  scripts/lint-coverage-map-check-types.ts \
  scripts/lint-coverage-map-gen-core.ts \
  scripts/lint-coverage-map-gen.ts \
  scripts/lint-ratchet/lint-ratchet-config.ts \
  scripts/lint-ratchet/registry-builders.ts; do
  copy_file "$path"
done

mkdir -p \
  "$FIXTURE/docs/generated" \
  "$FIXTURE/node_modules/@musi" \
  "$FIXTURE/scripts/drift-ai/fixtures/sample"
ln -s "$REPO_ROOT/node_modules/eslint" "$FIXTURE/node_modules/eslint"
ln -s "$REPO_ROOT/tools/lint-ratchet" "$FIXTURE/node_modules/@musi/lint-ratchet"

cat >"$FIXTURE/eslint.config.js" <<'JS'
export default [{ files: ["scripts/drift-ai/*.ts"], rules: {} }];
JS
cat >"$FIXTURE/package.json" <<'JSON'
{
  "type": "module",
  "scripts": {
    "docs:lint-coverage-map:generate": "bun run scripts/lint-coverage-map-gen.ts",
    "docs:lint-coverage-map:generate:check": "bun run scripts/lint-coverage-map-gen.ts -- --check"
  }
}
JSON
cat >"$FIXTURE/docs/generated/lint-coverage-map.md" <<'MD'
prefix stays byte-identical
<!-- BEGIN generated: lint-coverage-map drift-ai -->
stale generated bytes
<!-- END generated: lint-coverage-map drift-ai -->
suffix stays byte-identical
MD
: >"$FIXTURE/scripts/drift-ai/a.ts"
: >"$FIXTURE/scripts/drift-ai/b.test.ts"
: >"$FIXTURE/scripts/drift-ai/fixtures/sample/nested.ts"

git -C "$FIXTURE" init -q
git -C "$FIXTURE" config user.email fixture@example.com
git -C "$FIXTURE" config user.name Fixture
git -C "$FIXTURE" add .
git -C "$FIXTURE" commit -qm "test: initialize generator fixture"

if (cd "$FIXTURE" && bun run docs:lint-coverage-map:generate:check >/dev/null 2>&1); then
  echo "expected stale generated bytes to fail check mode" >&2
  exit 1
fi
(cd "$FIXTURE" && bun run docs:lint-coverage-map:generate >/dev/null)
(cd "$FIXTURE" && bun run docs:lint-coverage-map:generate:check >/dev/null)

grep -qF '| `scripts/drift-ai/*.ts` | 2 .ts |' \
  "$FIXTURE/docs/generated/lint-coverage-map.md"
grep -qF 'prefix stays byte-identical' "$FIXTURE/docs/generated/lint-coverage-map.md"
grep -qF 'suffix stays byte-identical' "$FIXTURE/docs/generated/lint-coverage-map.md"
if grep -qF '3 .ts' "$FIXTURE/docs/generated/lint-coverage-map.md"; then
  echo "nested fixture TypeScript entered the direct-child count" >&2
  exit 1
fi

: >"$FIXTURE/scripts/drift-ai/new.ts"
git -C "$FIXTURE" add scripts/drift-ai/new.ts
if (cd "$FIXTURE" && bun run docs:lint-coverage-map:generate:check >/dev/null 2>&1); then
  echo "expected a newly tracked direct-child file to stale the block" >&2
  exit 1
fi
(cd "$FIXTURE" && bun run docs:lint-coverage-map:generate >/dev/null)
grep -qF '| `scripts/drift-ai/*.ts` | 3 .ts |' \
  "$FIXTURE/docs/generated/lint-coverage-map.md"

sed -i 's/| 3 \.ts |/| 99 .ts |/' "$FIXTURE/docs/generated/lint-coverage-map.md"
if (cd "$FIXTURE" && bun run docs:lint-coverage-map:generate:check >/dev/null 2>&1); then
  echo "expected an edited generated count to fail check mode" >&2
  exit 1
fi
(cd "$FIXTURE" && bun run docs:lint-coverage-map:generate >/dev/null)
(cd "$FIXTURE" && bun run docs:lint-coverage-map:generate:check >/dev/null)

echo "lint coverage-map generator smoke OK"
