import { existsSync, readdirSync } from "node:fs";
import { join } from "node:path";

export type ScriptSmokeSubjects = Record<string, readonly string[]>;
const PATH_POLICY_QUERY_SUBJECTS = [
  "scripts/path-policy/path-policy-query.ts",
  "scripts/path-policy/path-policy-query-core.ts",
  "scripts/path-policy/path-policy.ts",
] as const;
// Config surface loaded by every smoke whose subject is a bun TS entrypoint
// that resolves the repo ESLint setup (lint-agent, ratchet, generators).
const ESLINT_SURFACE_SUBJECTS = [
  "eslint.config.js",
  "eslint-config/",
  "eslint-rules/",
  "package.json",
  "tsconfig.scripts.json",
] as const;

export const SCRIPT_SMOKE_SUBJECTS = {
  "test-verify": [
    "scripts/verify.sh",
    "scripts/verify/steps.generated.sh",
    "scripts/verify/steps-lib.sh",
    "scripts/lib/verify-metadata.sh",
    ...PATH_POLICY_QUERY_SUBJECTS,
    "scripts/process-tree.sh",
    "scripts/lib/parallel-step.sh",
    "scripts/tests/lib/test-git-env.sh",
    "scripts/tests/test-verify.sh",
    "scripts/ai-hooks/cache.sh",
    "scripts/ai-hooks/output-filter.sh",
  ],
  "test-verify-async": [
    "scripts/verify-async.sh",
    "scripts/tests/test-verify-async.sh",
    "scripts/process-tree.sh",
    "scripts/verify.sh",
    "scripts/lib/verify-metadata.sh",
    "scripts/ai-hooks/cache.sh",
  ],
  "test-verify-logs": [
    "scripts/verify-logs.sh",
    "scripts/tests/test-verify-logs.sh",
    "scripts/ai-hooks/cache.sh",
    "scripts/ai-hooks/output-filter.sh",
    "scripts/harness-emit-envelope.ts",
    "packages/shared/src/schemas/harness-diagnostics.ts",
  ],
  "test-verify-history": [
    "scripts/verify-history.sh",
    "scripts/tests/test-verify-history.sh",
    "scripts/lib/verify-metadata.sh",
    ...PATH_POLICY_QUERY_SUBJECTS,
    "scripts/path-policy/path-policy-smoke-subjects.ts",
    "scripts/tests/lib/test-git-env.sh",
    "scripts/verify/steps.generated.sh",
    "scripts/verify/steps-lib.sh",
    ".husky/pre-commit",
    "package.json",
  ],
  "test-worktree-db": [
    "scripts/worktree-db.sh",
    "scripts/worktree-new.sh",
    "scripts/worktree-drift-hook.sh",
    "scripts/dev.sh",
    "scripts/tests/test-worktree-db.sh",
  ],
  "test-dependency-freshness": [
    "scripts/dependency-freshness.sh",
    "scripts/prisma-client-freshness.sh",
    "scripts/doc-length-policy.sh",
    "scripts/lib/verify-metadata.sh",
    "scripts/process-tree.sh",
    "scripts/ai-hooks/output-filter.sh",
    "scripts/verify/steps.generated.sh",
    "scripts/verify/steps-lib.sh",
    ".husky/pre-commit",
    "scripts/tests/lib/test-git-env.sh",
    "scripts/tests/test-dependency-freshness.sh",
  ],
  "test-ai-hooks": [
    "scripts/tests/test-ai-hooks.sh",
    "scripts/harness/generate-hook-wiring.ts",
    "scripts/harness/hook-wiring-schema.ts",
    "scripts/lib/verify-metadata.sh",
    "scripts/ai-hooks/check-wiring.sh",
    "scripts/ai-hooks/",
    "scripts/tests/lib/test-git-env.sh",
    ".claude/hooks/",
    ".codex/hooks/",
    ".claude/settings.json",
    ".codex/hooks.json",
  ],
  "test-eslint-disable-register": [
    "scripts/eslint-disable-register.sh",
    "scripts/tests/lib/test-git-env.sh",
    "scripts/tests/test-eslint-disable-register.sh",
  ],
  "test-suppression-register": [
    "scripts/suppression-register.sh",
    "scripts/tests/lib/test-git-env.sh",
    "scripts/tests/test-suppression-register.sh",
  ],
  "test-codemod-structured-logging-fix": [
    "scripts/codemods/structured-logging-fix-transforms.ts",
    "scripts/codemods/structured-logging-fix.ts",
    "scripts/codemods/lib/",
    "scripts/tests/test-codemod-structured-logging-fix.sh",
    "package.json",
    "tsconfig.scripts.json",
  ],
  "test-codemod-trpc-shared-input": [
    "scripts/codemods/trpc-shared-input-candidates.ts",
    "scripts/codemods/trpc-shared-input.ts",
    "scripts/codemods/lib/",
    "scripts/tests/test-codemod-trpc-shared-input.sh",
    "package.json",
    "tsconfig.scripts.json",
  ],
  "test-codemod-trpc-shared-output": [
    "scripts/codemods/trpc-shared-output-candidates.ts",
    "scripts/codemods/trpc-shared-output.ts",
    "scripts/codemods/lib/",
    "scripts/tests/test-codemod-trpc-shared-output.sh",
    "package.json",
    "tsconfig.scripts.json",
  ],
  "test-codemod-expand-barrel": [
    "scripts/codemods/expand-barrel.ts",
    "scripts/codemods/expand-barrel/",
    "scripts/codemods/lib/",
    "scripts/codemods/fixtures/expand-barrel/",
    "scripts/tests/test-codemod-expand-barrel.sh",
    "package.json",
    "tsconfig.scripts.json",
  ],
  "test-codemod-concurrency-guard": [
    "scripts/codemods/concurrency-guard.ts",
    "scripts/codemods/concurrency-guard/",
    "scripts/codemods/lib/",
    "scripts/codemods/fixtures/concurrency-guard/",
    "scripts/tests/test-codemod-concurrency-guard.sh",
    "package.json",
    "tsconfig.scripts.json",
  ],
  "test-code-intel": [
    "scripts/code-intel.ts",
    "scripts/code-intel-server.ts",
    "scripts/code-intel/",
    "scripts/code-intel.test.ts",
    "scripts/tests/test-code-intel.sh",
    "scripts/vitest.config.ts",
    "package.json",
    "tsconfig.scripts.json",
    "packages/shared/package.json",
    "packages/server/package.json",
    "packages/client/tsconfig.json",
  ],
  "test-format-changed": [
    ".prettierignore",
    ".prettierrc",
    "scripts/format-changed.sh",
    "scripts/lib/changed-base.sh",
    ...PATH_POLICY_QUERY_SUBJECTS,
    "scripts/path-policy/path-policy-smoke-subjects.ts",
    "scripts/tests/lib/test-git-env.sh",
    "scripts/tests/test-format-changed.sh",
  ],
  "test-lint-changed": [
    "scripts/lint-changed.sh",
    "scripts/lint-shell.sh",
    "scripts/lib/parallel-runner.sh",
    "scripts/lib/verify-metadata.sh",
    "scripts/lib/changed-base.sh",
    ...PATH_POLICY_QUERY_SUBJECTS,
    "scripts/tests/lib/test-git-env.sh",
    "scripts/tests/test-lint-changed.sh",
    "eslint-config/",
  ],
  "test-lint-dist-preflight": [
    "scripts/lint.sh",
    "scripts/lint-changed.sh",
    "scripts/lib/lint-dist-preflight.sh",
    "scripts/tests/test-lint-dist-preflight.sh",
    "packages/shared/package.json",
    "packages/server/package.json",
  ],
  "test-lint-shell": [
    "scripts/lint-shell.sh",
    "scripts/lib/parallel-runner.sh",
    "scripts/lib/changed-base.sh",
    ...PATH_POLICY_QUERY_SUBJECTS,
    "scripts/tests/lib/test-git-env.sh",
    "scripts/tests/test-lint-shell.sh",
    "package.json",
    "bun.lock",
  ],
  "test-lint-config-sensors": [
    "scripts/lint-config-sensors.sh",
    "scripts/tests/test-lint-config-sensors.sh",
    "scripts/lint-changed.sh",
    "scripts/lib/verify-metadata.sh",
    "scripts/lib/changed-base.sh",
    ...PATH_POLICY_QUERY_SUBJECTS,
    "scripts/tests/lib/test-git-env.sh",
    ".yamllint.yml",
    "package.json",
    "bun.lock",
    ".github/workflows/",
    "docker-compose.yml",
    ".devcontainer/docker-compose.yml",
    ".devcontainer/Dockerfile",
    ".codex/config.toml",
    ".codex/skills/",
    "bunfig.toml",
  ],
  "test-test-changed": [
    "scripts/test-changed.sh",
    "scripts/vitest.sh",
    "scripts/lib/changed-base.sh",
    "scripts/ai-hooks/output-filter.sh",
    "scripts/tests/lib/test-git-env.sh",
    "scripts/tests/test-test-changed.sh",
  ],
  "test-test-slow": [
    "scripts/test-slow.sh",
    "scripts/test-changed.sh",
    "scripts/vitest.sh",
    "scripts/lib/changed-base.sh",
    "scripts/ai-hooks/output-filter.sh",
    "scripts/tests/lib/test-git-env.sh",
    "vitest.slow.config.ts",
    "packages/shared/vitest.config.ts",
    "packages/server/vitest.config.ts",
    "packages/client/vitest.config.ts",
    "packages/shared/src/test-tier-sentinel.test.ts",
    "packages/shared/src/test-tier-sentinel.slow.test.ts",
    "scripts/tests/test-test-slow.sh",
  ],
  "test-generate-module-index": [
    "scripts/generate-module-index.sh",
    "scripts/tests/lib/test-git-env.sh",
    "scripts/tests/test-generate-module-index.sh",
    "scripts/harness-emit-envelope.ts",
    "packages/shared/src/schemas/harness-diagnostics.ts",
  ],
  "test-generate-lint-guidance": [
    "scripts/generate-lint-guidance.ts",
    "scripts/lib/lint-rule-docs.ts",
    "scripts/tests/test-generate-lint-guidance.sh",
    "scripts/fixtures/generate-lint-guidance/",
    "docs/generated/local-lint-rules.md",
    ...ESLINT_SURFACE_SUBJECTS,
  ],
  "test-generate-harness-controls": [
    "scripts/harness/control-field-validation.ts",
    "scripts/harness/generate-harness-controls.ts",
    "scripts/harness/generate-harness-controls-validation.ts",
    "scripts/harness/hook-wiring-schema.ts",
    "scripts/harness/verify-step-schema.ts",
    "scripts/lib/lint-rule-docs.ts",
    "scripts/tests/test-generate-harness-controls.sh",
    "scripts/fixtures/generate-harness-controls/",
    "harness.controls.json",
    "docs/generated/harness-controls.md",
    ...ESLINT_SURFACE_SUBJECTS,
  ],
  "test-harness-check": [
    "scripts/harness-check.ts",
    "scripts/harness/control-field-validation.ts",
    "scripts/harness/harness-check-validation.ts",
    "scripts/harness/generate-hook-wiring.ts",
    "scripts/harness/generate-verify-steps.ts",
    "scripts/harness/hook-wiring-schema.ts",
    "scripts/ai-hooks/check-wiring.sh",
    "scripts/verify/steps.generated.sh",
    "scripts/verify/steps-lib.sh",
    "scripts/harness/verify-step-schema.ts",
    "scripts/lint-ratchet/ratchet-manifest-message.ts",
    "scripts/tests/test-harness-check.sh",
    ".claude/settings.json",
    ".codex/hooks.json",
    "harness.controls.json",
    ...ESLINT_SURFACE_SUBJECTS,
  ],
  "test-lint-agent": [
    "scripts/lint-agent.ts",
    "scripts/lib/lint-rule-docs.ts",
    "scripts/tests/test-lint-agent.sh",
    "packages/shared/src/schemas/harness-diagnostics.ts",
    ...ESLINT_SURFACE_SUBJECTS,
  ],
  "test-lint-agent-changed": [
    "scripts/lint-agent-changed.sh",
    "scripts/lint-agent.ts",
    "scripts/lib/changed-base.sh",
    "scripts/harness-emit-envelope.ts",
    ...PATH_POLICY_QUERY_SUBJECTS,
    "scripts/tests/lib/test-git-env.sh",
    "scripts/tests/test-lint-agent-changed.sh",
    "packages/shared/src/schemas/harness-diagnostics.ts",
    "package.json",
    "eslint-config/",
  ],
  "test-harness-emit-envelope": [
    "scripts/harness-emit-envelope.ts",
    "scripts/tests/test-harness-emit-envelope.sh",
    "packages/shared/src/schemas/harness-diagnostics.ts",
  ],
  "test-slow-drift-audit": [
    "scripts/slow-drift-audit.sh",
    "scripts/tests/test-slow-drift-audit.sh",
  ],
  "test-lint-ratchet": [
    "scripts/lint-ratchet.ts",
    "scripts/lint-ratchet/",
    "scripts/lint-ratchet/lint-ratchet-debt-log.test.ts",
    "scripts/lint-ratchet/lint-ratchet-debt-log-schema.test.ts",
    "scripts/lint-ratchet/lint-ratchet-debt-log-write.test.ts",
    "scripts/lint-ratchet/lint-ratchet-baseline-compare.ts",
    "scripts/lint-ratchet/lint-ratchet-baseline-parse.ts",
    "scripts/lint-ratchet/lint-ratchet-baseline.ts",
    "scripts/lint-ratchet/lint-ratchet-baseline.test.ts",
    "scripts/lint-ratchet/lint-ratchet-check-registry.ts",
    "scripts/lint-ratchet/lint-ratchet-check-registry.test.ts",
    "scripts/lint-ratchet/lint-ratchet-output.ts",
    "scripts/lint-ratchet/lint-ratchet-output.test.ts",
    "scripts/lint-ratchet/lint-ratchet-registry-builders.ts",
    "scripts/lint-ratchet/lint-ratchet-report.ts",
    "scripts/lint-ratchet/lint-ratchet-report.test.ts",
    "scripts/lint-ratchet/lint-ratchet-summary.ts",
    "scripts/lint-ratchet/lint-ratchet-summary.test.ts",
    "scripts/lint-ratchet/lint-ratchet-zero-baseline.ts",
    "scripts/lint-ratchet/lint-ratchet-zero-baseline.test.ts",
    "scripts/fixtures/lint-ratchet/",
    "scripts/git/install-lint-ratchet-merge-driver.sh",
    "scripts/git/lint-ratchet-baseline-merge-driver.sh",
    "scripts/lib/lint-rule-docs.ts",
    "scripts/lint-ratchet/ratchet-manifest-message.ts",
    "scripts/tests/lib/test-git-env.sh",
    "scripts/tests/lib/test-lint-ratchet-edit-check-fixtures.sh",
    "scripts/tests/test-lint-ratchet.sh",
    "lint-ratchet.baseline.json",
    "packages/shared/src/schemas/harness-diagnostics.ts",
    ...ESLINT_SURFACE_SUBJECTS,
  ],
  "test-migration-safety-scan": [
    "scripts/migration-safety-scan.sh",
    "scripts/tests/lib/test-git-env.sh",
    "scripts/tests/test-migration-safety-scan.sh",
    "scripts/harness-emit-envelope.ts",
    "packages/shared/src/schemas/harness-diagnostics.ts",
  ],
  "test-doctor-json": [
    "scripts/doctor.sh",
    "scripts/dependency-freshness.sh",
    "scripts/harness-emit-envelope.ts",
    "scripts/tests/lib/test-git-env.sh",
    "scripts/tests/test-doctor-json.sh",
    "harness.controls.json",
    "packages/shared/src/schemas/harness-diagnostics.ts",
  ],
  "test-parallel-runner": [
    "scripts/lib/parallel-runner.sh",
    "scripts/tests/test-parallel-runner.sh",
  ],
  "test-verify-metadata": [
    "scripts/lib/verify-metadata.sh",
    ...PATH_POLICY_QUERY_SUBJECTS,
    "scripts/tests/lib/test-git-env.sh",
    "scripts/tests/test-verify-metadata.sh",
  ],
  "test-test-scripts": [
    "scripts/test-scripts.sh",
    "scripts/lib/changed-base.sh",
    "scripts/tests/lib/test-git-env.sh",
    "scripts/tests/test-test-scripts.sh",
    ...PATH_POLICY_QUERY_SUBJECTS,
    "scripts/path-policy/path-policy-smoke-subjects.ts",
  ],
  "test-check-fast-uri-override": [
    "scripts/check-fast-uri-override.sh",
    "scripts/tests/test-check-fast-uri-override.sh",
  ],
  "test-check-eslint-react-peer-exception": [
    "scripts/check-eslint-react-peer-exception.sh",
    "scripts/tests/test-check-eslint-react-peer-exception.sh",
  ],
} as const satisfies ScriptSmokeSubjects;

function discoverScriptSmokeTestNames(): readonly string[] {
  const testsDir = join(process.cwd(), "scripts", "tests");
  const subjectNames = Object.keys(SCRIPT_SMOKE_SUBJECTS);
  if (!existsSync(testsDir)) return subjectNames;

  const discovered = new Set(
    readdirSync(testsDir)
      .filter((entry) => /^test-.+\.sh$/u.test(entry))
      .map((entry) => entry.slice(0, -".sh".length)),
  );
  const ordered = subjectNames.filter((name) => discovered.has(name));
  const extra = [...discovered].filter((name) => !subjectNames.includes(name)).sort();
  return [...ordered, ...extra];
}

export const SCRIPT_SMOKE_TEST_NAMES = discoverScriptSmokeTestNames();
