import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

import { parseCheckModeArgs, readCurrentOutput } from "../lib/doc-generator.js";
import { validateFixtureShellDependencies } from "./fixture-shell-dependencies.js";

const smokeFilePattern = /^test-.+\.sh$/u;
const smokeSubjectsHeaderPrefixPattern = /^#\s*smoke-subjects:/u;
const smokeOrderHeaderPattern = /^#\s*smoke-order:\s*(\d+)\s*$/u;
const missingOrderSortValue = Number.MAX_SAFE_INTEGER;

export interface SmokeSubjectDefinition {
  readonly name: string;
  readonly relativePath: string;
  readonly subjects: readonly string[];
  readonly order: number | undefined;
}

export interface SmokeSubjectGeneratedOutput {
  readonly path: string;
  readonly rendered: string;
}

function normalizePath(path: string): string {
  return path.replaceAll("\\", "/");
}

function smokeNameFromFileName(fileName: string): string {
  return fileName.slice(0, -".sh".length);
}

function listSmokeFileNames(testsDir: string): readonly string[] {
  if (!existsSync(testsDir)) return [];
  return readdirSync(testsDir)
    .filter((entry) => smokeFilePattern.test(entry))
    .sort();
}

function parseSubjects(
  relativePath: string,
  lineNumber: number,
  headerValue: string,
): readonly string[] {
  const subjects = headerValue.trim().split(/\s+/u).filter(Boolean);
  if (subjects.length === 0) {
    throw new Error(`${relativePath}:${String(lineNumber)} smoke-subjects header has no subjects`);
  }
  for (const subject of subjects) {
    if (subject.startsWith("/") || subject.includes("\\")) {
      throw new Error(
        `${relativePath}:${String(lineNumber)} smoke-subjects must be repo-relative POSIX paths: ${subject}`,
      );
    }
  }
  return subjects;
}

function parseSmokeFile(
  repoRoot: string,
  fileName: string,
  sourceOverrides: ReadonlyMap<string, string>,
): SmokeSubjectDefinition {
  const path = join(repoRoot, "scripts", "tests", fileName);
  const relativePath = normalizePath(relative(repoRoot, path));
  const subjects: string[] = [];
  let order: number | undefined;

  const source = sourceOverrides.get(relativePath) ?? readFileSync(path, "utf8");
  const lines = source.split(/\r?\n/u);
  for (const [index, line] of lines.entries()) {
    const lineNumber = index + 1;
    if (smokeSubjectsHeaderPrefixPattern.test(line)) {
      const headerValue = line.replace(smokeSubjectsHeaderPrefixPattern, "");
      subjects.push(...parseSubjects(relativePath, lineNumber, headerValue));
      continue;
    }
    const orderMatch = smokeOrderHeaderPattern.exec(line);
    if (orderMatch !== null) {
      if (order !== undefined) {
        throw new Error(`${relativePath}:${String(lineNumber)} declares more than one smoke-order`);
      }
      order = Number(orderMatch[1]);
    }
  }

  if (subjects.length === 0) {
    throw new Error(`${relativePath} must declare at least one # smoke-subjects: header`);
  }
  if (!subjects.includes(relativePath)) {
    throw new Error(`${relativePath} smoke-subjects must include ${relativePath}`);
  }
  if (new Set(subjects).size !== subjects.length) {
    throw new Error(`${relativePath} smoke-subjects contains duplicate subjects`);
  }

  return {
    name: smokeNameFromFileName(fileName),
    relativePath,
    subjects,
    order,
  };
}

function assertUniqueOrders(definitions: readonly SmokeSubjectDefinition[]): void {
  const owners = new Map<number, string>();
  for (const definition of definitions) {
    if (definition.order === undefined) continue;
    const owner = owners.get(definition.order);
    if (owner !== undefined) {
      throw new Error(
        `${definition.relativePath} and ${owner} both declare smoke-order ${String(definition.order)}`,
      );
    }
    owners.set(definition.order, definition.relativePath);
  }
}

function compareDefinitionOrder(
  left: SmokeSubjectDefinition,
  right: SmokeSubjectDefinition,
): number {
  const orderDifference =
    (left.order ?? missingOrderSortValue) - (right.order ?? missingOrderSortValue);
  if (orderDifference !== 0) return orderDifference;
  return left.name.localeCompare(right.name);
}

export function collectSmokeSubjectDefinitions(
  repoRoot: string,
  sourceOverrides: ReadonlyMap<string, string> = new Map(),
): readonly SmokeSubjectDefinition[] {
  const testsDir = join(repoRoot, "scripts", "tests");
  const definitions = listSmokeFileNames(testsDir).map((fileName) =>
    parseSmokeFile(repoRoot, fileName, sourceOverrides),
  );
  assertUniqueOrders(definitions);
  return definitions.slice().sort(compareDefinitionOrder);
}

function jsonString(value: string): string {
  return JSON.stringify(value);
}

export function renderSmokeSubjectsData(definitions: readonly SmokeSubjectDefinition[]): string {
  const lines = [
    "// Generated by scripts/path-policy/generate-smoke-subjects.ts. Do not edit by hand.",
    "export type ScriptSmokeSubjects = Record<string, readonly string[]>;",
    "",
    "// prettier-ignore",
    "export const SCRIPT_SMOKE_SUBJECTS = {",
  ];

  for (const definition of definitions) {
    lines.push(`  ${jsonString(definition.name)}: [`);
    for (const subject of definition.subjects) {
      lines.push(`    ${jsonString(subject)},`);
    }
    lines.push("  ],");
  }

  lines.push("} as const satisfies ScriptSmokeSubjects;", "");
  return lines.join("\n");
}

export function renderAllSmokeTestsFixture(definitions: readonly SmokeSubjectDefinition[]): string {
  const names = definitions
    .slice()
    .sort((left, right) => left.relativePath.localeCompare(right.relativePath))
    .map((definition) => `runner ran ${definition.name}`);
  return `${names.join("\n")}\n`;
}

export function projectSmokeSubjectOutputs(
  repoRoot: string,
  sourceOverrides: ReadonlyMap<string, string> = new Map(),
): readonly SmokeSubjectGeneratedOutput[] {
  validateFixtureShellDependencies(repoRoot);
  const definitions = collectSmokeSubjectDefinitions(repoRoot, sourceOverrides);
  return [
    {
      path: join(repoRoot, "scripts", "path-policy", "path-policy-smoke-subjects-data.ts"),
      rendered: renderSmokeSubjectsData(definitions),
    },
    {
      path: join(repoRoot, "scripts", "fixtures", "test-scripts", "all-smoke-tests.txt"),
      rendered: renderAllSmokeTestsFixture(definitions),
    },
  ];
}

export function diffSmokeSubjectOutputs(outputs: readonly SmokeSubjectGeneratedOutput[]): string[] {
  return outputs
    .filter((output) => readCurrentOutput(output.path) !== output.rendered)
    .map((output) => output.path);
}

export function writeSmokeSubjectOutputs(outputs: readonly SmokeSubjectGeneratedOutput[]): void {
  for (const output of outputs) {
    mkdirSync(dirname(output.path), { recursive: true });
    writeFileSync(output.path, output.rendered);
    console.log(`Wrote ${output.path}.`);
  }
}

export function checkOrWriteSmokeSubjectOutputs(repoRoot: string, argv: readonly string[]): void {
  const { checkMode } = parseCheckModeArgs(argv);
  const outputs = projectSmokeSubjectOutputs(repoRoot);

  if (!checkMode) {
    writeSmokeSubjectOutputs(outputs);
    return;
  }

  const drifted = diffSmokeSubjectOutputs(outputs);
  for (const path of drifted) {
    console.error(
      `${path} is out of date. Run \`bun run test:scripts:subjects\` and commit the result.`,
    );
  }
  if (drifted.length > 0) {
    process.exitCode = 1;
    return;
  }
  console.log("Smoke subject generated files are up to date.");
}
