// Pure projections of the root `commandPolicy` rule set: the committed shell
// fragment the policy hooks source and the Claude-native `permissions.deny`
// array the projectable rules flatten into.
//
// Nothing here spawns, reads, or writes: `bun run harness:command-policy` and
// `harness:check` supply the file text. Enforcement stays bash+awk+jq — the
// generator runs at build time and the hooks source pre-rendered committed
// bytes, never a runtime projection.

import { isObjectLike } from "../lib/records.js";
import type { CommandPolicyMatcher, CommandPolicyRule } from "./command-policy-schema.js";

/** Field separator inside the newline-delimited matcher blocks the fragment renders. */
const MATCHER_FIELD_SEPARATOR = "\t";
const JSON_INDENT = 2;

function shellSingleQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function matcherValue(matcher: CommandPolicyMatcher): string {
  switch (matcher.kind) {
    case "pattern":
      return matcher.pattern;
    case "literal":
      return matcher.literal;
    case "predicate":
      return matcher.predicate;
  }
}

function matcherLine(matcher: CommandPolicyMatcher): string {
  return `${matcher.kind}${MATCHER_FIELD_SEPARATOR}${matcherValue(matcher)}`;
}

/** `name[key]=value` assignment lines for one associative array, in rule order. */
function renderAssociativeEntries(
  name: string,
  rules: readonly CommandPolicyRule[],
  valueOf: (rule: CommandPolicyRule) => string | undefined,
): readonly string[] {
  const lines = [`declare -gA ${name}=()`];
  for (const rule of rules) {
    const value = valueOf(rule);
    if (value !== undefined) {
      lines.push(`${name}[${shellSingleQuote(rule.id)}]=${shellSingleQuote(value)}`);
    }
  }
  lines.push("");
  return lines;
}

/**
 * Render the committed fragment `policy.sh` sources.
 *
 * Every value is single-quoted, so `${AI_POLICY_GIT_CMD}` and
 * `$AI_POLICY_CMD_END` inside a pattern survive sourcing as literal text; the
 * consumer expands them at match time, when those variables are defined. An
 * absent key is meaningful in two arrays and only those two: no entry in
 * `AI_POLICY_RULE_MESSAGE` means the rule's predicate emits its own reason, and
 * no entry in `AI_POLICY_RULE_NATIVE_MATCHERS` means the rule is a deliberate
 * non-projection whose reason is in `AI_POLICY_RULE_NATIVE_EXCLUSION`.
 */
// porting-knob: command-policy -- retarget the hard-deny rule set and its native permission projection
export function renderCommandPolicyFragment(rules: readonly CommandPolicyRule[]): string {
  const messageConstants = rules.flatMap((rule) =>
    "constant" in rule.message
      ? [`declare -g ${rule.message.constant}=${shellSingleQuote(rule.message.text)}`]
      : [],
  );
  const lines = [
    "# shellcheck shell=bash",
    "# shellcheck disable=SC2034",
    "# Generated by scripts/harness/generate-command-policy.ts. Do not edit by hand.",
    "# Rule rows live in harness.controls.json (root commandPolicy array);",
    "# regenerate with `bun run harness:command-policy`.",
    "#",
    "# AI_POLICY_RULE_IDS is the scan order: first hard match wins; otherwise the first soft match advises. Pattern",
    "# matchers keep ${AI_POLICY_GIT_CMD} / $AI_POLICY_CMD_END symbolic, so a",
    "# consumer expands them at match time. Matcher blocks are newline-separated",
    "# `<kind><TAB><value>` lines in evaluation order.",
    "",
    ...messageConstants,
    "",
    `declare -ga AI_POLICY_RULE_IDS=(${rules.map((rule) => shellSingleQuote(rule.id)).join(" ")})`,
    "",
    ...renderAssociativeEntries("AI_POLICY_RULE_CLASS", rules, (rule) => rule.class),
    ...renderAssociativeEntries("AI_POLICY_RULE_SCOPE", rules, (rule) => rule.scope),
    ...renderAssociativeEntries("AI_POLICY_RULE_MESSAGE", rules, (rule) =>
      "text" in rule.message ? rule.message.text : undefined,
    ),
    ...renderAssociativeEntries(
      "AI_POLICY_RULE_HAYSTACK_TRANSFORM",
      rules,
      (rule) => rule.haystackTransform,
    ),
    ...renderAssociativeEntries("AI_POLICY_RULE_MATCHERS", rules, (rule) =>
      rule.matchers.map(matcherLine).join("\n"),
    ),
    ...renderAssociativeEntries("AI_POLICY_RULE_NATIVE_MATCHERS", rules, (rule) =>
      rule.nativePermissions.projected ? rule.nativePermissions.matchers.join("\n") : undefined,
    ),
    ...renderAssociativeEntries("AI_POLICY_RULE_NATIVE_EXCLUSION", rules, (rule) =>
      rule.nativePermissions.projected ? undefined : rule.nativePermissions.reason,
    ),
    "# Completion sentinel: policy.sh resets this before sourcing and fails closed",
    "# unless the fragment reaches this final statement with the expected rule count.",
    `declare -g AI_POLICY_RULES_COMPLETE=${String(rules.length)}`,
  ];
  while (lines[lines.length - 1] === "") lines.pop();
  return `${lines.join("\n")}\n`;
}

/**
 * The `.claude/settings.json` `permissions.deny` array these rules expect:
 * every projected rule's matchers, in rule order and then matcher order.
 * Non-projections contribute nothing — that is the point of the field.
 */
function expectedNativeDenyEntries(rules: readonly CommandPolicyRule[]): readonly string[] {
  return rules.flatMap((rule) =>
    rule.nativePermissions.projected ? rule.nativePermissions.matchers : [],
  );
}

function denyValue(settingsJsonText: string): unknown {
  const parsed: unknown = JSON.parse(settingsJsonText);
  if (!isObjectLike(parsed) || !isObjectLike(parsed.permissions)) return undefined;
  return parsed.permissions.deny;
}

/** The committed deny array, or a diagnostic tail describing why it is unreadable. */
function readDenyArray(settingsJsonText: string): readonly string[] | string {
  let deny: unknown;
  try {
    deny = denyValue(settingsJsonText);
  } catch (error) {
    return `is not valid JSON: ${error instanceof Error ? error.message : String(error)}`;
  }
  if (!Array.isArray(deny) || !deny.every((entry) => typeof entry === "string")) {
    return "must declare permissions.deny as an array of strings";
  }
  return deny.filter((entry): entry is string => typeof entry === "string");
}

function describeDenyDrift(deny: readonly string[], expected: readonly string[]): string {
  const expectedSet = new Set(expected);
  const denySet = new Set(deny);
  const unclaimed = deny.filter((entry) => !expectedSet.has(entry));
  const missing = expected.filter((entry) => !denySet.has(entry));
  const parts = [
    unclaimed.length === 0
      ? undefined
      : `entries no commandPolicy rule projects: ${unclaimed.join(", ")}`,
    missing.length === 0 ? undefined : `projected entries not denied: ${missing.join(", ")}`,
  ].filter((part) => part !== undefined);
  return parts.length === 0
    ? "the entries agree but their order does not; the array must follow commandPolicy rule order, then matcher order"
    : parts.join("; ");
}

export interface NativeDenyParityOptions {
  readonly rules: readonly CommandPolicyRule[];
  readonly settingsJsonText: string;
  readonly settingsPath: string;
  /** The command named in the repair hint. */
  readonly refreshCommand: string;
}

/**
 * Compare the committed native deny array against the projection.
 *
 * Read with `JSON.parse`, not a JSONC dependency: prior-pack CQ25-129 refused
 * that rewrite, and a *check* needs only the values — the localized text
 * scanner exists for the hook-wiring generator, which has to write back into
 * this file without disturbing its formatting.
 *
 * Order-sensitive on purpose: the array is a projection of an ordered rule set,
 * and a stable rendering is what makes a diff here readable as "this rule's
 * matchers changed" rather than "something somewhere moved".
 */
export function collectNativeDenyParityFailures(
  options: NativeDenyParityOptions,
): readonly string[] {
  const deny = readDenyArray(options.settingsJsonText);
  if (typeof deny === "string") return [`${options.settingsPath} ${deny}`];

  const expected = expectedNativeDenyEntries(options.rules);
  if (deny.length === expected.length && deny.every((entry, index) => entry === expected[index])) {
    return [];
  }
  return [
    [
      `${options.settingsPath} permissions.deny does not match the commandPolicy projection: ${describeDenyDrift(deny, expected)}.`,
      `Expected array:\n${JSON.stringify(expected, null, JSON_INDENT)}`,
      `Repair ${options.settingsPath} (or the rule's nativePermissions in harness.controls.json), then re-run \`bun run ${options.refreshCommand}\`.`,
    ].join("\n"),
  ];
}
