// Renders docs/generated/command-catalog.md: every package.json script across
// every tracked manifest, grouped by name family, with what it is for, what it
// does to the tree, and where to run it from.
//
// Single-sourced from harness.controls.json. Control-declared scripts project
// their purpose from the control record; everything else projects it from the
// root `commandCatalog` section. No third data file, and nothing here restates
// a purpose that already exists in a control.
//
// The per-family audience blurbs live in command-catalog-sections.ts and are
// required: a family with no blurb throws rather than rendering an unlabeled
// section, so a new command prefix cannot appear here unannounced.

import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { compareByCodepoint } from "../lib/codepoint-compare.js";
import { runDocGenerator } from "../lib/doc-generator.js";
import {
  buildCommandRows,
  type BuildCommandRowsInputs,
  type CommandRow,
} from "./command-catalog.js";
import { COMMAND_EFFECT_MEANINGS } from "./command-catalog-schema.js";
import { GROUP_BLURBS } from "./command-catalog-sections.js";
import { buildControlCommandSources } from "./command-catalog-sources.js";
import { loadTypedHarnessManifest } from "./harness-manifest-loader.js";
import { GENERATED_COMMAND_CATALOG_DOC_PATH } from "./harness-paths.js";
import { loadPackageManifestSurface } from "./package-manifest-scripts.js";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const outputPath = join(repoRoot, GENERATED_COMMAND_CATALOG_DOC_PATH);

function docLink(doc: string): string {
  const relative = doc.startsWith("docs/") ? `../${doc.slice("docs/".length)}` : `../../${doc}`;
  return `[${doc}](${relative})`;
}

function referenceCell(row: CommandRow): string {
  const parts: string[] = [];
  if (row.controlIds.length === 1) {
    parts.push(`control \`${row.controlIds[0] ?? ""}\``);
  } else if (row.controlIds.length > 1) {
    parts.push(`${String(row.controlIds.length)} controls`);
  }
  if (row.doc !== undefined) parts.push(docLink(row.doc));
  return parts.length === 0 ? "—" : parts.join("<br>");
}

function escapeCell(text: string): string {
  return text.replace(/\|/gu, "\\|").replace(/\n/gu, " ");
}

function renderGroup(group: string, rows: readonly CommandRow[]): readonly string[] {
  const blurb = GROUP_BLURBS.get(group);
  if (blurb === undefined) {
    throw new Error(
      `command catalog: no section blurb for the "${group}" script family. Add one to GROUP_BLURBS in scripts/harness/command-catalog-sections.ts saying who those commands are for.`,
    );
  }
  return [
    `## ${blurb.title}`,
    "",
    blurb.blurb,
    "",
    "| Command | Effect | Purpose | Reference |",
    "| --- | --- | --- | --- |",
    ...rows.map(
      (row) =>
        `| \`${row.invocation}\` | ${row.effect} | ${escapeCell(row.purpose)} | ${referenceCell(row)} |`,
    ),
    "",
  ];
}

/** Everything the page needs, in one load: the manifest plus the live scripts. */
function loadCommandSurface(): BuildCommandRowsInputs {
  const manifest = loadTypedHarnessManifest(repoRoot);
  const { manifests, workspacePackageNames } = loadPackageManifestSurface(repoRoot);
  return {
    manifests,
    workspacePackageNames,
    controlSources: buildControlCommandSources(manifest),
    catalog: manifest.commandCatalog ?? [],
  };
}

function render(): { readonly rendered: string; readonly wroteSuffix: string } {
  const surface = loadCommandSurface();
  const rows = buildCommandRows(surface);
  const grouped = new Map<string, CommandRow[]>();
  for (const row of rows) {
    const bucket = grouped.get(row.group);
    if (bucket === undefined) grouped.set(row.group, [row]);
    else bucket.push(row);
  }
  const scriptCount = surface.manifests.reduce(
    (total, manifest) => total + manifest.scripts.size,
    0,
  );
  // Split by where the PURPOSE comes from, not by whether a control backs the
  // row: an aggregating command has both a control list and an authored entry.
  const catalogKeys = new Set(surface.catalog.map((entry) => `${entry.manifest}::${entry.script}`));
  const authored = rows.filter((row) => catalogKeys.has(`${row.manifest}::${row.script}`)).length;
  const controlBacked = rows.length - authored;
  const lines: string[] = [
    "# Command Catalog",
    "",
    "> Generated by `scripts/harness/generate-command-catalog.ts`. Do not edit by hand.",
    "> Refresh with `bun run docs:command-catalog`.",
    "",
    `Every package.json script in this repository: ${String(scriptCount)} keys across ${String(surface.manifests.length)} tracked manifests, grouped by name family. This page is the authority for *what a command is for*; \`README.md\` and \`AGENTS.md\` cover the everyday subset and link here for the rest.`,
    "",
    `Nothing here is hand-written per row. ${String(controlBacked)} commands project their purpose from the harness control that registers them (see [harness-controls.md](./harness-controls.md) for the full principle, source file and repair path); the remaining ${String(authored)} project it from the \`commandCatalog\` section of \`harness.controls.json\` — the scripts no control reaches, plus the few aggregating commands whose controls are the rules they run rather than descriptions of the command. \`bun run harness:check\` fails when any script in any tracked manifest has neither — which is what stops a new command from landing undocumented.`,
    "",
    "**Where to run it from.** The `Command` column carries the full form. Root scripts are plain `bun run <script>`; workspace packages need `--filter <package>` because a bare `bun run` resolves against the nearest `package.json`; anything outside the workspaces needs `--cwd`.",
    "",
    "**Effect** is what running the command does to your tree:",
    "",
    ...Object.entries(COMMAND_EFFECT_MEANINGS).map(
      ([effect, meaning]) => `- \`${effect}\` — ${meaning}`,
    ),
    "",
  ];
  for (const group of [...grouped.keys()].sort(compareByCodepoint)) {
    lines.push(...renderGroup(group, grouped.get(group) ?? []));
  }
  return {
    rendered: `${lines.join("\n").trimEnd()}\n`,
    wroteSuffix: ` (${String(rows.length)} command(s) in ${String(grouped.size)} families)`,
  };
}

runDocGenerator({
  outputPath,
  refreshCommand: "docs:command-catalog",
  render,
});
