import { describe, expect, it } from "vitest";

import { renderHookTimeoutConstantsShellFromManifest } from "./hook-timeout-constants.js";

function manifestWithTimeouts(bunTimeout: number, gitTimeout: number): unknown {
  return {
    controls: [
      {
        id: "hook/ai-bun-run-quiet",
        hookWiring: {
          event: "PreToolUse",
          order: 10,
          harnesses: {
            claude: {
              matcher: "Bash",
              command: "bash .claude/hooks/bun-run-quiet.sh",
              timeout: bunTimeout,
            },
          },
          notes: {
            codex: "Fixture only.",
            copilot: "Fixture only.",
          },
        },
      },
      {
        id: "hook/ai-git-commit-quiet",
        hookWiring: {
          event: "PreToolUse",
          order: 20,
          harnesses: {
            claude: {
              matcher: "Bash",
              command: "bash .claude/hooks/git-commit-quiet.sh",
              timeout: gitTimeout,
            },
          },
          notes: {
            codex: "Fixture only.",
            copilot: "Fixture only.",
          },
        },
      },
    ],
  };
}

describe("hook timeout constants generator", () => {
  it("renders shell constants from manifest hook wiring timeouts", () => {
    expect(renderHookTimeoutConstantsShellFromManifest(manifestWithTimeouts(1260, 900)))
      .toBe(`# shellcheck shell=bash
# shellcheck disable=SC2034
# Generated by scripts/harness/generate-hook-timeout-constants.ts. Do not edit by hand.

BUN_RUN_QUIET_HOOK_TIMEOUT=1260
GIT_COMMIT_QUIET_HOOK_TIMEOUT=900
`);
  });

  it("requires timeout-bearing hook wiring for bound quiet hooks", () => {
    expect(() =>
      renderHookTimeoutConstantsShellFromManifest({
        controls: [
          {
            id: "hook/ai-bun-run-quiet",
            hookWiring: {
              event: "PreToolUse",
              order: 10,
              harnesses: {
                claude: {
                  matcher: "Bash",
                  command: "bash .claude/hooks/bun-run-quiet.sh",
                  timeout: 1260,
                },
              },
              notes: {
                codex: "Fixture only.",
                copilot: "Fixture only.",
              },
            },
          },
          {
            id: "hook/ai-git-commit-quiet",
            hookWiring: {
              event: "PreToolUse",
              order: 20,
              harnesses: {
                claude: {
                  matcher: "Bash",
                  command: "bash .claude/hooks/git-commit-quiet.sh",
                },
              },
              notes: {
                codex: "Fixture only.",
                copilot: "Fixture only.",
              },
            },
          },
        ],
      }),
    ).toThrow("hookWiring.harnesses.claude.timeout is required for GIT_COMMIT_QUIET_HOOK_TIMEOUT");
  });
});
