import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { compareByCodepoint } from "@musi/lint-ratchet/kernel/codepoint-compare.js";

import { runDocGenerator } from "../lib/doc-generator.js";
import { lintRatchets } from "../lint-ratchet/lint-ratchet-config.js";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const outputPath = join(repoRoot, "eslint-config/ratchet-restricted-disable-rules.generated.js");

function renderRestrictedDisableRules(): string {
  // codepoint order, not localeCompare — load-bearing for committed/freshness-compared bytes:
  // this list is rendered verbatim into the committed generated file and freshness-gated.
  const ruleIds = [...new Set(lintRatchets.map((ratchet) => ratchet.ruleId))].sort(
    compareByCodepoint,
  );
  return [
    "// @ts-check",
    "// Generated by scripts/harness/generate-restricted-disable-rules.ts. Do not edit by hand.",
    "",
    "export const ratchetRestrictedDisableRuleIds = Object.freeze([",
    ...ruleIds.map((ruleId) => `  ${JSON.stringify(ruleId)},`),
    "]);",
    "",
  ].join("\n");
}

function main(): void {
  runDocGenerator({
    outputPath,
    refreshCommand: "lint:restricted-disable-rules",
    render: () => ({
      rendered: renderRestrictedDisableRules(),
      wroteSuffix: ` (${String(lintRatchets.length)} ratchet rule source(s))`,
    }),
  });
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
