import { join } from "node:path";

import { runDocGenerator } from "../lib/doc-generator.js";
import { GENERATED_SURFACE_FRESHNESS_PATH } from "./harness-paths.js";

export interface GeneratedSurfaceFreshnessEntry {
  /** Exact repo paths, or directory prefixes ending in slash, that can stale the outputs. */
  readonly triggerPaths: readonly string[];
  readonly outputPaths: readonly string[];
  readonly checkScript: string;
  readonly warnLabel: string;
}

// porting-knob: generated-surface-freshness -- retarget generated inputs, outputs, and checks
export const GENERATED_SURFACE_FRESHNESS: readonly GeneratedSurfaceFreshnessEntry[] = [
  {
    triggerPaths: [
      "scripts/path-policy/generate-smoke-subjects.ts",
      "scripts/path-policy/smoke-subject-headers.ts",
      "scripts/path-policy/fixture-shell-dependencies.ts",
      "scripts/path-policy/fixture-shell-scope.ts",
      "scripts/tests/",
    ],
    outputPaths: [
      "scripts/path-policy/path-policy-smoke-subjects-data.ts",
      "scripts/fixtures/test-scripts/all-smoke-tests.txt",
    ],
    checkScript: "test:scripts:subjects:check",
    warnLabel: "script smoke-subject metadata",
  },
  {
    triggerPaths: [
      "harness.controls.json",
      "scripts/harness/generate-verify-steps.ts",
      "scripts/harness/generated-surface-freshness.ts",
      "scripts/harness/verify-step-schema.ts",
      "scripts/harness/verify-step-bridge-divergences.ts",
    ],
    outputPaths: [
      "scripts/verify/steps.generated.sh",
      "scripts/harness/generated-surface-freshness.generated.sh",
    ],
    checkScript: "verify:steps:check",
    warnLabel: "verify step and generated-surface metadata",
  },
  {
    triggerPaths: [
      "harness.controls.json",
      "scripts/harness/generate-hook-timeout-constants.ts",
      "scripts/harness/hook-timeout-constants.ts",
    ],
    outputPaths: ["scripts/ai-hooks/hook-timeouts.generated.sh"],
    checkScript: "harness:hook-timeouts:check",
    warnLabel: "hook timeout constants",
  },
  {
    triggerPaths: ["eslint-config/shared-policy.js", "scripts/harness/generate-config-surfaces.ts"],
    outputPaths: ["tsconfig.configs.json"],
    checkScript: "harness:config-surfaces:check",
    warnLabel: "config surface tsconfig",
  },
  {
    triggerPaths: [
      "harness.controls.json",
      "scripts/harness/generate-hook-wiring.ts",
      "scripts/harness/hook-wiring-schema.ts",
    ],
    outputPaths: [".claude/settings.json", ".codex/hooks.json", ".github/hooks/copilot.json"],
    checkScript: "harness:wiring:check",
    warnLabel: "AI hook wiring",
  },
  {
    triggerPaths: [
      "eslint-rules/",
      "eslint-config/local-plugin.js",
      "scripts/generate-lint-guidance.ts",
      "scripts/lib/lint-rule-docs.ts",
    ],
    outputPaths: ["docs/generated/local-lint-rules.md"],
    checkScript: "docs:lint-guidance:check",
    warnLabel: "lint guidance",
  },
  {
    triggerPaths: [
      "scripts/git/baseline-merge-driver.sh",
      "scripts/generate-baseline-conflict-recipes.ts",
    ],
    outputPaths: ["docs/guides/lint-ratchet-merges.md"],
    checkScript: "docs:baseline-conflict-recipes:check",
    warnLabel: "baseline conflict recovery recipes",
  },
  {
    triggerPaths: [
      "harness.controls.json",
      "scripts/harness/generate-harness-controls.ts",
      "scripts/harness/generate-harness-controls-validation.ts",
      "scripts/harness/control-field-validation.ts",
    ],
    outputPaths: ["docs/generated/harness-controls.md"],
    checkScript: "docs:harness-controls:check",
    warnLabel: "harness controls docs",
  },
  {
    triggerPaths: [
      "scripts/harness/generate-restricted-disable-rules.ts",
      "scripts/lint-ratchet/lint-ratchet-config.ts",
    ],
    outputPaths: ["eslint-config/ratchet-restricted-disable-rules.generated.js"],
    checkScript: "lint:restricted-disable-rules:check",
    warnLabel: "restricted-disable rule metadata",
  },
];

function shellSingleQuote(value: string): string {
  return "'" + value.replaceAll("'", "'\\''") + "'";
}

function renderCasePattern(path: string): string {
  return path.endsWith("/") ? shellSingleQuote(path) + "*" : shellSingleQuote(path);
}

export function renderGeneratedSurfaceFreshnessShell(
  entries: readonly GeneratedSurfaceFreshnessEntry[],
): string {
  const lines = [
    "# shellcheck shell=bash",
    "# Generated by scripts/harness/generate-verify-steps.ts. Do not edit by hand.",
    "# Freshness records live in scripts/harness/generated-surface-freshness.ts.",
    "",
    "musi_warn_generated_surfaces_stale() {",
    "  local staged staged_path",
    '  staged="$(git diff --cached --name-only --diff-filter=ACMR)"',
    '  [ -n "$staged" ] || return 0',
  ];

  for (const entry of entries) {
    const patterns = [...entry.triggerPaths, ...entry.outputPaths].map(renderCasePattern).join("|");
    lines.push(
      "",
      "  while IFS= read -r staged_path; do",
      '    case "$staged_path" in',
      "      " + patterns + ")",
      "        warn_if_generated_surface_stale " +
        shellSingleQuote(entry.warnLabel) +
        " " +
        shellSingleQuote(entry.checkScript),
      "        break",
      "        ;;",
      "    esac",
      '  done <<< "$staged"',
    );
  }
  lines.push("}", "");
  return lines.join("\n");
}

export function generateSurfaceFreshnessShell(repoRoot: string): void {
  runDocGenerator({
    outputPath: join(repoRoot, GENERATED_SURFACE_FRESHNESS_PATH),
    refreshCommand: "verify:steps",
    render: () => ({
      rendered: renderGeneratedSurfaceFreshnessShell(GENERATED_SURFACE_FRESHNESS),
    }),
  });
}
