# shellcheck shell=bash
# Generated by scripts/harness/generate-verify-steps.ts. Do not edit by hand.
# Freshness records live in harness.controls.json (generatedSurface facets).

musi_warn_generated_surfaces_stale() {
  local staged staged_path
  staged="$(git diff --cached --name-only --diff-filter=ACMR)"
  [ -n "$staged" ] || return 0

  while IFS= read -r staged_path; do
    case "$staged_path" in
      '.claude/settings.json'|'harness.controls.json'|'scripts/ai-hooks/command-normalize.sh'|'scripts/ai-hooks/command-paths.sh'|'scripts/ai-hooks/git-classify.sh'|'scripts/ai-hooks/policy-eval.sh'|'scripts/ai-hooks/policy.sh'|'scripts/harness/command-catalog-schema.ts'|'scripts/harness/command-policy-projection.ts'|'scripts/harness/command-policy-schema.ts'|'scripts/harness/control-field-validation.ts'|'scripts/harness/generate-command-policy.ts'|'scripts/harness/harness-manifest-loader.ts'|'scripts/harness/harness-manifest-schema.ts'|'scripts/harness/harness-manifest.ts'|'scripts/harness/harness-paths.ts'|'scripts/harness/verify-step-artifacts.ts'|'scripts/harness/verify-step-programs.ts'|'scripts/harness/verify-step-schema.ts'|'scripts/lib/codepoint-compare.ts'|'scripts/lib/doc-generator.ts'|'scripts/lib/lint-rule-docs.ts'|'scripts/lib/records.ts'|'scripts/ai-hooks/policy-rules.generated.sh')
        warn_if_generated_surface_stale 'agent command policy rules and native deny projection' 'harness:command-policy:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'docs/CONCURRENCY.md'|'packages/server/prisma/schema.prisma'|'scripts/codemods/concurrency-guard/constants.ts'|'scripts/codemods/concurrency-guard/generate-relation-graph.ts'|'scripts/codemods/concurrency-guard/relation-graph-generator.ts'|'scripts/lib/codepoint-compare.ts'|'scripts/lib/doc-generator.ts'|'packages/server/src/prisma/concurrency-relation-graph.generated.json'|'packages/server/src/prisma/concurrency-relation-graph.generated.ts')
        warn_if_generated_surface_stale 'concurrency relation graph' 'concurrency:relation-graph:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'eslint-config/config-surfaces.js'|'scripts/harness/generate-config-surfaces.ts'|'scripts/lib/doc-generator.ts'|'tsconfig.configs.json')
        warn_if_generated_surface_stale 'config surface tsconfig' 'harness:config-surfaces:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'harness.controls.json'|'scripts/harness/command-catalog-schema.ts'|'scripts/harness/control-field-validation.ts'|'scripts/harness/generate-hook-wiring.ts'|'scripts/harness/harness-manifest-loader.ts'|'scripts/harness/harness-manifest-schema.ts'|'scripts/harness/harness-manifest.ts'|'scripts/harness/harness-paths.ts'|'scripts/harness/hook-shim-files.ts'|'scripts/harness/hook-shims.ts'|'scripts/harness/hook-wiring-schema.ts'|'scripts/harness/verify-step-artifacts.ts'|'scripts/harness/verify-step-programs.ts'|'scripts/harness/verify-step-schema.ts'|'scripts/lib/atomic-write.ts'|'scripts/lib/codepoint-compare.ts'|'scripts/lib/lint-rule-docs.ts'|'scripts/lib/records.ts'|'.claude/settings.json'|'.claude/hooks/'*|'.codex/hooks.json'|'.codex/hooks/'*|'.copilot/hooks/'*|'.github/hooks/copilot.json')
        warn_if_generated_surface_stale 'AI hook wiring' 'harness:wiring:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'harness.controls.json'|'scripts/harness/command-catalog-schema.ts'|'scripts/harness/control-field-validation.ts'|'scripts/harness/generate-hook-timeout-constants.ts'|'scripts/harness/harness-manifest-loader.ts'|'scripts/harness/harness-manifest-schema.ts'|'scripts/harness/harness-manifest.ts'|'scripts/harness/harness-paths.ts'|'scripts/harness/hook-timeout-constants.ts'|'scripts/harness/hook-wiring-schema.ts'|'scripts/harness/verify-step-artifacts.ts'|'scripts/harness/verify-step-programs.ts'|'scripts/harness/verify-step-schema.ts'|'scripts/lib/codepoint-compare.ts'|'scripts/lib/doc-generator.ts'|'scripts/lib/lint-rule-docs.ts'|'scripts/lib/records.ts'|'scripts/ai-hooks/hook-timeouts.generated.sh')
        warn_if_generated_surface_stale 'hook timeout constants' 'harness:hook-timeouts:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'eslint-config/'*|'eslint-rules/'*|'eslint.config.js'|'scripts/harness/generate-lint-rule-controls.ts'|'scripts/harness/harness-manifest.ts'|'scripts/harness/local-rule-config.ts'|'scripts/harness/local-rule-discovery.ts'|'scripts/lib/codepoint-compare.ts'|'scripts/lib/doc-generator.ts'|'scripts/lib/records.ts'|'scripts/lint-ratchet/lint-ratchet-config.ts'|'scripts/lint-ratchet/registry-builders.ts'|'harness.controls.lint-rules.generated.json')
        warn_if_generated_surface_stale 'lint-rule harness controls' 'harness:lint-rule-controls:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'eslint-rules/'*|'scripts/harness/generate-local-plugin.ts'|'scripts/harness/local-rule-discovery.ts'|'scripts/lib/codepoint-compare.ts'|'scripts/lib/doc-generator.ts'|'eslint-config/local-plugin.generated.js')
        warn_if_generated_surface_stale 'local plugin registry' 'lint:local-plugin:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'drift-ai.config.json'|'scripts/drift-ai/scope.ts'|'scripts/drift-ai/types.ts'|'scripts/harness/generate-pre-push-scope-trigger.ts'|'scripts/harness/harness-paths.ts'|'scripts/harness/pre-push-scope-trigger.ts'|'scripts/lib/doc-generator.ts'|'scripts/lib/path-taxonomy.ts'|'scripts/lib/records.ts'|'scripts/harness/pre-push-scope-trigger.generated.sh')
        warn_if_generated_surface_stale 'pre-push near-duplicates scope trigger' 'harness:pre-push-trigger:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'eslint-config/config-surfaces.js'|'eslint-config/max-lines-exceptions-codec.js'|'eslint-config/path-glob-policy.js'|'eslint-config/script-test-policy.js'|'scripts/harness/generate-restricted-disable-rules.ts'|'scripts/lib/codepoint-compare.ts'|'scripts/lib/doc-generator.ts'|'scripts/lint-ratchet/lint-ratchet-config.ts'|'scripts/lint-ratchet/registry-builders.ts'|'eslint-config/ratchet-restricted-disable-rules.generated.js')
        warn_if_generated_surface_stale 'restricted-disable rule metadata' 'lint:restricted-disable-rules:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      '.claude/skills/'*|'.gitignore'|'harness.controls.json'|'scripts/harness/check-skill-inventory.ts'|'scripts/harness/generate-skill-artifacts.ts'|'scripts/harness/harness-manifest.ts'|'scripts/harness/skill-artifact-projection.ts'|'scripts/harness/skill-inventory-schema.ts'|'scripts/harness/skill-overlay-content.ts'|'scripts/harness/skill-projection-files.ts'|'scripts/harness/skill-smoke-subject-block.ts'|'scripts/lib/atomic-write.ts'|'scripts/lib/codepoint-compare.ts'|'scripts/lib/doc-generator.ts'|'scripts/lib/records.ts'|'scripts/path-policy/fixture-copy-expressions.ts'|'scripts/path-policy/fixture-helper-calls.ts'|'scripts/path-policy/fixture-import-closure.ts'|'scripts/path-policy/fixture-loop-bindings.ts'|'scripts/path-policy/fixture-sandbox-model.ts'|'scripts/path-policy/fixture-seed-statements.ts'|'scripts/path-policy/fixture-seeding-annotations.ts'|'scripts/path-policy/fixture-shell-dependencies.ts'|'scripts/path-policy/fixture-shell-scope.ts'|'scripts/path-policy/segment-pattern.ts'|'scripts/path-policy/smoke-test-files.ts'|'scripts/path-policy/smoke-subject-headers.ts'|'scripts/import-closure/closure-walk.ts'|'scripts/import-closure/runtime-imports.ts'|'scripts/import-closure/runtime-resolution.ts'|'.codex/skills/'*|'scripts/tests/test-skill-dispatch-wrappers.sh'|'scripts/path-policy/path-policy-smoke-subjects-data.ts'|'scripts/fixtures/test-scripts/all-smoke-tests.txt')
        warn_if_generated_surface_stale 'skill mirrors and smoke routing' 'harness:skills:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'scripts/lib/doc-generator.ts'|'scripts/path-policy/fixture-copy-expressions.ts'|'scripts/path-policy/fixture-helper-calls.ts'|'scripts/path-policy/fixture-import-closure.ts'|'scripts/path-policy/fixture-loop-bindings.ts'|'scripts/path-policy/fixture-sandbox-model.ts'|'scripts/path-policy/fixture-seed-statements.ts'|'scripts/path-policy/fixture-seeding-annotations.ts'|'scripts/path-policy/fixture-shell-dependencies.ts'|'scripts/path-policy/fixture-shell-scope.ts'|'scripts/path-policy/generate-smoke-subjects.ts'|'scripts/path-policy/segment-pattern.ts'|'scripts/path-policy/smoke-test-files.ts'|'scripts/path-policy/smoke-subject-headers.ts'|'scripts/tests/'*|'scripts/import-closure/closure-walk.ts'|'scripts/import-closure/runtime-imports.ts'|'scripts/import-closure/runtime-resolution.ts'|'scripts/path-policy/path-policy-smoke-subjects-data.ts'|'scripts/fixtures/test-scripts/all-smoke-tests.txt')
        warn_if_generated_surface_stale 'script smoke-subject metadata' 'test:scripts:subjects:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'harness.controls.json'|'scripts/harness-registration-check.ts'|'scripts/harness/command-catalog-schema.ts'|'scripts/harness/control-field-validation.ts'|'scripts/harness/generate-verify-steps.ts'|'scripts/harness/generated-surface-dependencies.ts'|'scripts/harness/generated-surfaces-loader.ts'|'scripts/harness/generated-surfaces.ts'|'scripts/harness/harness-check-validation.ts'|'scripts/harness/harness-manifest-loader.ts'|'scripts/harness/harness-manifest-schema.ts'|'scripts/harness/harness-manifest.ts'|'scripts/harness/harness-paths.ts'|'scripts/harness/registration-explain-cli.ts'|'scripts/harness/registration-explain-describe.ts'|'scripts/harness/registration-explain-matchers.ts'|'scripts/harness/registration-explain-model.ts'|'scripts/harness/registration-explain-render.ts'|'scripts/harness/registration-explain.ts'|'scripts/harness/verify-step-artifacts.ts'|'scripts/harness/verify-step-programs.ts'|'scripts/harness/verify-step-schema.ts'|'scripts/import-closure/closure-walk.ts'|'scripts/import-closure/runtime-imports.ts'|'scripts/import-closure/runtime-resolution.ts'|'scripts/lib/codepoint-compare.ts'|'scripts/lib/doc-generator.ts'|'scripts/lib/lint-rule-docs.ts'|'scripts/lib/records.ts'|'scripts/lint-ratchet/ratchet-manifest-message.ts'|'scripts/path-policy/path-policy-smoke-subjects-data.ts'|'scripts/path-policy/path-policy-smoke-subjects.ts'|'scripts/verify/steps.generated.sh'|'scripts/harness/generated-surface-freshness.generated.sh'|'scripts/ai-hooks/classified-bun-scripts.generated.sh'|'scripts/tests/harness-check-fixture-manifest.generated.txt')
        warn_if_generated_surface_stale 'verify step and generated-surface metadata' 'verify:steps:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'docs/agent_notes/backlog/'*|'scripts/backlog-catalog-render.ts'|'scripts/backlog-lint.ts'|'scripts/backlog-lint-classify.ts'|'scripts/backlog-lint-core.ts'|'scripts/backlog-lint-drift.ts'|'scripts/backlog-lint-format.ts'|'scripts/backlog-lint-grammar.ts'|'scripts/backlog-lint-index-table.ts'|'scripts/backlog-lint-metadata.ts'|'scripts/backlog-lint-packs.ts'|'scripts/backlog-lint-status.ts'|'scripts/backlog-lint-types.ts'|'scripts/cli-option-values.ts'|'scripts/generate-backlog-catalog.ts'|'scripts/lib/cli.ts'|'scripts/lib/doc-generator.ts'|'scripts/lib/git.ts')
        warn_if_generated_surface_stale 'backlog catalog' 'docs:backlog-catalog:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'scripts/generate-baseline-conflict-recipes.ts'|'scripts/git/baseline-merge-driver.sh'|'scripts/lib/doc-generator.ts'|'scripts/lint-ratchet/workflow-vocabulary.ts'|'tools/lint-ratchet/src/git-rail/conflict-recovery.ts'|'docs/guides/lint-ratchet-merges.md')
        warn_if_generated_surface_stale 'baseline conflict recovery recipes' 'docs:baseline-conflict-recipes:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'examples/lint-ratchet-demo/package.json'|'harness.controls.json'|'harness.controls.lint-rules.generated.json'|'package.json'|'packages/client/package.json'|'packages/server/package.json'|'packages/shared/package.json'|'scripts/harness/command-catalog-schema.ts'|'scripts/harness/command-catalog-sections.ts'|'scripts/harness/command-catalog-sources.ts'|'scripts/harness/command-catalog.ts'|'scripts/harness/control-field-validation.ts'|'scripts/harness/generate-command-catalog.ts'|'scripts/harness/generated-surfaces.ts'|'scripts/harness/harness-check-validation.ts'|'scripts/harness/harness-manifest-loader.ts'|'scripts/harness/harness-manifest-schema.ts'|'scripts/harness/harness-manifest.ts'|'scripts/harness/harness-paths.ts'|'scripts/harness/package-manifest-scripts.ts'|'scripts/harness/verify-step-artifacts.ts'|'scripts/harness/verify-step-programs.ts'|'scripts/harness/verify-step-schema.ts'|'scripts/lib/codepoint-compare.ts'|'scripts/lib/doc-generator.ts'|'scripts/lib/git.ts'|'scripts/lib/lint-rule-docs.ts'|'scripts/lib/records.ts'|'scripts/lint-ratchet/ratchet-manifest-message.ts'|'tools/harness-diagnostics/package.json'|'tools/lint-ratchet/package.json'|'docs/generated/command-catalog.md')
        warn_if_generated_surface_stale 'command catalog' 'docs:command-catalog:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'eslint-config/config-surfaces.js'|'eslint-config/path-glob-policy.js'|'eslint-config/script-test-policy.js'|'harness.controls.json'|'harness.controls.lint-rules.generated.json'|'scripts/harness/command-catalog-schema.ts'|'scripts/harness/command-policy-schema.ts'|'scripts/harness/control-field-validation.ts'|'scripts/harness/generate-harness-controls-validation.ts'|'scripts/harness/generate-harness-controls.ts'|'scripts/harness/harness-manifest-schema.ts'|'scripts/harness/harness-manifest.ts'|'scripts/harness/harness-paths.ts'|'scripts/harness/hook-wiring-doc.ts'|'scripts/harness/hook-wiring-schema.ts'|'scripts/harness/verify-step-artifacts.ts'|'scripts/harness/verify-step-programs.ts'|'scripts/harness/verify-step-schema.ts'|'scripts/lib/codepoint-compare.ts'|'scripts/lib/doc-generator.ts'|'scripts/lib/lint-rule-docs.ts'|'scripts/lib/records.ts'|'scripts/lint-ratchet/lint-ratchet-config.ts'|'scripts/lint-ratchet/registry-builders.ts'|'docs/generated/harness-controls.md')
        warn_if_generated_surface_stale 'harness controls docs' 'docs:harness-controls:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'scripts/cli-option-values.ts'|'scripts/harness-audit.ts'|'scripts/harness/'*|'scripts/import-closure/'*|'scripts/lib/'*|'scripts/lint-ratchet/'*|'docs/generated/harness-porting-manifest.md')
        warn_if_generated_surface_stale 'harness porting copy manifest' 'docs:harness-porting:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'eslint-config/'*|'eslint-rules/'*|'eslint.config.js'|'scripts/drift-ai/'*|'scripts/lib/codepoint-compare.ts'|'scripts/lib/doc-generator.ts'|'scripts/lib/git.ts'|'scripts/lint-coverage-map-check-eslint-reach.ts'|'scripts/lint-coverage-map-check-io.ts'|'scripts/lint-coverage-map-gen-core.ts'|'scripts/lint-coverage-map-gen.ts'|'scripts/lint-coverage-map-manifest-codemods.ts'|'scripts/lint-coverage-map-manifest-config-files.ts'|'scripts/lint-coverage-map-manifest-config-sensors.ts'|'scripts/lint-coverage-map-manifest-docs.ts'|'scripts/lint-coverage-map-manifest-drift-ai.ts'|'scripts/lint-coverage-map-manifest-harness-scripts.ts'|'scripts/lint-coverage-map-manifest-lint-rules-and-shell.ts'|'scripts/lint-coverage-map-manifest-linted-scripts-a.ts'|'scripts/lint-coverage-map-manifest-linted-scripts-b.ts'|'scripts/lint-coverage-map-manifest-misc.ts'|'scripts/lint-coverage-map-manifest-packages.ts'|'scripts/lint-coverage-map-manifest-portable-tooling.ts'|'scripts/lint-coverage-map-manifest-prose.ts'|'scripts/lint-coverage-map-manifest-ratchet-runtime.ts'|'scripts/lint-coverage-map-manifest-schema.ts'|'scripts/lint-coverage-map-manifest-script-entrypoints.ts'|'scripts/lint-coverage-map-manifest-script-fixtures.ts'|'scripts/lint-coverage-map-manifest-sections.ts'|'scripts/lint-coverage-map-manifest.ts'|'scripts/lint-ratchet/lint-ratchet-config.ts'|'scripts/lint-ratchet/registry-builders.ts'|'tools/lint-ratchet/package.json'|'tools/lint-ratchet/src/kernel/codepoint-compare.ts'|'tools/lint-ratchet/src/kernel/ratchet-globs.ts'|'tsconfig.scripts.json'|'docs/generated/lint-coverage-map.md')
        warn_if_generated_surface_stale 'lint coverage-map document' 'docs:lint-coverage-map:generate:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'eslint-config/local-plugin.generated.js'|'eslint-rules/'*|'scripts/generate-lint-guidance.ts'|'scripts/lib/doc-generator.ts'|'scripts/lib/lint-rule-docs.ts'|'scripts/lib/records.ts'|'docs/generated/local-lint-rules.md')
        warn_if_generated_surface_stale 'lint guidance' 'docs:lint-guidance:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'scripts/harness/command-catalog-schema.ts'|'scripts/harness/control-field-validation.ts'|'scripts/harness/generate-manifest-json-schema.ts'|'scripts/harness/harness-manifest-schema.ts'|'scripts/harness/harness-manifest.ts'|'scripts/harness/verify-step-artifacts.ts'|'scripts/harness/verify-step-programs.ts'|'scripts/harness/verify-step-schema.ts'|'scripts/lib/codepoint-compare.ts'|'scripts/lib/doc-generator.ts'|'scripts/lib/lint-rule-docs.ts'|'scripts/lib/records.ts'|'schemas/harness.controls.schema.json')
        warn_if_generated_surface_stale 'published manifest JSON Schema' 'harness:manifest-schema:check'
        break
        ;;
    esac
  done <<< "$staged"
}
