import { describe, expect, it } from "vitest";

import { type HarnessManifest, parseHarnessManifest } from "./harness-manifest-schema.js";
import { renderHookTimeoutConstantsShellFromManifest } from "./hook-timeout-constants.js";

// `shim` is the shared body's basename: the surface declaration makes the
// binding's matcher and command canonical projections of it, so the fixture
// stays a well-formed control rather than leaning on the tripwire's note
// opt-out for an asymmetry it does not actually have.
function quietHookControl(
  id: string,
  shim: string,
  timeout: number | undefined,
): Record<string, unknown> {
  const body = `scripts/ai-hooks/${shim}`;
  return {
    id,
    kind: "hook",
    category: "maintainability",
    principle: "Fixture quiet hook used by the timeout-constant generator tests.",
    pairedGuide: "none",
    repairKind: "manual",
    source: body,
    invocation: "bun run harness:wiring",
    hookWiring: {
      event: "PreToolUse",
      body,
      order: id.includes("bun-run") ? 10 : 20,
      surface: "bash",
      harnesses: {
        claude: {
          matcher: "Bash",
          command: `bash $CLAUDE_PROJECT_DIR/.claude/hooks/${shim}`,
          ...(timeout === undefined ? {} : { timeout }),
        },
      },
      notes: {
        codex: "Fixture only.",
        copilot: "Fixture only.",
      },
    },
  };
}

// Built through the typed contract so the fixture cannot drift out of the
// shape the generator is now typed against.
function manifestOf(controls: readonly Record<string, unknown>[]): HarnessManifest {
  return parseHarnessManifest({
    scriptParityExemptions: [],
    ciGateControlIds: [],
    controls,
  });
}

function manifestWithTimeouts(
  bunTimeout: number | undefined,
  gitTimeout: number | undefined,
): HarnessManifest {
  return manifestOf([
    quietHookControl("hook/ai-bun-run-quiet", "bun-run-quiet.sh", bunTimeout),
    quietHookControl("hook/ai-git-commit-quiet", "git-commit-quiet.sh", gitTimeout),
  ]);
}

describe("hook timeout constants generator", () => {
  it("renders shell constants from manifest hook wiring timeouts", () => {
    expect(renderHookTimeoutConstantsShellFromManifest(manifestWithTimeouts(1260, 1260)))
      .toBe(`# shellcheck shell=bash
# shellcheck disable=SC2034
# Generated by scripts/harness/generate-hook-timeout-constants.ts. Do not edit by hand.

BUN_RUN_QUIET_HOOK_TIMEOUT=1260
GIT_COMMIT_QUIET_HOOK_TIMEOUT=1260
`);
  });

  it("rejects divergent quiet-hook timeout ceilings", () => {
    expect(() =>
      renderHookTimeoutConstantsShellFromManifest(manifestWithTimeouts(1260, 900)),
    ).toThrow(
      "quiet-hook timeout ceilings must match: BUN_RUN_QUIET_HOOK_TIMEOUT=1260, GIT_COMMIT_QUIET_HOOK_TIMEOUT=900",
    );
  });

  it("requires timeout-bearing hook wiring for bound quiet hooks", () => {
    expect(() =>
      renderHookTimeoutConstantsShellFromManifest(manifestWithTimeouts(1260, undefined)),
    ).toThrow("hookWiring.harnesses.claude.timeout is required for GIT_COMMIT_QUIET_HOOK_TIMEOUT");
  });

  it("reports a bound quiet hook that the manifest does not declare at all", () => {
    expect(() =>
      renderHookTimeoutConstantsShellFromManifest(
        manifestOf([quietHookControl("hook/ai-bun-run-quiet", "bun-run-quiet.sh", 1260)]),
      ),
    ).toThrow(
      "required hook timeout control hook/ai-git-commit-quiet is missing from harness.controls.json",
    );
  });
});
