import { describe, expect, it } from "vitest";

import {
  renderHookWiringOutputsFromManifest,
  replaceClaudeHooksInSettings,
} from "./generate-hook-wiring.js";

const BASE_SETTINGS = `{
  "env": {
    "KEEP": "yes"
  },
  "permissions": {
    "deny": []
  },
  "hooks": {
    "PreToolUse": []
  },
  "enabledPlugins": {
    "typescript-lsp@claude-plugins-official": true
  }
}
`;

describe("hook wiring generator", () => {
  it("renders Claude and Codex hook wiring from manifest order metadata", () => {
    const manifest = {
      controls: [
        {
          id: "hook/codex-aggregator",
          kind: "hook",
          hookWiring: {
            event: "PostToolUse",
            order: 90,
            harnesses: {
              codex: {
                matcher: "Bash",
                command: 'bash "$(git rev-parse --show-toplevel)/.codex/hooks/post-tool-use.sh"',
                statusMessage: "Summarizing repository Bash output",
                timeout: 60,
              },
            },
            notes: { claude: "Claude has no Codex Bash aggregation hook." },
          },
        },
        {
          id: "hook/prisma",
          kind: "hook",
          hookWiring: {
            event: "PostToolUse",
            order: 10,
            harnesses: {
              claude: {
                matcher: "Edit|Write",
                command: "bash $CLAUDE_PROJECT_DIR/.claude/hooks/prisma-generate.sh",
                timeout: 120,
              },
              codex: {
                matcher: "apply_patch",
                command: 'bash "$(git rev-parse --show-toplevel)/.codex/hooks/prisma-generate.sh"',
                statusMessage: "Regenerating Prisma client",
                timeout: 120,
              },
            },
          },
        },
        {
          id: "hook/doc-length",
          kind: "hook",
          hookWiring: {
            event: "PostToolUse",
            order: 20,
            harnesses: {
              claude: {
                matcher: "Edit|Write",
                command: "bash $CLAUDE_PROJECT_DIR/.claude/hooks/doc-length.sh",
              },
              codex: {
                matcher: "apply_patch",
                command: 'bash "$(git rev-parse --show-toplevel)/.codex/hooks/doc-length.sh"',
                statusMessage: "Checking edited doc length",
                timeout: 15,
              },
            },
          },
        },
        {
          id: "hook/stop",
          kind: "hook",
          hookWiring: {
            event: "Stop",
            order: 10,
            harnesses: {
              claude: {
                command: "bash $CLAUDE_PROJECT_DIR/.claude/hooks/stop-reminder.sh",
                timeout: 30,
              },
              codex: {
                command: 'bash "$(git rev-parse --show-toplevel)/.codex/hooks/stop-reminder.sh"',
                statusMessage: "Checking repository stop conditions",
                timeout: 30,
              },
            },
          },
        },
      ],
    };

    const outputs = renderHookWiringOutputsFromManifest(manifest, BASE_SETTINGS);
    const claudeSettings: unknown = JSON.parse(outputs.claudeSettingsJson);
    const codexHooks: unknown = JSON.parse(outputs.codexHooksJson);

    expect(claudeSettings).toMatchObject({
      env: { KEEP: "yes" },
      permissions: { deny: [] },
      enabledPlugins: { "typescript-lsp@claude-plugins-official": true },
      hooks: {
        PostToolUse: [
          {
            matcher: "Edit|Write",
            hooks: [
              {
                type: "command",
                command: "bash $CLAUDE_PROJECT_DIR/.claude/hooks/prisma-generate.sh",
                timeout: 120,
              },
              {
                type: "command",
                command: "bash $CLAUDE_PROJECT_DIR/.claude/hooks/doc-length.sh",
              },
            ],
          },
        ],
        Stop: [
          {
            hooks: [
              {
                type: "command",
                command: "bash $CLAUDE_PROJECT_DIR/.claude/hooks/stop-reminder.sh",
                timeout: 30,
              },
            ],
          },
        ],
      },
    });
    expect(codexHooks).toEqual({
      _generated:
        "Generated by scripts/harness/generate-hook-wiring.ts from harness.controls.json. Do not edit by hand.",
      hooks: {
        PostToolUse: [
          {
            matcher: "apply_patch",
            hooks: [
              {
                type: "command",
                command: 'bash "$(git rev-parse --show-toplevel)/.codex/hooks/prisma-generate.sh"',
                statusMessage: "Regenerating Prisma client",
                timeout: 120,
              },
              {
                type: "command",
                command: 'bash "$(git rev-parse --show-toplevel)/.codex/hooks/doc-length.sh"',
                statusMessage: "Checking edited doc length",
                timeout: 15,
              },
            ],
          },
          {
            matcher: "Bash",
            hooks: [
              {
                type: "command",
                command: 'bash "$(git rev-parse --show-toplevel)/.codex/hooks/post-tool-use.sh"',
                statusMessage: "Summarizing repository Bash output",
                timeout: 60,
              },
            ],
          },
        ],
        Stop: [
          {
            hooks: [
              {
                type: "command",
                command: 'bash "$(git rev-parse --show-toplevel)/.codex/hooks/stop-reminder.sh"',
                statusMessage: "Checking repository stop conditions",
                timeout: 30,
              },
            ],
          },
        ],
      },
    });
  });

  it("replaces only the Claude hooks key", () => {
    const replaced = replaceClaudeHooksInSettings(BASE_SETTINGS, { Stop: [{ hooks: [] }] });

    expect(replaced).toContain('"env": {\n    "KEEP": "yes"\n  }');
    expect(replaced).toContain('"enabledPlugins": {');
    // type-assertion-boundary: json - JSON.parse of the settings text the
    // function under test just emitted; only the hooks key is asserted on.
    const parsed = JSON.parse(replaced) as { hooks: unknown };
    expect(parsed.hooks).toEqual({ Stop: [{ hooks: [] }] });
  });

  it("does not mistake a string value for the Claude hooks key", () => {
    const settings = `{
  "description": "hooks",
  "hooks": {
    "PreToolUse": []
  }
}
`;

    const replaced = replaceClaudeHooksInSettings(settings, { Stop: [{ hooks: [] }] });
    const parsed = JSON.parse(replaced) as { description: string; hooks: unknown };

    expect(parsed.description).toBe("hooks");
    expect(parsed.hooks).toEqual({ Stop: [{ hooks: [] }] });
  });

  it("replaces hooks with compact JSON and whitespace before the colon", () => {
    const settings = `{"env":{"KEEP":"yes"},"hooks" : [],"after":{"hooks":"keep"}}`;

    const replaced = replaceClaudeHooksInSettings(settings, { Stop: [{ hooks: [] }] });

    expect(replaced.endsWith("\n")).toBe(false);
    expect(JSON.parse(replaced)).toEqual({
      env: { KEEP: "yes" },
      hooks: { Stop: [{ hooks: [] }] },
      after: { hooks: "keep" },
    });
  });

  it("ignores nested hooks keys before the top-level Claude hooks key", () => {
    const settings = `{
  "adapter": {
    "hooks": {
      "PreToolUse": [
        {
          "keep": true
        }
      ]
    }
  },
  "hooks": {
    "PreToolUse": []
  }
}
`;

    const replaced = replaceClaudeHooksInSettings(settings, { Stop: [{ hooks: [] }] });

    expect(JSON.parse(replaced)).toEqual({
      adapter: {
        hooks: {
          PreToolUse: [{ keep: true }],
        },
      },
      hooks: { Stop: [{ hooks: [] }] },
    });
  });

  it("uses JSON string parsing when matching escaped top-level hooks keys", () => {
    const settings = `{
  "h\\u006foks": [],
  "near\\u002dhooks": true
}
`;

    const replaced = replaceClaudeHooksInSettings(settings, { Stop: [{ hooks: [] }] });

    expect(JSON.parse(replaced)).toEqual({
      hooks: { Stop: [{ hooks: [] }] },
      "near-hooks": true,
    });
  });

  it("throws a clear error when the top-level Claude hooks key is missing", () => {
    const settings = `{
  "env": {
    "KEEP": "yes"
  }
}
`;

    expect(() => replaceClaudeHooksInSettings(settings, { Stop: [{ hooks: [] }] })).toThrow(
      ".claude/settings.json must declare a top-level hooks key",
    );
  });

  it("rejects duplicate manifest control ids instead of emitting duplicated hooks", () => {
    const stopWiring = {
      event: "Stop",
      order: 10,
      harnesses: {
        claude: {
          command: "bash $CLAUDE_PROJECT_DIR/.claude/hooks/stop-reminder.sh",
        },
        codex: {
          command: 'bash "$(git rev-parse --show-toplevel)/.codex/hooks/stop-reminder.sh"',
          statusMessage: "Checking repository stop conditions",
        },
      },
    };
    const manifest = {
      controls: [
        { id: "hook/stop", kind: "hook", hookWiring: stopWiring },
        { id: "hook/stop", kind: "hook", hookWiring: stopWiring },
      ],
    };

    expect(() => renderHookWiringOutputsFromManifest(manifest, BASE_SETTINGS)).toThrow(
      "duplicate control id: hook/stop",
    );
  });

  it("requires a deliberate note for omitted harness targets", () => {
    const manifest = {
      controls: [
        {
          id: "hook/claude-only",
          kind: "hook",
          hookWiring: {
            event: "PreToolUse",
            order: 10,
            harnesses: {
              claude: {
                matcher: "Bash",
                command: "bash $CLAUDE_PROJECT_DIR/.claude/hooks/no-direct-db.sh",
              },
            },
          },
        },
      ],
    };

    expect(() => renderHookWiringOutputsFromManifest(manifest, BASE_SETTINGS)).toThrow(
      "hook/claude-only omits codex wiring without a notes.codex explanation",
    );
  });
});
