# shellcheck shell=bash
# Generated by scripts/harness/generate-verify-steps.ts. Do not edit by hand.
# Freshness records live in scripts/harness/generated-surface-freshness.ts.

musi_warn_generated_surfaces_stale() {
  local staged staged_path
  staged="$(git diff --cached --name-only --diff-filter=ACMR)"
  [ -n "$staged" ] || return 0

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'scripts/path-policy/generate-smoke-subjects.ts'|'scripts/path-policy/smoke-subject-headers.ts'|'scripts/path-policy/fixture-shell-dependencies.ts'|'scripts/path-policy/fixture-shell-scope.ts'|'scripts/tests/'*|'scripts/path-policy/path-policy-smoke-subjects-data.ts'|'scripts/fixtures/test-scripts/all-smoke-tests.txt')
        warn_if_generated_surface_stale 'script smoke-subject metadata' 'test:scripts:subjects:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'harness.controls.json'|'scripts/harness/generate-verify-steps.ts'|'scripts/harness/generated-surface-freshness.ts'|'scripts/harness/verify-step-schema.ts'|'scripts/harness/verify-step-bridge-divergences.ts'|'scripts/verify/steps.generated.sh'|'scripts/harness/generated-surface-freshness.generated.sh')
        warn_if_generated_surface_stale 'verify step and generated-surface metadata' 'verify:steps:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'harness.controls.json'|'scripts/harness/generate-hook-timeout-constants.ts'|'scripts/harness/hook-timeout-constants.ts'|'scripts/ai-hooks/hook-timeouts.generated.sh')
        warn_if_generated_surface_stale 'hook timeout constants' 'harness:hook-timeouts:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'eslint-config/shared-policy.js'|'scripts/harness/generate-config-surfaces.ts'|'tsconfig.configs.json')
        warn_if_generated_surface_stale 'config surface tsconfig' 'harness:config-surfaces:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'harness.controls.json'|'scripts/harness/generate-hook-wiring.ts'|'scripts/harness/hook-wiring-schema.ts'|'.claude/settings.json'|'.codex/hooks.json'|'.github/hooks/copilot.json')
        warn_if_generated_surface_stale 'AI hook wiring' 'harness:wiring:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'eslint-rules/'*|'eslint-config/local-plugin.js'|'scripts/generate-lint-guidance.ts'|'scripts/lib/lint-rule-docs.ts'|'docs/generated/local-lint-rules.md')
        warn_if_generated_surface_stale 'lint guidance' 'docs:lint-guidance:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'scripts/git/baseline-merge-driver.sh'|'scripts/generate-baseline-conflict-recipes.ts'|'docs/guides/lint-ratchet-merges.md')
        warn_if_generated_surface_stale 'baseline conflict recovery recipes' 'docs:baseline-conflict-recipes:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'harness.controls.json'|'scripts/harness/generate-harness-controls.ts'|'scripts/harness/generate-harness-controls-validation.ts'|'scripts/harness/control-field-validation.ts'|'docs/generated/harness-controls.md')
        warn_if_generated_surface_stale 'harness controls docs' 'docs:harness-controls:check'
        break
        ;;
    esac
  done <<< "$staged"

  while IFS= read -r staged_path; do
    case "$staged_path" in
      'scripts/harness/generate-restricted-disable-rules.ts'|'scripts/lint-ratchet/lint-ratchet-config.ts'|'eslint-config/ratchet-restricted-disable-rules.generated.js')
        warn_if_generated_surface_stale 'restricted-disable rule metadata' 'lint:restricted-disable-rules:check'
        break
        ;;
    esac
  done <<< "$staged"
}
