import { describe, expect, it } from "vitest";

import { deriveHookShims, HOOK_SHIM_DIRS, type ShimWiringInput } from "./hook-shims.js";

function claudeWiring(overrides: Partial<ShimWiringInput> = {}): ShimWiringInput {
  return {
    controlId: "hook/fixture-claude",
    event: "PostToolUse",
    body: "scripts/ai-hooks/fixture-body.sh",
    harnesses: {
      claude: {
        matcher: "Edit|Write",
        command: "bash $CLAUDE_PROJECT_DIR/.claude/hooks/fixture-body.sh",
      },
    },
    ...overrides,
  };
}

describe("hook shim derivation", () => {
  it("renders the exact Claude exec shim with the CLAUDE_PROJECT_DIR fallback", () => {
    const shims = deriveHookShims([claudeWiring()]);

    expect(shims).toHaveLength(1);
    expect(shims[0]?.harness).toBe("claude");
    expect(shims[0]?.relPath).toBe(".claude/hooks/fixture-body.sh");
    expect(shims[0]?.content).toBe(
      [
        "#!/bin/bash",
        "# Generated by scripts/harness/generate-hook-wiring.ts from harness.controls.json",
        "# hookWiring entries. Do not edit by hand; regenerate with `bun run harness:wiring`.",
        "# Thin adapter - semantics documented in scripts/ai-hooks/fixture-body.sh.",
        "",
        "set -u",
        "",
        'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
        'REPO_ROOT=$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null || git rev-parse --show-toplevel 2>/dev/null || echo "${CLAUDE_PROJECT_DIR:-/workspace}")',
        'exec bash "$REPO_ROOT/scripts/ai-hooks/fixture-body.sh"',
        "",
      ].join("\n"),
    );
  });

  it("renders the exact Codex exec shim with the /workspace fallback", () => {
    const shims = deriveHookShims([
      {
        controlId: "hook/fixture-codex",
        event: "PostToolUse",
        body: "scripts/ai-hooks/fixture-body.sh",
        harnesses: {
          codex: {
            matcher: "apply_patch",
            command: 'bash "$(git rev-parse --show-toplevel)/.codex/hooks/fixture-body.sh"',
            statusMessage: "Fixture",
          },
        },
      },
    ]);

    expect(shims).toHaveLength(1);
    expect(shims[0]?.harness).toBe("codex");
    expect(shims[0]?.relPath).toBe(".codex/hooks/fixture-body.sh");
    expect(shims[0]?.content).toBe(
      [
        "#!/bin/bash",
        "# Generated by scripts/harness/generate-hook-wiring.ts from harness.controls.json",
        "# hookWiring entries. Do not edit by hand; regenerate with `bun run harness:wiring`.",
        "# Thin adapter - semantics documented in scripts/ai-hooks/fixture-body.sh.",
        "",
        "set -u",
        "",
        'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
        'REPO_ROOT=$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null || git rev-parse --show-toplevel 2>/dev/null || echo /workspace)',
        'exec bash "$REPO_ROOT/scripts/ai-hooks/fixture-body.sh"',
        "",
      ].join("\n"),
    );
  });

  it("renders the exact Copilot dispatch shim and derives the post-edit mode", () => {
    const shims = deriveHookShims([
      {
        controlId: "hook/fixture-copilot",
        event: "PostToolUse",
        body: "scripts/ai-hooks/fixture-body.sh",
        harnesses: {
          copilot: {
            matcher: "create|edit",
            command: 'bash "$(git rev-parse --show-toplevel)/.copilot/hooks/fixture-body.sh"',
          },
        },
      },
    ]);

    expect(shims).toHaveLength(1);
    expect(shims[0]?.harness).toBe("copilot");
    expect(shims[0]?.relPath).toBe(".copilot/hooks/fixture-body.sh");
    expect(shims[0]?.content).toBe(
      [
        "#!/bin/bash",
        "# Generated by scripts/harness/generate-hook-wiring.ts from harness.controls.json",
        "# hookWiring entries. Do not edit by hand; regenerate with `bun run harness:wiring`.",
        "# Thin adapter - semantics documented in scripts/ai-hooks/fixture-body.sh; Copilot",
        "# payload/response translation in scripts/ai-hooks/copilot-adapter.sh.",
        "",
        "set -u",
        "",
        'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
        'REPO_ROOT=$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null || git rev-parse --show-toplevel 2>/dev/null || echo /workspace)',
        'HOOK_LIB="$REPO_ROOT/scripts/ai-hooks"',
        "# shellcheck source=/dev/null",
        '. "$HOOK_LIB/common.sh"',
        "# shellcheck source=/dev/null",
        '. "$HOOK_LIB/copilot-adapter.sh"',
        "",
        'ai_copilot_dispatch post-edit edit "$HOOK_LIB/fixture-body.sh"',
        "",
      ].join("\n"),
    );
  });

  it.each([
    ["PreToolUse", "bash|powershell", "pre bash"],
    ["PreToolUse", "create|edit", "pre edit"],
    ["PostToolUse", "bash|powershell", "post-bash bash"],
    ["PostToolUse", "create|edit", "post-edit edit"],
  ] as const)("derives copilot dispatch args for %s with matcher %s", (event, matcher, args) => {
    const shims = deriveHookShims([
      {
        controlId: "hook/fixture-copilot",
        event,
        body: "scripts/ai-hooks/fixture-body.sh",
        harnesses: {
          copilot: {
            matcher,
            command: 'bash "$(git rev-parse --show-toplevel)/.copilot/hooks/fixture-body.sh"',
          },
        },
      },
    ]);

    expect(shims[0]?.content).toContain(`ai_copilot_dispatch ${args} "$HOOK_LIB/fixture-body.sh"`);
  });

  it("fails closed on copilot Stop because ai_copilot_dispatch has no stop mode", () => {
    expect(() =>
      deriveHookShims([
        {
          controlId: "hook/fixture-copilot-stop",
          event: "Stop",
          body: "scripts/ai-hooks/fixture-body.sh",
          harnesses: {
            copilot: {
              command: 'bash "$(git rev-parse --show-toplevel)/.copilot/hooks/fixture-body.sh"',
            },
          },
        },
      ]),
    ).toThrow(/copilot Stop shims cannot be generated.*no stop mode/u);
  });

  it("fails closed on an unknown copilot matcher", () => {
    expect(() =>
      deriveHookShims([
        {
          controlId: "hook/fixture-copilot",
          event: "PreToolUse",
          body: "scripts/ai-hooks/fixture-body.sh",
          harnesses: {
            copilot: {
              matcher: "shell",
              command: 'bash "$(git rev-parse --show-toplevel)/.copilot/hooks/fixture-body.sh"',
            },
          },
        },
      ]),
    ).toThrow('matcher must be "bash|powershell" or "create|edit"');
  });

  it("accepts both recognized command shapes and confines each harness to its own directory", () => {
    const shims = deriveHookShims([
      {
        controlId: "hook/fixture-both",
        event: "PostToolUse",
        body: "scripts/ai-hooks/fixture-body.sh",
        harnesses: {
          claude: {
            matcher: "Edit|Write",
            command: 'bash "$(git rev-parse --show-toplevel)/.claude/hooks/fixture-body.sh"',
          },
          codex: {
            matcher: "apply_patch",
            command: "bash $CLAUDE_PROJECT_DIR/.codex/hooks/fixture-body.sh",
            statusMessage: "Fixture",
          },
        },
      },
    ]);

    expect(shims.map((shim) => shim.relPath)).toEqual([
      ".claude/hooks/fixture-body.sh",
      ".codex/hooks/fixture-body.sh",
    ]);
  });

  it("rejects an unrecognized command shape instead of guessing a write target", () => {
    expect(() =>
      deriveHookShims([
        claudeWiring({
          harnesses: {
            claude: { matcher: "Edit|Write", command: "bash .claude/hooks/fixture-body.sh" },
          },
        }),
      ]),
    ).toThrow("does not match a recognized shim command shape");
  });

  it("rejects a command that targets another harness's adapter directory", () => {
    expect(() =>
      deriveHookShims([
        claudeWiring({
          harnesses: {
            claude: {
              matcher: "Edit|Write",
              command: "bash $CLAUDE_PROJECT_DIR/.codex/hooks/fixture-body.sh",
            },
          },
        }),
      ]),
    ).toThrow("must target the claude adapter directory .claude/hooks/");
  });

  it.each([
    ["path traversal", "bash $CLAUDE_PROJECT_DIR/.claude/hooks/../evil.sh"],
    ["nested subdirectory", "bash $CLAUDE_PROJECT_DIR/.claude/hooks/nested/evil.sh"],
    ["shell metacharacters", "bash $CLAUDE_PROJECT_DIR/.claude/hooks/evil;rm.sh"],
    ["command substitution", "bash $CLAUDE_PROJECT_DIR/.claude/hooks/$(rm).sh"],
    ["non-.sh name", "bash $CLAUDE_PROJECT_DIR/.claude/hooks/evil.bash"],
    ["dotfile name", "bash $CLAUDE_PROJECT_DIR/.claude/hooks/.hidden.sh"],
  ] as const)("rejects unsafe shim names: %s", (_label, command) => {
    expect(() =>
      deriveHookShims([
        claudeWiring({ harnesses: { claude: { matcher: "Edit|Write", command } } }),
      ]),
    ).toThrow(/safe \*\.sh segment|must target the claude adapter directory/u);
  });

  it("rejects absolute write targets", () => {
    expect(() =>
      deriveHookShims([
        claudeWiring({
          harnesses: {
            claude: { matcher: "Edit|Write", command: "bash $CLAUDE_PROJECT_DIR//etc/evil.sh" },
          },
        }),
      ]),
    ).toThrow("must target the claude adapter directory .claude/hooks/");
  });

  it.each([
    ["outside scripts/ai-hooks", "scripts/evil.sh"],
    ["traversal inside the body dir", "scripts/ai-hooks/../evil.sh"],
    ["nested body path", "scripts/ai-hooks/nested/evil.sh"],
    ["non-.sh body", "scripts/ai-hooks/evil.ts"],
    ["absolute body", "/etc/evil.sh"],
  ] as const)("rejects bodies outside the canonical grammar: %s", (_label, body) => {
    expect(() => deriveHookShims([claudeWiring({ body })])).toThrow(
      /body must (live under|name a single) scripts\/ai-hooks\//u,
    );
  });

  it("rejects colliding shim output paths across controls", () => {
    expect(() =>
      deriveHookShims([claudeWiring(), claudeWiring({ controlId: "hook/fixture-collision" })]),
    ).toThrow(
      "hook/fixture-collision.hookWiring.harnesses.claude.command collides with hook/fixture-claude on shim output .claude/hooks/fixture-body.sh",
    );
  });

  it("yields one confined unique path per harness association, sorted by path", () => {
    const wirings: ShimWiringInput[] = [
      {
        controlId: "hook/fixture-all",
        event: "PostToolUse",
        body: "scripts/ai-hooks/fixture-body.sh",
        harnesses: {
          claude: {
            matcher: "Edit|Write",
            command: "bash $CLAUDE_PROJECT_DIR/.claude/hooks/fixture-body.sh",
          },
          codex: {
            matcher: "apply_patch",
            command: 'bash "$(git rev-parse --show-toplevel)/.codex/hooks/fixture-body.sh"',
            statusMessage: "Fixture",
          },
          copilot: {
            matcher: "create|edit",
            command: 'bash "$(git rev-parse --show-toplevel)/.copilot/hooks/fixture-body.sh"',
          },
        },
      },
      {
        controlId: "hook/fixture-lifecycle",
        event: "SessionStart",
        body: "scripts/ai-hooks/another-body.sh",
        harnesses: {
          claude: {
            matcher: "startup|resume",
            command: "bash $CLAUDE_PROJECT_DIR/.claude/hooks/another-body.sh",
          },
        },
      },
    ];

    const shims = deriveHookShims(wirings);
    const harnessAssociations = wirings.flatMap((wiring) => Object.keys(wiring.harnesses));

    expect(shims).toHaveLength(harnessAssociations.length);
    expect(new Set(shims.map((shim) => shim.relPath)).size).toBe(shims.length);
    for (const shim of shims) {
      expect(shim.relPath.startsWith(`${HOOK_SHIM_DIRS[shim.harness]}/`)).toBe(true);
    }
    expect(shims.map((shim) => shim.relPath)).toEqual(
      [...shims.map((shim) => shim.relPath)].sort(),
    );
    // Lifecycle-event shims are plain Claude exec shims — no dispatch layer.
    const lifecycle = shims.find((shim) => shim.relPath === ".claude/hooks/another-body.sh");
    expect(lifecycle?.content).toContain('exec bash "$REPO_ROOT/scripts/ai-hooks/another-body.sh"');
    expect(lifecycle?.content).not.toContain("ai_copilot_dispatch");
  });
});
