import { HARNESS_MANIFEST_FILENAME } from "./harness-manifest.js";
import {
  type HookHarness,
  isNonEmptyString,
  isObject,
  resolveHookWiring,
} from "./hook-wiring-schema.js";

interface HookTimeoutConstantBinding {
  readonly controlId: string;
  readonly harness: HookHarness;
  readonly variableName: string;
}

interface HookTimeoutConstant {
  readonly variableName: string;
  readonly timeout: number;
}

const HOOK_TIMEOUT_CONSTANT_BINDINGS = [
  {
    controlId: "hook/ai-bun-run-quiet",
    harness: "claude",
    variableName: "BUN_RUN_QUIET_HOOK_TIMEOUT",
  },
  {
    controlId: "hook/ai-git-commit-quiet",
    harness: "claude",
    variableName: "GIT_COMMIT_QUIET_HOOK_TIMEOUT",
  },
] as const satisfies readonly HookTimeoutConstantBinding[];

const SHELL_VARIABLE_NAME_PATTERN = /^[A-Za-z_]\w*$/u;

function collectControlsById(manifest: unknown): ReadonlyMap<string, Record<string, unknown>> {
  if (!isObject(manifest) || !Array.isArray(manifest.controls)) {
    throw new Error(`${HARNESS_MANIFEST_FILENAME} must declare a controls array`);
  }

  const controlsById = new Map<string, Record<string, unknown>>();
  for (const [index, control] of manifest.controls.entries()) {
    if (!isObject(control)) {
      throw new Error(`control entry at index ${String(index)} must be an object`);
    }
    if (!isNonEmptyString(control.id)) {
      throw new Error(`control entry at index ${String(index)} must declare a non-empty id`);
    }
    if (controlsById.has(control.id)) {
      throw new Error(`duplicate control id: ${control.id}`);
    }
    controlsById.set(control.id, control);
  }
  return controlsById;
}

function timeoutForBinding(
  controlsById: ReadonlyMap<string, Record<string, unknown>>,
  binding: HookTimeoutConstantBinding,
): number {
  const control = controlsById.get(binding.controlId);
  if (control === undefined) {
    throw new Error(
      `required hook timeout control ${binding.controlId} is missing from harness.controls.json`,
    );
  }

  const wiring = resolveHookWiring(binding.controlId, control.hookWiring);
  const command = wiring.harnesses[binding.harness];
  if (command === undefined) {
    throw new Error(
      `hookWiring.harnesses.${binding.harness} is required for ${binding.variableName}`,
    );
  }
  if (command.timeout === undefined) {
    throw new Error(
      `hookWiring.harnesses.${binding.harness}.timeout is required for ${binding.variableName}`,
    );
  }
  return command.timeout;
}

function collectHookTimeoutConstants(manifest: unknown): readonly HookTimeoutConstant[] {
  const controlsById = collectControlsById(manifest);
  const constants = HOOK_TIMEOUT_CONSTANT_BINDINGS.map((binding) => ({
    variableName: binding.variableName,
    timeout: timeoutForBinding(controlsById, binding),
  }));
  if (new Set(constants.map(({ timeout }) => timeout)).size > 1) {
    throw new Error(
      `quiet-hook timeout ceilings must match: ${constants
        .map(({ timeout, variableName }) => `${variableName}=${String(timeout)}`)
        .join(", ")}`,
    );
  }
  return constants;
}

export function renderHookTimeoutConstantsShellFromManifest(manifest: unknown): string {
  const lines = [
    "# shellcheck shell=bash",
    "# shellcheck disable=SC2034",
    "# Generated by scripts/harness/generate-hook-timeout-constants.ts. Do not edit by hand.",
    "",
  ];

  for (const constant of collectHookTimeoutConstants(manifest)) {
    if (!SHELL_VARIABLE_NAME_PATTERN.test(constant.variableName)) {
      throw new Error(`invalid shell variable name for hook timeout: ${constant.variableName}`);
    }
    lines.push(`${constant.variableName}=${String(constant.timeout)}`);
  }

  return `${lines.join("\n")}\n`;
}
