import { HARNESS_MANIFEST_FILENAME } from "./harness-manifest.js";
import type { HarnessManifest } from "./harness-manifest-schema.js";
import { type HookHarness, resolveHookWiring } from "./hook-wiring-schema.js";

type HarnessControl = HarnessManifest["controls"][number];

interface HookTimeoutConstantBinding {
  readonly controlId: string;
  readonly harness: HookHarness;
  readonly variableName: string;
}

interface HookTimeoutConstant {
  readonly variableName: string;
  readonly timeout: number;
}

const HOOK_TIMEOUT_CONSTANT_BINDINGS = [
  {
    controlId: "hook/ai-bun-run-quiet",
    harness: "claude",
    variableName: "BUN_RUN_QUIET_HOOK_TIMEOUT",
  },
  {
    controlId: "hook/ai-git-commit-quiet",
    harness: "claude",
    variableName: "GIT_COMMIT_QUIET_HOOK_TIMEOUT",
  },
] as const satisfies readonly HookTimeoutConstantBinding[];

const SHELL_VARIABLE_NAME_PATTERN = /^[A-Za-z_]\w*$/u;

// Entry shape, id uniqueness, and the controls array itself are the typed
// contract's job (harness-manifest-schema.ts), so this module keeps only the
// binding-level semantics: which controls must exist, carry claude wiring, and
// agree on one ceiling.
function collectControlsById(manifest: HarnessManifest): ReadonlyMap<string, HarnessControl> {
  return new Map(manifest.controls.map((control) => [control.id, control]));
}

function timeoutForBinding(
  controlsById: ReadonlyMap<string, HarnessControl>,
  binding: HookTimeoutConstantBinding,
): number {
  const control = controlsById.get(binding.controlId);
  if (control === undefined) {
    throw new Error(
      `required hook timeout control ${binding.controlId} is missing from ${HARNESS_MANIFEST_FILENAME}`,
    );
  }
  if (control.kind !== "hook") {
    throw new Error(
      `hook timeout control ${binding.controlId} must be kind=hook, not ${control.kind}`,
    );
  }

  const wiring = resolveHookWiring(binding.controlId, control.hookWiring);
  const command = wiring.harnesses[binding.harness];
  if (command === undefined) {
    throw new Error(
      `hookWiring.harnesses.${binding.harness} is required for ${binding.variableName}`,
    );
  }
  if (command.timeout === undefined) {
    throw new Error(
      `hookWiring.harnesses.${binding.harness}.timeout is required for ${binding.variableName}`,
    );
  }
  return command.timeout;
}

function collectHookTimeoutConstants(manifest: HarnessManifest): readonly HookTimeoutConstant[] {
  const controlsById = collectControlsById(manifest);
  const constants = HOOK_TIMEOUT_CONSTANT_BINDINGS.map((binding) => ({
    variableName: binding.variableName,
    timeout: timeoutForBinding(controlsById, binding),
  }));
  if (new Set(constants.map(({ timeout }) => timeout)).size > 1) {
    throw new Error(
      `quiet-hook timeout ceilings must match: ${constants
        .map(({ timeout, variableName }) => `${variableName}=${String(timeout)}`)
        .join(", ")}`,
    );
  }
  return constants;
}

export function renderHookTimeoutConstantsShellFromManifest(manifest: HarnessManifest): string {
  const lines = [
    "# shellcheck shell=bash",
    "# shellcheck disable=SC2034",
    "# Generated by scripts/harness/generate-hook-timeout-constants.ts. Do not edit by hand.",
    "",
  ];

  for (const constant of collectHookTimeoutConstants(manifest)) {
    if (!SHELL_VARIABLE_NAME_PATTERN.test(constant.variableName)) {
      throw new Error(`invalid shell variable name for hook timeout: ${constant.variableName}`);
    }
    lines.push(`${constant.variableName}=${String(constant.timeout)}`);
  }

  return `${lines.join("\n")}\n`;
}
