// Renders the .husky/pre-push near-duplicates boundary trigger from the
// scanner's own truth. The hook's changed-path grep decides whether a push pays
// the whole-tree --check-baseline scan, and it must fire on exactly the inputs
// that can change the detector's verdict:
//   - source extensions the scanner walks — buildSourceExtensions over
//     BUILT_IN_SOURCE_EXTENSIONS (scripts/drift-ai/scope.ts) plus
//     drift-ai.config.json additionalSourceExtensions;
//   - the two whole-file inputs that change detector truth without touching any
//     source file (NEAR_DUPLICATES_TRIGGER_FILES below).
//
// The hook used to carry that ERE by hand, pinned by a checker that re-parsed
// the hook text (scripts/harness/pre-push-scope-pin.ts). Generating the ENTIRE
// pattern into a fragment the hook sources removes both the seam and the
// parser: the standard generatedSurface freshness gate now subsumes the pin.

import { readFileSync } from "node:fs";
import { join } from "node:path";

import { buildSourceExtensions } from "../drift-ai/scope.js";
import { isRecord } from "../lib/records.js";

/** Shell variable the generated fragment defines and `.husky/pre-push` greps with. */
export const PRE_PUSH_SCOPE_TRIGGER_VARIABLE = "MUSI_PRE_PUSH_NEAR_DUPLICATES_TRIGGER";

/**
 * Whole-file trigger inputs, matched by basename anywhere in the tree: the
 * committed baseline is the comparison target itself, and the drift-ai config
 * feeds thresholds and exclusions, so a config-only push changes detector truth
 * without touching a single scanned source file.
 */
export const NEAR_DUPLICATES_TRIGGER_FILES = [
  "sensor-near-duplicates.baseline.json",
  "drift-ai.config.json",
] as const;

/** grep -qE metacharacters that need escaping inside the generated alternation. */
const ERE_METACHARACTERS = /[.*+?^$|(){}[\]\\]/gu;

function escapeExtendedRegExp(value: string): string {
  return value.replace(ERE_METACHARACTERS, String.raw`\$&`);
}

function shellSingleQuote(value: string): string {
  return `'${value.replaceAll("'", String.raw`'\''`)}'`;
}

/**
 * Build the full boundary-trigger ERE. Extension order follows the scanner's
 * set iteration order; the pattern is a pure membership test, so order is
 * presentation only. No empty-extension defense: the only production input is
 * `buildSourceExtensions`, which seeds six non-empty built-ins and admits an
 * addition only when the normalized extension is longer than one character.
 */
export function buildNearDuplicatesTriggerPattern(extensions: ReadonlySet<string>): string {
  const bareExtensions = [...extensions].map((extension) => extension.replace(/^\./u, ""));
  const files = NEAR_DUPLICATES_TRIGGER_FILES.map(escapeExtendedRegExp).join("|");
  const suffixes = bareExtensions.map(escapeExtendedRegExp).join("|");
  return String.raw`(^|/)(${files})$|\.(${suffixes})$`;
}

/** Pure projection of the scanned extension set into the sourceable fragment. */
// porting-knob: pre-push-scope-trigger -- retarget the near-duplicates boundary trigger inputs
export function renderPrePushScopeTriggerShell(extensions: ReadonlySet<string>): string {
  return [
    "# shellcheck shell=bash",
    "# shellcheck disable=SC2034",
    "# Generated by scripts/harness/generate-pre-push-scope-trigger.ts. Do not edit by hand.",
    "# Regenerate with `bun run harness:pre-push-trigger`.",
    "#",
    "# The near-duplicates boundary trigger .husky/pre-push greps changed paths with.",
    "# Extensions come from the scanner's own truth (BUILT_IN_SOURCE_EXTENSIONS in",
    "# scripts/drift-ai/scope.ts plus drift-ai.config.json additionalSourceExtensions),",
    "# so the hook and the scanner cannot drift apart.",
    "",
    `${PRE_PUSH_SCOPE_TRIGGER_VARIABLE}=${shellSingleQuote(buildNearDuplicatesTriggerPattern(extensions))}`,
    "",
  ].join("\n");
}

// Reads additionalSourceExtensions straight from drift-ai.config.json instead
// of importing loadDriftAiConfig: the full config module drags ~35 drift-ai
// files into the generator's import closure — which is also the harness:check
// fixture copy closure — for one array. Lenient by design: a malformed config
// fails the sensor itself long before this generator matters, and
// buildSourceExtensions applies the same trim/lowercase/dot normalization the
// scanner uses.
function readAdditionalSourceExtensions(repoRoot: string): readonly string[] {
  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(join(repoRoot, "drift-ai.config.json"), "utf8"));
  } catch {
    return [];
  }
  // isRecord, not a cast: it also rejects a top-level JSON array, which is
  // `typeof "object"` and would otherwise be indexed for a field it can never
  // have. scripts/lib/records.ts is already in this generator's closure.
  if (!isRecord(raw)) return [];
  const additional = raw["additionalSourceExtensions"];
  if (!Array.isArray(additional)) return [];
  return additional.filter((value): value is string => typeof value === "string");
}

/** The scanner's effective source-extension set for `repoRoot`. */
export function readNearDuplicatesScannerExtensions(repoRoot: string): ReadonlySet<string> {
  return buildSourceExtensions(readAdditionalSourceExtensions(repoRoot));
}
