# shellcheck shell=bash
# shellcheck disable=SC2034
# Generated by scripts/harness/generate-pre-push-scope-trigger.ts. Do not edit by hand.
# Regenerate with `bun run harness:pre-push-trigger`.
#
# The near-duplicates boundary trigger .husky/pre-push greps changed paths with.
# Extensions come from the scanner's own truth (BUILT_IN_SOURCE_EXTENSIONS in
# scripts/drift-ai/scope.ts plus drift-ai.config.json additionalSourceExtensions),
# so the hook and the scanner cannot drift apart.

MUSI_PRE_PUSH_NEAR_DUPLICATES_TRIGGER='(^|/)(sensor-near-duplicates\.baseline\.json|drift-ai\.config\.json)$|\.(ts|tsx|js|jsx|mjs|cjs)$'
