import { describe, expect, it } from "vitest";

import { renderBacklogCatalog } from "./backlog-catalog-render.js";
import { classifyBacklogTree } from "./backlog-lint-classify.js";
import { lifecycleFromStatus, recognizedStatus } from "./backlog-lint-status.js";
import type { BacklogLintFile } from "./backlog-lint-types.js";

const BACKLOG_DIR = "docs/agent_notes/backlog";

function file(path: string, ...body: string[]): BacklogLintFile {
  return { path: `${BACKLOG_DIR}/${path}`, text: body.join("\n") };
}

function note(path: string, status: string): BacklogLintFile {
  return file(path, `# ${path}`, "", `Status: ${status}`, "", "## Body");
}

const FILES: readonly BacklogLintFile[] = [
  note("README.md", "Reference — retention policy"),
  note("loose-note.md", "Parked — waiting on the socket rework"),
  note("pack/00-index.md", "Parked task index"),
  note("pack/10-a.md", "Not started"),
  note("pack/11-b.md", "Done"),
  file("pack/RUN-LEDGER.md", "# Ledger", "", "Status: Record of every run"),
  file("pack/working/packet.md", "# P", "", "raw packet"),
  note("closed-pack/00-index.md", "Drained — retained as the provenance record"),
  note("closed-pack/10-a.md", "Done"),
  note("closed-pack/11-b.md", "Superseded by 10-a"),
];

function render(files: readonly BacklogLintFile[] = FILES): string {
  return renderBacklogCatalog(classifyBacklogTree({ files, backlogDir: BACKLOG_DIR }));
}

describe("renderBacklogCatalog", () => {
  it("opens with a do-not-edit banner and a status the vocabulary reads as terminal", () => {
    // The page is itself a backlog note the lint reads. Its own status has to
    // stay inside the vocabulary, or the catalog counts itself as open work.
    const lines = render().split("\n");
    expect(lines[0]).toBe("# Backlog catalog");
    expect(lines).toContain(
      "<!-- Generated by scripts/generate-backlog-catalog.ts. Do not edit by hand. -->",
    );
    const status = lines
      .find((line) => line.startsWith("Status:"))
      ?.slice("Status:".length)
      .trim();
    expect(status).toBeDefined();
    expect(recognizedStatus(status ?? "")).toBe(true);
    expect(lifecycleFromStatus(status ?? "")).toBe("terminal");
  });

  it("rolls each pack up with its index and lifecycle counts", () => {
    const rendered = render();
    expect(rendered).toContain(
      "| [closed-pack](./closed-pack/00-index.md) | `00-index.md` | 0 | 3 | 0 | 3 | 0 |",
    );
    expect(rendered).toContain(
      "| [pack](./pack/00-index.md) | `00-index.md` | 2 | 2 | 0 | 4 | 1 |",
    );
  });

  it("marks a pack whose index name is not canonical", () => {
    const rendered = render([
      file("odd/00-report.md", "# Report", "", "Status: Closed"),
      note("odd/10-a.md", "Done"),
      note("odd/11-b.md", "Done"),
    ]);
    expect(rendered).toContain("`00-report.md` (non-canonical)");
  });

  it("reports a pack with no task index at all", () => {
    const rendered = render([note("orphan/10-a.md", "Ready"), note("orphan/11-b.md", "Ready")]);
    expect(rendered).toContain("| orphan | none | 2 | 0 | 0 | 2 | 0 |");
  });

  it("totals the tree by record class", () => {
    const rendered = render();
    expect(rendered).toContain("| leaf | 1 | 3 | 0 | 4 |");
    expect(rendered).toContain("| standalone note | 1 | 1 | 0 | 2 |");
    expect(rendered).toContain("| working artifact | 0 | 0 | 1 | 1 |");
  });

  it("lists every root note and every pack record outside the task index", () => {
    const rendered = render();
    expect(rendered).toContain(
      "| [loose-note.md](./loose-note.md) | actionable | Parked — waiting on the socket rework |",
    );
    expect(rendered).toContain(
      "| [RUN-LEDGER.md](./pack/RUN-LEDGER.md) | pack | terminal | Record of every run |",
    );
  });

  it("does not enumerate leaves, because each pack's own index already does", () => {
    expect(render()).not.toContain("./pack/10-a.md");
  });

  it("shows an em dash for a note that declares no status", () => {
    const rendered = render([file("undated.md", "# U", "", "no header here")]);
    expect(rendered).toContain("| [undated.md](./undated.md) | unknown | — |");
  });

  it("escapes table-breaking pipes and truncates a long status value", () => {
    const long = `a|b ${"x".repeat(120)}`;
    const rendered = render([note("loud.md", long)]);
    expect(rendered).toContain("a\\|b");
    expect(rendered).toContain("…");
    const row = rendered.split("\n").find((line) => line.includes("loud.md")) ?? "";
    expect(row.length).toBeLessThan(140);
  });

  it("clips before an unclosed inline code span, never inside one", () => {
    const rendered = render([
      note("code.md", "Parked — waiting on the rework in `packages/server/src/services/x.ts`"),
    ]);
    const row = rendered.split("\n").find((line) => line.includes("code.md")) ?? "";
    expect(row).toContain("…");
    expect((row.match(/`/gu) ?? []).length % 2).toBe(0);
  });

  it("collapses irregular whitespace inside a status value into single spaces", () => {
    const rendered = render([note("wrapped.md", "Parked  pending   the rework")]);
    const row = rendered.split("\n").find((line) => line.includes("wrapped.md")) ?? "";
    expect(row).toContain("| Parked pending the rework |");
  });

  it("keeps the text of a pack-relative link but drops the target", () => {
    const rendered = render([
      note("linked.md", "Reference — background for [00-index.md](./00-index.md)"),
    ]);
    expect(rendered).toContain("Reference — background for 00-index.md");
    expect(rendered).not.toContain("(./00-index.md)");
  });
});
