// Walks the project ESLint config, collects principle strings from rules under
// the local/* namespace, and emits an agent-facing markdown doc.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const PROCESS_ARG_OFFSET = 2;

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const outputPath = join(repoRoot, "docs/generated/local-lint-rules.md");

interface RuleEntry {
  readonly id: string;
  readonly description?: string;
  readonly principle: string;
}

interface RuleDocs {
  readonly description?: string;
  readonly principle?: string;
}

interface LocalRule {
  readonly meta?: {
    readonly docs?: RuleDocs;
  };
}

interface LocalPlugin {
  readonly rules: Record<string, LocalRule>;
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function hasLocalRules(value: unknown): value is LocalPlugin {
  if (!isObject(value)) return false;
  return isObject(value.rules);
}

function blockLocalPlugin(block: unknown): LocalPlugin | undefined {
  if (!isObject(block)) return undefined;
  const plugins = block.plugins;
  if (!isObject(plugins)) return undefined;
  const local = plugins.local;
  return hasLocalRules(local) ? local : undefined;
}

function findLocalPlugin(config: readonly unknown[]): LocalPlugin | undefined {
  for (const block of config) {
    const localPlugin = blockLocalPlugin(block);
    if (localPlugin !== undefined) return localPlugin;
  }
  return undefined;
}

function readCurrentOutput(): string {
  try {
    return readFileSync(outputPath, "utf8");
  } catch {
    return "";
  }
}

async function collectRules(): Promise<RuleEntry[]> {
  const configPath = pathToFileURL(join(repoRoot, "eslint.config.js")).href;
  const configModule: unknown = await import(configPath);
  if (!isObject(configModule) || !Array.isArray(configModule.default)) {
    throw new Error("eslint.config.js did not export a config array");
  }

  const localPlugin = findLocalPlugin(configModule.default);
  if (localPlugin === undefined) {
    throw new Error("Could not find local plugin in eslint.config.js");
  }

  const entries: RuleEntry[] = [];
  for (const [id, rule] of Object.entries(localPlugin.rules)) {
    const docs = rule.meta?.docs;
    const principle = docs?.principle;
    if (typeof principle !== "string") continue;
    const description = docs?.description;
    entries.push({
      id: `local/${id}`,
      description,
      principle,
    });
  }
  entries.sort((a, b) => a.id.localeCompare(b.id));
  return entries;
}

function renderMarkdown(entries: readonly RuleEntry[]): string {
  const lines: string[] = [];
  lines.push("# Local ESLint Rules");
  lines.push("");
  lines.push("> Generated by `scripts/generate-lint-guidance.ts`. Do not edit by hand.");
  lines.push("> Refresh with `bun run docs:lint-guidance`.");
  lines.push("");
  lines.push("This document is the agent-facing reference for Musi's `local/*` ESLint rules.");
  lines.push(
    "Each entry shows the rule's principle: a one- or two-sentence statement of why the rule exists, so an AI agent reading a diagnostic can repair from message.",
  );
  lines.push("");
  for (const entry of entries) {
    lines.push(`## \`${entry.id}\``);
    lines.push("");
    if (entry.description !== undefined) {
      lines.push(`**Description:** ${entry.description}`);
      lines.push("");
    }
    lines.push(`**Principle:** ${entry.principle}`);
    lines.push("");
  }
  while (lines[lines.length - 1] === "") {
    lines.pop();
  }
  return `${lines.join("\n")}\n`;
}

function parseArgs(args: readonly string[]): { readonly checkMode: boolean } {
  const unknownArgs = args.filter((arg) => arg !== "--" && arg !== "--check");
  if (unknownArgs.length > 0) {
    throw new Error(`Unknown argument(s): ${unknownArgs.join(", ")}`);
  }
  return { checkMode: args.includes("--check") };
}

async function main(): Promise<void> {
  const { checkMode } = parseArgs(process.argv.slice(PROCESS_ARG_OFFSET));
  const entries = await collectRules();
  const rendered = renderMarkdown(entries);

  if (checkMode) {
    const current = readCurrentOutput();
    if (current !== rendered) {
      console.error(
        `${outputPath} is out of date. Run \`bun run docs:lint-guidance\` and commit the result.`,
      );
      process.exitCode = 1;
      return;
    }
    console.log(`${outputPath} is up to date.`);
    return;
  }

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, rendered);
  console.log(`Wrote ${outputPath} (${String(entries.length)} rule(s) with principles).`);
}

await main();
