// Walks the project ESLint config, validates rule guidance metadata under the
// local/* namespace, and emits an agent-facing markdown doc.

import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { runDocGeneratorAsync } from "./lib/doc-generator.js";
import {
  formatRuleDocsFailures,
  loadLintRuleDocs,
  RULE_DOC_CATEGORIES,
  type RuleDocCategory,
  type RuleDocsEntry,
} from "./lib/lint-rule-docs.js";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = join(repoRoot, "docs/generated/local-lint-rules.md");

type RuleEntry = RuleDocsEntry;

const CATEGORY_HEADINGS: Record<RuleDocCategory, string> = {
  maintainability: "Maintainability",
  "architecture-fitness": "Architecture fitness",
  behavior: "Behavior",
};

function isNonEmptyString(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0;
}

async function collectRules(): Promise<RuleEntry[] | undefined> {
  const { entries, failures } = await loadLintRuleDocs(repoRoot);
  if (failures.length > 0) {
    console.error(formatRuleDocsFailures(failures));
    process.exitCode = 1;
    return undefined;
  }
  const sorted = [...entries];
  sorted.sort((a, b) => {
    const categoryOrder =
      RULE_DOC_CATEGORIES.indexOf(a.category) - RULE_DOC_CATEGORIES.indexOf(b.category);
    return categoryOrder === 0 ? a.id.localeCompare(b.id) : categoryOrder;
  });
  return sorted;
}

function formatPairedGuide(pairedGuide: string): string {
  if (pairedGuide === "none") return "none";
  const href = relative("docs/generated", pairedGuide).replaceAll("\\", "/");
  return `[${pairedGuide}](${href})`;
}

function formatRepair(entry: RuleEntry): string {
  if (entry.repairKind !== "codemod") return entry.repairKind;
  const command = entry.repairCommand;
  if (!isNonEmptyString(command)) throw new Error(`Missing repair command for ${entry.id}`);
  return `${entry.repairKind} — \`${command}\``;
}

function renderMarkdown(entries: readonly RuleEntry[]): string {
  const lines: string[] = [];
  lines.push("# Local ESLint Rules");
  lines.push("");
  lines.push("> Generated by `scripts/generate-lint-guidance.ts`. Do not edit by hand.");
  lines.push("> Refresh with `bun run docs:lint-guidance`.");
  lines.push("");
  lines.push("This document is the agent-facing reference for Musi's `local/*` ESLint rules.");
  lines.push(
    "This table is generated from `meta.docs` on each rule and grouped into maintainability, architecture-fitness, and behavior categories so an AI agent can repair from a diagnostic.",
  );
  lines.push("");
  let currentCategory: RuleDocCategory | undefined;
  for (const entry of entries) {
    if (entry.category !== currentCategory) {
      lines.push(`## ${CATEGORY_HEADINGS[entry.category]}`);
      lines.push("");
      currentCategory = entry.category;
    }
    lines.push(`### \`${entry.id}\``);
    lines.push("");
    lines.push(`**Description:** ${entry.description}`);
    lines.push("");
    lines.push(`**Principle:** ${entry.principle}`);
    lines.push("");
    lines.push(`**Category:** ${entry.category}`);
    lines.push("");
    lines.push(`**Paired guide:** ${formatPairedGuide(entry.pairedGuide)}`);
    lines.push("");
    lines.push(`**Repair:** ${formatRepair(entry)}`);
    lines.push("");
  }
  while (lines[lines.length - 1] === "") {
    lines.pop();
  }
  return `${lines.join("\n")}\n`;
}

await runDocGeneratorAsync({
  outputPath,
  refreshCommand: "docs:lint-guidance",
  render: async () => {
    const entries = await collectRules();
    if (entries === undefined) return undefined;
    return {
      rendered: renderMarkdown(entries),
      wroteSuffix: ` (${String(entries.length)} rule(s) with metadata)`,
    };
  },
});
