#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

mode="write"
case "${1:-}" in
  --check) mode="check" ;;
  '') ;;
  *)
    printf 'module:index: unknown argument: %s\n' "$1" >&2
    printf 'usage: generate-module-index.sh [--check]\n' >&2
    exit 2
    ;;
esac

tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

{
  echo "# Module Index"
  echo
  echo "Generated by \`bun run module:index\`. Do not edit by hand."
  echo
  echo "This index lists every \`*MODULE.md\` orientation file in the repository."
  echo "For the module-doc contract, see [docs/module-docs.md](docs/module-docs.md)."
  echo
  echo "## Modules"
  echo

  while IFS= read -r module_doc; do
    title="$(sed -n '1{s/^# *//;p;q;}' "$module_doc")"
    if [ -z "$title" ]; then
      title="$module_doc"
    fi
    title="$(printf '%s' "$title" | perl -CS -pe 's/\x{2013}|\x{2014}/-/g')"

    if [[ "$module_doc" == */MODULE.md ]]; then
      module_ref="${module_doc%/MODULE.md}/"
    else
      module_ref="$module_doc"
    fi

    printf -- "- [%s](%s) - \`%s\`\n" "$title" "$module_doc" "$module_ref"
  done < <(rg --files -g '*MODULE.md' | sort)
} > "$tmp_file"

if [ "$mode" = "check" ]; then
  if [ -f MODULE-INDEX.md ] && cmp -s "$tmp_file" MODULE-INDEX.md; then
    echo "module:index: OK"
    exit 0
  fi

  printf 'module:index: MODULE-INDEX.md is out of date; run `bun run module:index`.\n' >&2
  if [ -f MODULE-INDEX.md ]; then
    diff -u MODULE-INDEX.md "$tmp_file" >&2 || true
  else
    printf 'module:index: MODULE-INDEX.md is missing.\n' >&2
  fi
  exit 1
fi

mv "$tmp_file" MODULE-INDEX.md
trap - EXIT
