import type { CoverageEntry } from "./lint-coverage-map-manifest-schema.js";

export const harnessAuditEntries: readonly CoverageEntry[] = [
  {
    id: "scripts-logs-audit-fixtures-business-events-server-jsonl",
    globs: [
      "scripts/logs-audit/fixtures/business-events-server.jsonl",
      "scripts/logs-audit/fixtures/redacted-server.jsonl",
    ],
    files: "2 .jsonl",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`excluded` — fixture",
    status: ["excluded"],
    followUp: "—",
  },
  {
    id: "scripts-harness-audit-ts",
    globs: ["scripts/harness-audit.ts", "scripts/harness/harness-audit-report.ts"],
    files:
      "2 .ts (the `harness:audit` diagnostics fusion CLI plus its report assembly/rendering split)",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed: "none — normal lint enforces the full rule surface, including the max-300 cap",
    status: ["linted", "ratcheted"],
    followUp: "The CLI re-exports the report surface.",
  },
  {
    id: "scripts-harness-harness-audit-test-ts",
    globs: ["scripts/harness/harness-audit.test.ts"],
    files: "1 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed: "none — focused Vitest coverage exercises the diagnostics fusion consumer",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
];

export const otherScriptFixtureEntries: readonly CoverageEntry[] = [
  {
    id: "scripts-fixtures-lint-ratchet-report-lint-ratchet-report-clean-json",
    globs: ["scripts/fixtures/lint-ratchet-report/lint-ratchet-report-clean.json"],
    files: "1 .json",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`excluded` — fixture diagnostics envelope used by the report smoke",
    status: ["excluded"],
    followUp: "—",
  },
  {
    id: "scripts-fixtures-lint-ratchet-report-lint-ratchet-report-regression-json",
    globs: ["scripts/fixtures/lint-ratchet-report/lint-ratchet-report-regression.json"],
    files: "1 .json",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`excluded` — fixture diagnostics envelope used by the report smoke",
    status: ["excluded"],
    followUp: "—",
  },
  {
    id: "scripts-harness-audit-fixtures-json",
    globs: ["scripts/harness-audit/fixtures/*.json"],
    files: "5 .json",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed:
      "`excluded` — `harness:audit` envelope fixtures (real `lint:ratchet`/`logs:audit` shapes plus `drift:ai` projections) consumed by `harness-audit.test.ts`",
    status: ["excluded"],
    followUp: "—",
  },
  {
    id: "scripts-fixtures-lint-ratchet-expected-config-mjs",
    globs: ["scripts/fixtures/lint-ratchet/expected-*.config.mjs"],
    files: "1 .mjs",
    normalLint: {
      covered: false,
      note: "targeted `scripts/fixtures/**` ignore; also matches `**/*.config.*`",
    },
    ratchets: "none",
    parser: "—",
    proposed: "`excluded` — expected-generated-config snapshot used by `test-lint-ratchet.sh`",
    status: ["excluded"],
    followUp: "—",
  },
  {
    id: "tools-lint-ratchet-src-kernel-fixtures-message-identity-golden-json",
    globs: ["tools/lint-ratchet/src/kernel/fixtures/message-identity-golden.json"],
    files: "1 .json",
    normalLint: { covered: true, note: "`tools/lint-ratchet/**` reach block" },
    ratchets: "none",
    parser: "`@eslint/json` structural lint",
    proposed:
      "frozen message-identity golden corpus imported by the package's `message-identity.test.ts`",
    status: ["linted"],
    followUp: "—",
  },
  {
    id: "scripts-fixtures-lint-message-eval-2026-07-15-codex-pilot-json",
    globs: ["scripts/fixtures/lint-message-eval/2026-07-15-codex-pilot.json"],
    files: "1 .json",
    normalLint: { covered: false, note: "targeted `scripts/fixtures/**` ignore" },
    ratchets: "none",
    parser: "—",
    proposed:
      "`excluded` — committed treatment/control agent-response trace replayed by `eval:lint-messages`",
    status: ["excluded"],
    followUp:
      "See `docs/guides/lint-message-evals.md` for the capture protocol and sampling caveat.",
  },
  {
    id: "scripts-fixtures-generate-harness-controls-expected-md",
    globs: [
      "scripts/fixtures/generate-harness-controls/expected.md",
      "scripts/fixtures/generate-lint-guidance/expected.md",
    ],
    files: "2 .md",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`excluded` — expected-output snapshots",
    status: ["excluded"],
    followUp: "—",
  },
  {
    id: "scripts-fixtures-generate-verify-steps-manifest-json",
    globs: ["scripts/fixtures/generate-verify-steps/manifest.json"],
    files: "1 .json",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "JSON fixture consumed by Vitest",
    proposed: "`excluded` — fixture manifest",
    status: ["excluded"],
    followUp:
      "Fixture manifest for `scripts/generate-verify-steps.test.ts`; intentionally outside JSON lint because `scripts/fixtures/**` is ignored.",
  },
  {
    id: "scripts-fixtures-generate-verify-steps-expected-generated-sh",
    globs: ["scripts/fixtures/generate-verify-steps/expected.generated.sh"],
    files: "1 .sh",
    normalLint: { covered: true, note: "`bun run lint:shell`" },
    ratchets: "ShellCheck floor",
    parser: "system `shellcheck`",
    proposed: "none",
    status: ["linted"],
    followUp:
      "Expected generated shell snapshot for `scripts/generate-verify-steps.test.ts`; remains ShellCheck-compatible because `lint-shell.sh` discovers `scripts/**/*.sh`.",
  },
  {
    id: "scripts-harness-audit-fixtures-malformed-not-json-txt",
    globs: ["scripts/harness-audit/fixtures/malformed-not-json.txt"],
    files: "1 .txt",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed:
      "`excluded` — malformed diagnostics fixture used by `harness-audit.test.ts` parser-hardening coverage",
    status: ["excluded"],
    followUp: "—",
  },
  {
    id: "scripts-fixtures-test-scripts-all-smoke-tests-txt",
    globs: ["scripts/fixtures/test-scripts/all-smoke-tests.txt"],
    files: "1 .txt",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed:
      "`excluded` — generated all-smokes fixture consumed by `scripts/tests/test-test-scripts.sh`",
    status: ["excluded"],
    followUp: "—",
  },
  {
    id: "scripts-tests-harness-check-fixture-manifest-generated-txt",
    globs: ["scripts/tests/harness-check-fixture-manifest.generated.txt"],
    files: "1 .txt",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed:
      "`excluded` — generated fixture copy manifest (rendered from static import closure plus reasoned `generatedSurface.fixtureExtras` by `bun run verify:steps`) consumed by `scripts/tests/test-harness-check.sh`",
    status: ["excluded"],
    followUp: "—",
  },
];
