import type { CoverageEntry } from "./lint-coverage-map-manifest-schema.js";

export const generateHarnessControlsEntries: readonly CoverageEntry[] = [
  {
    id: "scripts-harness-generate-harness-controls-ts",
    globs: [
      "scripts/harness/generate-harness-controls.ts",
      "scripts/harness/generate-harness-controls-validation.ts",
      "scripts/harness/hook-wiring-doc.ts",
    ],
    files: "3 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed:
      "none — normal lint enforces the full rule surface, including `complexity` and the max-300 cap",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-harness-command-catalog-ts",
    globs: [
      "scripts/harness/command-catalog.ts",
      "scripts/harness/command-catalog.test.ts",
      "scripts/harness/command-catalog-schema.ts",
      "scripts/harness/command-catalog-sections.ts",
      "scripts/harness/command-catalog-sources.ts",
      "scripts/harness/command-catalog-sources.test.ts",
      "scripts/harness/generate-command-catalog.ts",
      "scripts/harness/package-manifest-scripts.ts",
    ],
    files: "8 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed:
      "none — the command-catalog model, its metadata projections and its generator are under normal lint with the rest of the harness scripts",
    status: ["linted", "ratcheted"],
    followUp:
      "Backs `docs/generated/command-catalog.md` and the command-catalog completeness rule in `harness:check`.",
  },
  {
    id: "scripts-harness-control-field-validation-ts",
    globs: ["scripts/harness/control-field-validation.ts"],
    files: "1 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed:
      "none — shared field validation is under normal lint with the harness-control validators it supports",
    status: ["linted", "ratcheted"],
    followUp:
      "Shared by `generate-harness-controls-validation.ts` and `harness-check-validation.ts`.",
  },
  {
    id: "scripts-harness-harness-paths-ts",
    globs: [
      "scripts/harness/harness-paths.ts",
      "scripts/harness/harness-manifest.ts",
      "scripts/harness/harness-manifest.test.ts",
    ],
    files: "3 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed: "none — shared harness path constants and manifest loader under normal lint",
    status: ["linted", "ratcheted"],
    followUp:
      "`harness-manifest.ts` owns `HARNESS_MANIFEST_FILENAME` and the shared manifest loader; `harness-paths.ts` owns the non-portable hook-wiring and generated output-path constants imported by `harness:check`, the generators, and `path-policy`.",
  },
  {
    id: "scripts-harness-harness-manifest-schema-ts",
    globs: [
      "scripts/harness/harness-manifest-schema.ts",
      "scripts/harness/harness-manifest-schema.test.ts",
      "scripts/harness/harness-manifest-loader.ts",
      "scripts/harness/harness-manifest-loader.test.ts",
      "scripts/harness/manifest-contract-check.ts",
      "scripts/harness/manifest-contract-check.test.ts",
      "scripts/harness/generate-manifest-json-schema.ts",
      "scripts/harness/generate-manifest-json-schema.test.ts",
    ],
    files: "8 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed: "none — typed manifest contract, its read seam, and the tripwire under normal lint",
    status: ["linted", "ratcheted"],
    followUp:
      "`harness-manifest-schema.ts` is the whole-manifest Zod contract layered above the Zod-free leaf reader; `harness-manifest-loader.ts` joins leaf IO to that contract; `manifest-contract-check.ts` wires the no-direct-read tripwire (`MANIFEST_DIRECT_READERS`) into `harness:check`; `generate-manifest-json-schema.ts` projects the same contract into the published `schemas/harness.controls.schema.json`. See `docs/guides/harness-manifest-parser.md`.",
  },
  {
    id: "scripts-harness-generated-surfaces-loader-ts",
    globs: [
      "scripts/harness/generated-surfaces-loader.ts",
      "scripts/harness/registration-check.ts",
      "scripts/harness/registration-explain.ts",
      "scripts/harness/registration-explain-cli.ts",
      "scripts/harness/registration-explain-describe.ts",
      "scripts/harness/registration-explain-matchers.ts",
      "scripts/harness/registration-explain-model.ts",
      "scripts/harness/registration-explain-render.ts",
      "scripts/harness/registration-generated-checks.ts",
      "scripts/harness/registration-manifest-checks.ts",
      "scripts/harness/registration-preflight-wiring.ts",
      "scripts/harness/registration-check.test.ts",
      "scripts/harness/registration-explain.test.ts",
      "scripts/harness/registration-preflight-wiring.test.ts",
    ],
    files: "14 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets:
      "`ratchet/local-type-assertion-boundary`; tests also use the script-test Vitest floors",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed:
      "none — focused registration fixtures inject every admitted structural defect class and pin full-check self-wiring",
    status: ["linted", "ratcheted"],
    followUp:
      "Shared non-spawning registration collector for `harness:check` and `harness:registration:check`, plus the read-only `--explain` provenance join (`registration-explain*.ts`) over the same parsed state; the full-check-only wiring tripwire pins hook/engine order, package/control registration, and exact two-way parity between the `VERIFY_STEP_PROJECTIONS` descriptor and the manifest `outputPaths` it must agree with (plus each projection\u2019s reachability from its declared checker).",
  },
  {
    id: "scripts-harness-generate-verify-steps-ts",
    globs: [
      "scripts/harness/generate-verify-steps.ts",
      "scripts/harness/generate-hook-wiring.ts",
      "scripts/harness/hook-shims.ts",
      "scripts/harness/hook-shim-files.ts",
      "scripts/harness/generate-config-surfaces.ts",
      "scripts/harness/generate-hook-timeout-constants.ts",
      "scripts/harness/generate-pre-push-scope-trigger.ts",
      "scripts/harness/generate-skill-artifacts.ts",
      "scripts/harness/generate-command-policy.ts",
      "scripts/harness/command-policy-schema.ts",
      "scripts/harness/command-policy-projection.ts",
    ],
    files: "11 .ts",
    normalLint: { covered: true },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json`",
    proposed:
      "none — focused generator coverage exercises generated verify-step and freshness metadata, hook wiring JSON, hook timeout constants, the pre-push near-duplicates boundary trigger, config-surface `tsconfig` output, manifest-projected skill artifacts, and the agent command-policy rule fragment plus its Claude-native deny projection",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-harness-generate-restricted-disable-rules-ts",
    globs: ["scripts/harness/generate-restricted-disable-rules.ts"],
    files: "1 .ts",
    normalLint: { covered: true },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json`",
    proposed: "none — generated restricted-disable rule-id freshness is part of `harness:check`",
    status: ["linted", "ratcheted"],
    followUp:
      "Generates `eslint-config/ratchet-restricted-disable-rules.generated.js` from `scripts/lint-ratchet/lint-ratchet-config.ts` so the normal-lint inline-disable fence follows the ratchet registry.",
  },
  {
    id: "scripts-harness-generate-local-plugin-ts",
    globs: [
      "scripts/harness/generate-local-plugin.ts",
      "scripts/harness/generate-local-plugin.test.ts",
      "scripts/harness/local-rule-discovery.ts",
      "scripts/harness/generate-lint-rule-controls.ts",
      "scripts/harness/generate-lint-rule-controls.test.ts",
    ],
    files: "5 .ts",
    normalLint: { covered: true },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json`",
    proposed: "none — generated local-plugin registry freshness is part of `harness:check`",
    status: ["linted", "ratcheted"],
    followUp:
      "Generates `eslint-config/local-plugin.generated.js` from the rule modules on disk, and `harness.controls.lint-rules.generated.json` from those modules plus their activation surfaces, so neither the `local` plugin registry nor the lint-rule harness controls need a hand-maintained list.",
  },
  {
    id: "scripts-harness-porting-manifest-ts",
    globs: [
      "scripts/harness/generate-porting-manifest.ts",
      "scripts/harness/porting-recipes.ts",
      "scripts/harness/porting-recipes.test.ts",
    ],
    files: "3 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets:
      "`ratchet/local-type-assertion-boundary`; the test also uses the script-test Vitest floors",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed:
      "none — the derived public copy manifest is gate-checked by `docs:harness-porting:check` and its classification failures are covered by focused unit tests",
    status: ["linted", "ratcheted"],
    followUp:
      "Derives the docs/ai-harness.md adoption copy sets from the source import closure (`scripts/import-closure/`) instead of hand lists, and fails closed when a recipe reaches an unclassified file or an undeclared Musi adapter.",
  },
  {
    id: "scripts-harness-generated-surfaces-ts",
    globs: [
      "scripts/harness/generated-surface-dependencies.ts",
      "scripts/harness/generated-surface-dependencies.test.ts",
      "scripts/harness/generated-surfaces.ts",
      "scripts/harness/generated-surfaces.test.ts",
    ],
    files: "4 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed:
      "none — Zod-strict `generatedSurface` facet loader, shared fixture dependency derivation, residue hygiene, and generated projections under normal lint with focused vitest suites",
    status: ["linted", "ratcheted"],
    followUp:
      "Every generated-surface projection consumes the loader instead of re-reading `harness.controls.json`; `verify:steps:check` holds byte parity and `harness:check` derives the fixture copy closure once.",
  },
  {
    id: "scripts-harness-verify-step-schema-ts",
    globs: [
      "scripts/harness/verify-step-programs.test.ts",
      "scripts/harness/verify-step-programs.ts",
      "scripts/harness/verify-step-schema.ts",
      "scripts/harness/verify-step-artifacts.ts",
      "scripts/harness/hook-wiring-schema.ts",
      "scripts/harness/hook-wiring-schema.test.ts",
    ],
    files: "6 .ts",
    normalLint: { covered: true },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json`",
    proposed:
      "none — shared catalog/profile resolution has a focused resolver suite, the artifact-edge vocabulary and its closure validation are exercised through the verify-step generator suite, and hookWiring's canonical adapter projection, surface tripwire, and exact-key rejection have a focused schema suite; the remaining resolver allow-lists are covered by generator and harness-control validation tests",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-harness-check-skill-inventory-ts",
    globs: [
      "scripts/harness/check-skill-inventory.ts",
      "scripts/harness/skill-artifact-projection.ts",
      "scripts/harness/skill-artifact-projection.test.ts",
      "scripts/harness/skill-inventory-schema.ts",
      "scripts/harness/skill-overlay-content.ts",
      "scripts/harness/skill-projection-files.ts",
      "scripts/harness/skill-smoke-subject-block.ts",
      "scripts/harness/check-skill-inventory.test.ts",
    ],
    files: "8 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed:
      "none — manifest-backed skill projection and focused overlay tests cover generated mirrors, preserved harness/frontmatter/target-owned content, atomic materialization, filesystem-discovered targets, gitignore opt-ins, and generated smoke routing",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-harness-generate-verify-steps-test-ts",
    globs: [
      "scripts/harness/generate-verify-steps.test.ts",
      "scripts/harness/generate-hook-wiring.test.ts",
      "scripts/harness/hook-shims.test.ts",
      "scripts/harness/hook-shim-files.test.ts",
      "scripts/harness/generate-config-surfaces.test.ts",
      "scripts/harness/generate-hook-timeout-constants.test.ts",
      "scripts/harness/generate-skill-artifacts.test.ts",
      "scripts/harness/generate-command-policy.test.ts",
    ],
    files: "8 .ts",
    normalLint: { covered: true },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json`",
    proposed:
      "none — focused Vitest coverage exercises generated command arrays, dynamic resolver and freshness metadata, hook wiring output, hook timeout constants, config-surface tsconfig rendering, skill refresh/check composition, command-policy schema and fragment rendering, committed-fragment freshness, and native deny projection; dispatcher parity is owned by the shell corpus",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-harness-control-field-validation-test-ts",
    globs: [
      "scripts/harness/control-field-validation.test.ts",
      "scripts/harness/fixture-closure-check.test.ts",
      "scripts/harness/harness-check-validation.test.ts",
    ],
    files: "3 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed:
      "none — focused Vitest coverage exercises the shared field validation rules, the script-parity message remedy text, and the fixture copy-closure orchestration (fail-closed no-declaration path, regular-file rejection, missing/stale diffs) over temp repos",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
];
