import type { CoverageEntry } from "./lint-coverage-map-manifest-schema.js";

export const lintedScriptEntriesB: readonly CoverageEntry[] = [
  {
    id: "scripts-cli-option-values-ts",
    globs: ["scripts/cli-option-values.ts"],
    files: "1 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json`",
    proposed: "none — shared CLI option-value guard used by logs:audit and harness:audit",
    status: ["linted", "ratcheted"],
    followUp:
      "Covered through `scripts/logs-audit/logs-audit.test.ts` and `scripts/harness/harness-audit.test.ts` parser cases.",
  },
  {
    id: "scripts-drift-ts",
    globs: ["scripts/drift/**/*.ts"],
    files: "2 .ts (`locator-usage.ts`, `locator-usage.test.ts`)",
    normalLint: { covered: true },
    ratchets:
      "normal `local/max-lines` floor (non-test only), `ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json`",
    proposed: "none",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-generate-lint-guidance-ts",
    globs: ["scripts/generate-lint-guidance.ts"],
    files: "1 .ts",
    normalLint: { covered: true },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json`",
    proposed: "none",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-generate-baseline-conflict-recipes-ts",
    globs: [
      "scripts/generate-baseline-conflict-recipes.ts",
      "scripts/generate-baseline-conflict-recipes.test.ts",
    ],
    files: "2 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json`",
    proposed: "none — focused coverage pins driver-recipe extraction and marker splicing",
    status: ["linted", "ratcheted"],
    followUp:
      "Projects the per-baseline recovery recipe blocks in `docs/guides/lint-ratchet-merges.md` from the package lint-ratchet renderer and Musi's three cases in `scripts/git/baseline-merge-driver.sh`; freshness gated by `docs:baseline-conflict-recipes:check`.",
  },
  {
    id: "scripts-harness-registration-check-ts",
    globs: ["scripts/harness-registration-check.ts"],
    files: "1 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json`",
    proposed: "none — thin CLI over the shared typed registration collector",
    status: ["linted", "ratcheted"],
    followUp:
      "`harness:registration:check` is the fast-commit structural admission command; full `harness:check` calls the same collector before its behavioral checks.",
  },
  {
    id: "scripts-lib-lint-rule-docs-ts",
    globs: [
      "scripts/lib/lint-rule-docs.ts",
      "scripts/lib/doc-generator.ts",
      "scripts/lib/doc-generator.test.ts",
      "scripts/lib/git.ts",
      "scripts/lib/git.test.ts",
      "scripts/lib/cli.ts",
      "scripts/lib/cli.test.ts",
      "scripts/lib/max-lines-policy.ts",
      "scripts/lib/max-lines-policy.test.ts",
      "scripts/lib/atomic-write.ts",
      "scripts/lib/codepoint-compare.ts",
      "scripts/lib/eslint-json.ts",
      "scripts/lib/eslint-main-cache.ts",
      "scripts/lib/eslint-main-cache.test.ts",
      "scripts/lib/process-argv.ts",
      "scripts/lib/verify-metadata-core.ts",
      "scripts/lib/verify-metadata-core.test.ts",
      "scripts/lib/records.ts",
      "scripts/lib/records.test.ts",
      "scripts/lib/process-argv.test.ts",
      "scripts/lib/error-message.ts",
      "scripts/lib/error-message.test.ts",
      "scripts/lib/ts-module-refs.ts",
      "scripts/lib/ts-module-refs.test.ts",
      "scripts/lib/ts-module-refs.parity.test.ts",
      "scripts/lib/path-taxonomy.ts",
      "scripts/lib/path-taxonomy.test.ts",
      "scripts/lib/migration-safety-core.ts",
      "scripts/lib/migration-safety-core.test.ts",
      "scripts/lib/migration-safety-report.ts",
      "scripts/lib/migration-safety-cli.ts",
      "scripts/lib/migration-safety-cli.test.ts",
      "scripts/lib/migration-safety-io.ts",
      "scripts/lib/migration-safety-io.test.ts",
    ],
    files: "34 .ts",
    normalLint: { covered: true },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json`",
    proposed:
      "none — shared script utilities cover lint-rule docs, doc generation, Git plumbing, CLI parsing, max-lines policy, lint-ratchet kernel adapters, ESLint cache identity, direct-run detection, verify metadata, record guards, unknown-error formatting, the shared import-edge classification kernel, the shared source/test path-taxonomy policies, and the Prisma migration-safety scanner's analytical core, renderers, CLI, and effects layer; their focused tests pin the exposed contracts",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-lib-fixtures-verify-metadata-core-corpus-json",
    globs: ["scripts/lib/fixtures/verify-metadata-core-corpus.json"],
    files: "1 .json",
    normalLint: { covered: true },
    ratchets: "none",
    parser: "ESLint",
    proposed:
      "none — committed characterization corpus (legacy-parity + defect-fix expectations) consumed by `verify-metadata-core.test.ts`",
    status: ["linted"],
    followUp: "—",
  },
  {
    id: "scripts-lint-ratchet-lint-ratchet-config-ts",
    globs: ["scripts/lint-ratchet/lint-ratchet-config.ts"],
    files: "1 .ts",
    normalLint: { covered: true },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json`",
    proposed: "none — pure config object",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-lint-ratchet-registry-builders-ts",
    globs: ["scripts/lint-ratchet/registry-builders.ts"],
    files: "1 .ts",
    normalLint: { covered: true },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json`",
    proposed: "none — typed registry builders keep ratchet family options centralized",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-logs-audit-ts",
    globs: [
      "scripts/logs-audit.ts",
      "scripts/logs-audit/logs-audit-*.ts",
      "scripts/logs-audit/logs-audit.test.ts",
    ],
    files: "14 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default; fixtures excluded" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed:
      "none — normal lint enforces the full rule surface; production files are under the normal max-300 cap",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-drift-triage-triage-report-ts",
    globs: [
      "scripts/drift-triage/triage-report.ts",
      "scripts/drift-triage/triage-report-contracts.ts",
      "scripts/drift-triage/triage-report-drift-input.ts",
      "scripts/drift-triage/triage-report-input.ts",
      "scripts/drift-triage/triage-report-summary.ts",
      "scripts/drift-triage/triage-report-support.ts",
      "scripts/drift-triage/triage-report-text.ts",
      "scripts/drift-triage/triage-report-types.ts",
      "scripts/drift-triage/triage-report.test.ts",
      "scripts/drift-triage/triage-report-swarm-prep.test.ts",
      "scripts/drift-triage/triage-item-id.ts",
      "scripts/drift-triage/triage-location.ts",
      "scripts/drift-triage/triage-packet-types.ts",
      "scripts/drift-triage/triage-packet-select.ts",
      "scripts/drift-triage/triage-packet-group.ts",
      "scripts/drift-triage/triage-packet-staleness.ts",
      "scripts/drift-triage/triage-packets.ts",
      "scripts/drift-triage/triage-packets.test.ts",
      "scripts/drift-triage/triage-verdict-types.ts",
      "scripts/drift-triage/triage-verdict-input.ts",
      "scripts/drift-triage/triage-verdict-collect.ts",
      "scripts/drift-triage/triage-verdict-collect.test.ts",
      "scripts/drift-triage/triage-verdict-text.ts",
    ],
    files: "23 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json`",
    proposed:
      "none — focused reducer, packet, and collector coverage pins exact locations, completeness semantics, filtering, deterministic ownership, strict verdict contracts, recovery, and second-pass selection",
    status: ["linted", "ratcheted"],
    followUp:
      "Runtime parsing accepts only complete drift/advisory reports; swarm packets are post-merge, and verdict collection rejects ownership/canonical conflicts while reporting missing work.",
  },
];
