import type { CoverageEntry } from "./lint-coverage-map-manifest-schema.js";

export const ratchetRuntimeScriptEntries: readonly CoverageEntry[] = [
  {
    id: "scripts-lint-ratchet-cli",
    globs: ["scripts/lint-ratchet.ts", "scripts/lint-ratchet.entry.test.ts"],
    files: "2 .ts (ratchet runner CLI + entry classification test)",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed: "none — normal lint owns the runtime complexity floor",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-lint-ratchet-modules",
    globs: ["scripts/lint-ratchet/*.ts"],
    files:
      "47 .ts (the Musi adapter runtime, registry, CLI, harness wiring, and binding/integration adapter tests; portable engine code lives in `@musi/lint-ratchet`)",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed: "none — normal lint owns the helper-module floors",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-lint-ratchet-output-ts",
    globs: ["scripts/lint-ratchet/output.ts"],
    files: "1 .ts (diagnostics output helper)",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed: "none — normal lint owns the runtime-helper floors",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-harness-harness-diagnostics-output-ts",
    globs: ["scripts/harness/harness-diagnostics-output.ts"],
    files:
      "1 .ts (the envelope emission kernel: schema-validates every envelope, then routes it `stdout-only`/`sidecar-only`/`stdout-and-sidecar`/`output-path`; owns the `HARNESS_DIAGNOSTICS_OUTPUT` sidecar path for every producer)",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed:
      "none - shared emission kernel behind lint:agent, lint:ratchet, harness-emit-envelope, drift:ai and logs:audit",
    status: ["linted", "ratcheted"],
    followUp:
      "Its `process.env` read is on the process-primitive allowlist: this module IS the `HARNESS_DIAGNOSTICS_OUTPUT` boundary every producer shares.",
  },
  {
    id: "scripts-lint-ratchet-check-registry-ts",
    globs: ["scripts/lint-ratchet/check-registry.ts"],
    files: "1 .ts (registry preflight helper)",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed: "none — normal lint owns the helper floors",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-lint-ratchet-ratchet-manifest-message-ts",
    globs: ["scripts/lint-ratchet/ratchet-manifest-message.ts"],
    files: "1 .ts (shared missing-ratchet manifest formatter)",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed: "none — normal lint enforces runtime complexity and max-lines",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-lint-ratchet-report-ts",
    globs: ["scripts/lint-ratchet/report.ts"],
    files: "1 .ts (diagnostics markdown formatter)",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed: "none — normal lint owns the helper floors",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-lint-ratchet-baseline-test-ts",
    globs: ["scripts/lint-ratchet/baseline.test.ts"],
    files: "1 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets:
      "`ratchet/local-type-assertion-boundary`, `ratchet/vitest-expect-expect-script-tests`, `ratchet/vitest-valid-expect-script-tests`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed: "none — normal lint plus the Vitest option-pinning ratchets are in place",
    status: ["linted", "ratcheted"],
    followUp:
      "Engine-semantics suites live in `tools/lint-ratchet/src/kernel/baseline.test.ts`; this file keeps the Musi-bound envelope, production-ratchet, committed-baseline, and check-baseline assertions.",
  },
  {
    id: "scripts-lint-ratchet-check-registry-test-ts",
    globs: ["scripts/lint-ratchet/check-registry.test.ts"],
    files: "1 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed: "none — focused Vitest coverage exercises the registry preflight helper",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-lint-ratchet-output-tests",
    globs: [
      "scripts/lint-ratchet/output-diagnostics-file.test.ts",
      "scripts/lint-ratchet/output-drift.test.ts",
      "scripts/lint-ratchet/output-emission.test.ts",
      "scripts/lint-ratchet/output-fixture.test-helper.ts",
      "scripts/lint-ratchet/output-propose.test.ts",
      "scripts/lint-ratchet/output-update-collection.test.ts",
      "scripts/lint-ratchet/output-warnings.test.ts",
    ],
    files: "7 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed: "none — focused Vitest suites cover the output contracts in `test:scripts`",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-harness-harness-diagnostics-output-test-ts",
    globs: ["scripts/harness/harness-diagnostics-output.test.ts"],
    files: "1 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed:
      "none - focused Vitest coverage exercises all four emission routes, pre-write validation, verbatim producer-order rendering, and the sidecar writer's unset/empty/valid/invalid/dir-creation/write-failure behavior",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-lint-ratchet-report-test-ts",
    globs: ["scripts/lint-ratchet/report.test.ts"],
    files: "1 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed: "none — focused Vitest coverage exercises the report formatter",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-lint-agent-ts",
    globs: [
      "scripts/lint-agent.ts",
      "scripts/lint-agent-envelope.ts",
      "scripts/lint-agent-envelope.test.ts",
      "scripts/lint-agent-fix-text.ts",
      "scripts/lint-agent-guidance.ts",
    ],
    files:
      "5 .ts (machine-readable lint slice, importable envelope projection, focused unit coverage, fix-text projection helper, and checked non-local guidance overlays)",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed:
      "none — normal lint enforces the full rule surface; envelope tests pin parser-error, repair-command, CLI argument, ordering, overlay, and pass-through contracts",
    status: ["linted", "ratcheted"],
    followUp: "Production files remain under the normal max-lines cap.",
  },
  {
    id: "scripts-harness-check-ts",
    globs: [
      "scripts/harness-check.ts",
      "scripts/harness/harness-check-validation.ts",
      "scripts/harness/fixture-closure-check.ts",
      "scripts/harness/harness-gate-parity.ts",
      "scripts/harness/hook-timeout-constants.ts",
      "scripts/harness/local-rule-config.ts",
      "scripts/harness/porting-knob-parity.ts",
      "scripts/harness/porting-knob-parity.test.ts",
      "scripts/harness/pre-push-scope-trigger.ts",
      "scripts/harness/pre-push-scope-trigger.test.ts",
    ],
    files: "10 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed: "none — normal lint enforces the full rule surface, including the max-300 cap",
    status: ["linted", "ratcheted"],
    followUp:
      "`local-rule-config.ts` owns local-rule discovery; `harness-gate-parity.ts` owns package-script/CI gate parity; `porting-knob-parity.ts` pins the Porting This checklist; `pre-push-scope-trigger.ts` renders the near-duplicates boundary trigger from the scanner's extensions.",
  },
  {
    id: "scripts-lint-coverage-map-check-eslint-reach-findings-io-row-consistency-scope-suggest-types-ts",
    globs: [
      "scripts/lint-coverage-map-check{,-eslint-reach,-findings,-io,-row-consistency,-scope,-suggest,-types}.ts",
    ],
    files: "8 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed: "none — the checker helpers stay below the normal max-lines cap",
    status: ["linted", "ratcheted"],
    followUp:
      "Future growth should split by concern instead of restoring per-file suppressions. `-suggest` builds scaffold manifest entries; `-row-consistency` holds the ratchet-membership check; `-scope` decides which tracked files the map must account for.",
  },
  {
    id: "scripts-lint-coverage-map-check-test-ts",
    globs: [
      "scripts/lint-coverage-map-check.test.ts",
      "scripts/lint-coverage-map-check-suggest.test.ts",
      "scripts/lint-coverage-map-manifest-schema.test.ts",
    ],
    files: "3 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets:
      "`ratchet/local-type-assertion-boundary`, `ratchet/vitest-expect-expect-script-tests`, `ratchet/vitest-valid-expect-script-tests`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed: "none — normal lint plus bounded-debt ratchets are in place",
    status: ["linted", "ratcheted"],
    followUp: "Deeper-rule work follows the ordinary lint/ratchet lifecycle.",
  },
  {
    id: "scripts-lint-coverage-map-gen-ts",
    globs: [
      "scripts/lint-coverage-map-gen.ts",
      "scripts/lint-coverage-map-gen-core.ts",
      "scripts/lint-coverage-map-gen-core.test.ts",
    ],
    files: "3 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed:
      "none — focused renderer and derivation coverage pins the document template, the table shape, and the derived drift-ai row contract",
    status: ["linted", "ratcheted"],
    followUp:
      "Pure core for the lint coverage-map generator: it renders the whole document from the typed manifest, so the Markdown has no hand-maintained span left.",
  },
  {
    id: "scripts-lint-coverage-map-manifest",
    globs: [
      "scripts/lint-coverage-map-manifest{,-codemods,-config-files,-config-sensors,-docs,-drift-ai,-harness-scripts,-lint-rules-and-shell,-linted-scripts-a,-linted-scripts-b,-misc,-packages,-portable-tooling,-prose,-ratchet-runtime,-schema,-script-entrypoints,-script-fixtures,-sections}.ts",
    ],
    files: "19 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed:
      "none — the typed policy manifest, its Zod contract, and the per-area entry modules stay below the normal max-lines cap",
    status: ["linted", "ratcheted"],
    followUp:
      "Typed source of truth for the coverage rows below; `-schema.ts` owns the Zod contract, `-sections.ts` the document skeleton, `-prose.ts` the static narrative sections, and each `-<area>.ts` module one reviewable slice of the row data. Split an area module rather than raising its cap.",
  },
  {
    id: "scripts-path-policy-path-policy-ts",
    globs: [
      "scripts/path-policy/path-policy.ts",
      "scripts/path-policy/path-policy-smoke-subjects.ts",
      "scripts/path-policy/path-policy-smoke-subjects-data.ts",
      "scripts/path-policy/**/path-policy-query*.ts",
      "scripts/path-policy/path-policy.test.ts",
      "scripts/path-policy/segment-pattern.ts",
      "scripts/path-policy/segment-pattern.test.ts",
      "scripts/path-policy/generate-smoke-subjects.ts",
      "scripts/path-policy/smoke-subject-headers.ts",
      "scripts/path-policy/smoke-subject-headers.test.ts",
      "scripts/path-policy/smoke-test-files.ts",
      "scripts/path-policy/smoke-test-files.test.ts",
      "scripts/path-policy/fixture-helper-calls.ts",
      "scripts/path-policy/fixture-helper-calls.test.ts",
      "scripts/path-policy/fixture-shell-dependencies.ts",
      "scripts/path-policy/fixture-shell-dependencies.test.ts",
      "scripts/path-policy/fixture-shell-scope.ts",
      "scripts/path-policy/fixture-copy-expressions.ts",
      "scripts/path-policy/fixture-import-closure.ts",
      "scripts/path-policy/fixture-sandbox-model.ts",
      "scripts/path-policy/fixture-seed-statements.ts",
      "scripts/path-policy/fixture-loop-bindings.ts",
      "scripts/path-policy/fixture-seeding-annotations.ts",
    ],
    files: "25 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint via `tsconfig.scripts.json` parser override",
    proposed:
      "`path-policy-smoke-subjects-data.ts` carries a `maxLinesPolicy.exceptions` cap (generated lookup table); the rest are under normal lint",
    status: ["linted", "ratcheted"],
    followUp:
      "The family owns the shared path-policy model, NUL-safe shell query interface, generated smoke-subject data, and fixture closure checks for copied shell dependencies and static TS/JS import graphs.",
  },
];
