import type { CoverageEntry } from "./lint-coverage-map-manifest-schema.js";

export const configSensorEntries: readonly CoverageEntry[] = [
  {
    id: "github-workflows-yml",
    globs: [".github/workflows/*.yml"],
    files: "3 .yml",
    normalLint: { covered: true, note: "`bun run lint:config-sensors`" },
    ratchets: "actionlint + yamllint floor",
    parser: "`@tktco/node-actionlint@1.6.0`, system `yamllint` (`apt install yamllint`, >=1.29.0)",
    proposed: "none",
    status: ["linted"],
    followUp: "changed-gate relevant",
  },
  {
    id: "github-pull-request-template-md",
    globs: [".github/pull_request_template.md"],
    files: "1 .md",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`not-code` — Markdown template",
    status: ["not-code"],
    followUp: "—",
  },
  {
    id: "yamllint-yml",
    globs: [".yamllint.yml"],
    files: "1 .yml",
    normalLint: { covered: true, note: "`bun run lint:config-sensors`" },
    ratchets: "yamllint floor",
    parser: "system `yamllint` (`apt install yamllint`, >=1.29.0)",
    proposed: "none",
    status: ["linted"],
    followUp: "changed-gate relevant",
  },
  {
    id: "docker-compose-yml",
    globs: ["docker-compose.yml", ".devcontainer/docker-compose.yml"],
    files: "2 .yml",
    normalLint: { covered: true, note: "`bun run lint:config-sensors`" },
    ratchets: "yamllint floor",
    parser: "system `yamllint` (`apt install yamllint`, >=1.29.0)",
    proposed: "none",
    status: ["linted"],
    followUp: "changed-gate relevant",
  },
  {
    id: "codex-skills-agents-openai-yaml",
    globs: [".codex/skills/*/agents/openai.yaml"],
    files: "2 .yaml",
    normalLint: { covered: true, note: "`bun run lint:config-sensors`" },
    ratchets: "yamllint floor",
    parser: "system `yamllint` (`apt install yamllint`, >=1.29.0)",
    proposed: "none",
    status: ["linted"],
    followUp: "changed-gate relevant",
  },
  {
    id: "codex-config-toml",
    globs: [".codex/config.toml", "bunfig.toml"],
    files: "2 .toml",
    normalLint: { covered: true, note: "`bun run lint:config-sensors`" },
    ratchets: "taplo fmt-check + lint floor",
    parser: "`@taplo/cli@0.7.0` → Taplo 0.9.0",
    proposed: "none",
    status: ["linted"],
    followUp: "changed-gate relevant",
  },
  {
    id: "devcontainer-devcontainer-json",
    globs: [".devcontainer/devcontainer.json"],
    files: "1 .json (no comments today)",
    normalLint: { covered: true, note: "strict JSON track via `**/*.json`" },
    ratchets: "none",
    parser: "—",
    proposed:
      "if a future edit introduces `//`/`/* */` comments, add `.devcontainer/devcontainer.json` to the jsonc track",
    status: ["linted"],
    followUp: "—",
  },
  {
    id: "devcontainer-dockerfile",
    globs: [".devcontainer/Dockerfile"],
    files: "1",
    normalLint: { covered: true, note: "`bun run lint:config-sensors`" },
    ratchets: "hadolint floor",
    parser:
      "`hadolint@0.4.2` → Hadolint 2.14.0 (`DL3007` ignored for the local refreshed base image tag)",
    proposed: "none",
    status: ["linted"],
    followUp:
      "changed-gate relevant; ignored local `docs/refs/5e-database/Dockerfile` is linted when present with reference-only low-value ignores",
  },
  {
    id: "devcontainer-env-example",
    globs: [".devcontainer/.env.example", ".env.example"],
    files: "2",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`excluded` — example env (no secrets); maintained by hand",
    status: ["excluded"],
    followUp: "—",
  },
  {
    id: "packages-server-prisma-migrations-migration-lock-toml-config-listing",
    globs: ["packages/server/prisma/migrations/migration_lock.toml"],
    files: "1 .toml",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`excluded` — Prisma-managed",
    status: ["excluded"],
    followUp: "(also listed in Production Package Source)",
  },
];
