import type { CoverageEntry } from "./lint-coverage-map-manifest-schema.js";

export const markdownAndDocEntries: readonly CoverageEntry[] = [
  {
    id: "docs",
    globs: ["docs/**/*"],
    files: "961 (mostly .md, plus JSON/MJS audit artifacts and the SRD PDF)",
    normalLint: { covered: false, note: "`docs/` in global ignores" },
    ratchets: "none",
    parser: "—",
    proposed:
      "`not-code` for the docs themselves; a narrow doc-length **advisory** (never a commit blocker) covers only specific files — `AGENTS.md`, `CLAUDE.md`, `DECISIONS.md`, `decisions-*.md`, `agent_notes/README.md`, `finished_work/README.md`, `in_progress/*.md` — not `docs/agent_notes/` broadly",
    status: ["not-code"],
    followUp:
      "`scripts/doc-length-policy.sh` is the source of truth (advisory-only, file-specific).",
  },
  {
    id: "docs-agent-notes-backlog-harness-review-2026-07-40-trpc-auth-before-persistence-measurement-mjs",
    globs: [
      "docs/agent_notes/backlog/harness-review-2026-07/40-trpc-auth-before-persistence-measurement/*.mjs",
    ],
    files: "3 .mjs",
    normalLint: { covered: false, note: "`docs/` in global ignores" },
    ratchets: "none",
    parser: "Node + ESLint Node API, invoked manually only",
    proposed:
      "`excluded` — archival measurement artifacts intentionally not imported by the local ESLint plugin, lint configs, ratchets, or harness manifest",
    status: ["excluded"],
    followUp:
      "Reproduction commands live in the adjacent README. Keep this unwired unless the measurement is explicitly reopened with a new rule design.",
  },
  {
    id: "readme-md",
    globs: [
      "README.md",
      "AGENTS.md",
      "CLAUDE.md",
      "CONTEXT.md",
      "DESIGN.md",
      "MODULE-INDEX.md",
      "packages/**/MODULE.md",
      "**/*MODULE.md",
      "packages/**/README.md",
    ],
    files:
      "root guidance docs + 33 client + 13 server + 3 shared MODULE docs + 1 nested package README",
    filesCountNote:
      "a narrative breakdown by kind, not a total: the leading term names the root guidance docs rather than counting them.",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`not-code` — Markdown guidance; module-index sensor validates per-module structure",
    status: ["not-code"],
    followUp: "`scripts/generate-module-index.sh` + `module:index:check` is the structural sensor",
  },
  {
    id: "notice-md",
    globs: ["NOTICE.md"],
    files: "1 .md",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed:
      "`not-code` — root source license, SRD attribution, and third-party notice for public distribution",
    status: ["not-code"],
    followUp: "—",
  },
  {
    id: "claude-skills-md",
    globs: [".claude/skills/**/*.md", ".codex/skills/**/*.md"],
    pathNote: "(skill content)",
    files: "38 .md",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`not-code`",
    status: ["not-code"],
    followUp: "—",
  },
  {
    id: "claude-output-styles-cadence-md",
    globs: [".claude/output-styles/cadence.md"],
    files: "1 .md",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed:
      "`not-code` — custom Claude Code output style for concise progress tone; workflow policy lives in `AGENTS.md`",
    status: ["not-code"],
    followUp: "—",
  },
  {
    id: "devcontainer-readme-md",
    globs: [".devcontainer/README.md", ".github/pull_request_template.md"],
    files: "2 .md",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`not-code`",
    status: ["not-code"],
    followUp: "—",
  },
  {
    id: "scripts-readme-md",
    globs: ["scripts/README.md"],
    files: "1 .md",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`not-code` — scripts layout contract",
    status: ["not-code"],
    followUp: "—",
  },
  {
    id: "license",
    globs: ["LICENSE"],
    files: "1",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`not-code` — root source license text",
    status: ["not-code"],
    followUp: "—",
  },
  {
    id: "packages-server-src-seed-data-reference-notice-md",
    globs: ["packages/server/src/seed/data/reference/NOTICE.md"],
    files: "1 .md",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`not-code` — CC-BY-4.0 attribution for the vendored SRD reference data",
    status: ["not-code"],
    followUp: "—",
  },
  {
    id: "packages-server-src-seed-data-notice-md",
    globs: ["packages/server/src/seed/data/NOTICE.md"],
    files: "1 .md",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed:
      "`not-code` — CC-BY-4.0 attribution + modification notice for the Markdown-derived SRD seed data",
    status: ["not-code"],
    followUp: "—",
  },
  {
    id: "docs-srd-cc-v5-2-1-pdf",
    globs: ["docs/SRD_CC_v5.2.1.pdf"],
    files: "1 .pdf",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`not-code`",
    status: ["not-code"],
    followUp: "—",
  },
];
