import type { CoverageEntry } from "./lint-coverage-map-manifest-schema.js";

export const codemodEntries: readonly CoverageEntry[] = [
  {
    id: "scripts-codemods-concurrency-guard-ts",
    globs: ["scripts/codemods/concurrency-guard.ts", "scripts/codemods/concurrency-guard/*.ts"],
    files: "14 .ts (12 source files plus 2 co-located tests)",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default; fixtures excluded" },
    ratchets:
      "`ratchet/local-type-assertion-boundary`; tests also use the script-test Vitest floors",
    parser: "ESLint `tsconfig.scripts.json` via the shared script project config",
    proposed:
      "none — normal lint enforces the source complexity and max-lines floors, with focused generator/drift coverage",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-codemods-structured-logging-fix-ts",
    globs: [
      "scripts/codemods/structured-logging-fix.ts",
      "scripts/codemods/structured-logging-fix-transforms.ts",
      "scripts/codemods/structured-logging-fix-ast.ts",
    ],
    files: "3 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default; fixtures excluded" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json` via the shared script project config",
    proposed: "none — normal lint enforces the codemod source complexity and max-lines floors",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-codemods-expand-barrel-ts",
    globs: ["scripts/codemods/expand-barrel.ts", "scripts/codemods/expand-barrel/*.ts"],
    files: "13 .ts (facade and split helpers)",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default; fixtures excluded" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json` via the shared script project config",
    proposed: "none — normal lint enforces the codemod source complexity and max-lines floors",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-codemods-trpc-shared-input-ts",
    globs: [
      "scripts/codemods/trpc-shared-input.ts",
      "scripts/codemods/trpc-shared-input-candidates.ts",
      "scripts/codemods/trpc-shared-output.ts",
      "scripts/codemods/trpc-shared-output-candidates.ts",
    ],
    files: "4 .ts",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default; fixtures excluded" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json` via the shared script project config",
    proposed: "none — normal lint enforces the codemod source complexity and max-lines floors",
    status: ["linted", "ratcheted"],
    followUp: "—",
  },
  {
    id: "scripts-codemods-lib-trpc-shared-schema-ts",
    globs: [
      "scripts/codemods/lib/trpc-shared-schema*.ts",
      "scripts/codemods/lib/trpc-shared-engine.ts",
      "scripts/codemods/lib/trpc-shared-engine-args.ts",
      "scripts/codemods/lib/trpc-shared-engine-types.ts",
    ],
    files:
      "11 .ts (shared codemod helper facade and split helpers plus the input/output codemod engine, its CLI arg parser, and its config types)",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default; fixtures excluded" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json` via the shared script project config",
    proposed: "none — normal lint enforces the codemod source complexity and max-lines floors",
    status: ["linted", "ratcheted"],
    followUp: "The shared input/output engine is the common implementation seam.",
  },
  {
    id: "scripts-codemods-lib-walk-ts-files-ts",
    globs: ["scripts/codemods/lib/walk-ts-files.ts", "scripts/codemods/lib/walk-ts-files.test.ts"],
    files: "2 .ts (shared recursive .ts directory walker and its unit test)",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default; fixtures excluded" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json` via the shared script project config",
    proposed: "none — normal lint enforces the codemod source complexity and max-lines floors",
    status: ["linted", "ratcheted"],
    followUp: "The four codemod path modules share this walker.",
  },
  {
    id: "scripts-codemods-lib-codemod-core-ts",
    globs: [
      "scripts/codemods/lib/codemod-errors.ts",
      "scripts/codemods/lib/codemod-imports.ts",
      "scripts/codemods/lib/codemod-project.ts",
      "scripts/codemods/lib/codemod-writes.ts",
    ],
    files: "4 .ts (shared codemod error, import, project, and write orchestration helpers)",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default; fixtures excluded" },
    ratchets: "`ratchet/local-type-assertion-boundary`",
    parser: "ESLint `tsconfig.scripts.json` via the shared script project config",
    proposed: "none — normal lint enforces the codemod source complexity and max-lines floors",
    status: ["linted", "ratcheted"],
    followUp: "Neutral helpers are imported directly by each codemod family.",
  },
  {
    id: "scripts-codemods-concurrency-guard-test-ts",
    globs: [
      "scripts/codemods/concurrency-guard.test.ts",
      "scripts/codemods/expand-barrel.test.ts",
      "scripts/codemods/structured-logging-fix.test.ts",
      "scripts/codemods/trpc-shared-schema-codemod.test.ts",
      "scripts/codemods/lib/fixture-runner.test-helper.ts",
      "scripts/codemods/lib/fixture-runner.test-helper.test.ts",
    ],
    files: "6 .ts (test harness + shared fixture-runner helper and its unit test)",
    normalLint: { covered: true, note: "`scripts/**/*.ts` default; fixtures excluded" },
    ratchets:
      "`ratchet/local-type-assertion-boundary`; normal ESLint enforces `@typescript-eslint/no-misused-promises`, `@typescript-eslint/only-throw-error`, `vitest/expect-expect`, and `vitest/valid-expect`",
    parser: "ESLint `tsconfig.scripts.json` via the shared script project config",
    proposed: "none — bug-class rules live in normal lint",
    status: ["linted", "ratcheted"],
    followUp: "The tests share the fixture-runner scaffold.",
  },
  {
    id: "scripts-codemods-tsconfig-json",
    globs: ["scripts/codemods/tsconfig.json"],
    files: "1 .json",
    normalLint: { covered: true, note: "jsonc track" },
    ratchets: "none",
    parser: "`@eslint/json`",
    proposed: "none — parser-project config is linted as JSONC, not TypeScript source",
    status: ["linted"],
    followUp: "—",
  },
  {
    id: "scripts-codemods-fixtures",
    globs: ["scripts/codemods/fixtures/**/*"],
    files: "358 mixed .ts/.json",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`excluded` — synthesized before/after test inputs, not live code",
    status: ["excluded"],
    followUp:
      "Targeted `scripts/codemods/fixtures/**` ignore keeps these snapshots out of ESLint and ratchets.",
  },
];
