import type { CoverageEntry } from "./lint-coverage-map-manifest-schema.js";

export const rootAndPackageConfigEntries: readonly CoverageEntry[] = [
  {
    id: "eslint-flat-config",
    globs: ["eslint.config.js"],
    files: "1 .js",
    normalLint: { covered: true, note: "exact re-include from `**/*.config.*`" },
    ratchets: "normal ESLint dedicated root JS config block",
    parser: "Espree",
    proposed:
      "JS recommended + `no-unused-vars`; JSDoc deferred because `eslint-plugin-jsdoc` is not a dependency",
    status: ["linted"],
    followUp: "—",
  },
  {
    id: "eslint-config-support-modules",
    globs: ["eslint-config/*.js"],
    files: "21 .js",
    normalLint: { covered: true, note: "ESLint config support modules" },
    ratchets: "normal ESLint config blocks",
    parser:
      "Espree; all except `local-plugin.generated.js` also use the standalone `tsconfig.eslint-js.json` checkJs lane",
    proposed: "JS recommended + `no-unused-vars`",
    status: ["linted"],
    followUp:
      "`config-surfaces.js` loads the config-surface manifest; `restricted-syntax-builder.js` and `restricted-syntax-policy.js` own additive `no-restricted-syntax` composition. `scripts/*.ts` consumers bind to this JSDoc directly through `allowJs`.",
  },
  {
    id: "commitlint-config-js",
    globs: ["commitlint.config.js"],
    files: "1 .js",
    normalLint: { covered: true, note: "exact re-include from `**/*.config.*`" },
    ratchets: "normal ESLint dedicated root JS config block",
    parser: "Espree",
    proposed:
      "JS recommended + `no-unused-vars`; JSDoc deferred because `eslint-plugin-jsdoc` is not a dependency",
    status: ["linted"],
    followUp: "—",
  },
  {
    id: "knip-config-ts",
    globs: ["knip.config.ts", "playwright.config.ts", "vitest.config.ts", "vitest.slow.config.ts"],
    files: "4 root .ts",
    normalLint: { covered: true, note: "exact re-include from `**/*.config.*`" },
    ratchets: "normal ESLint TS config block",
    parser: "typescript-eslint project service via `tsconfig.configs.json` default project",
    proposed: "strict-tier minus `local/max-lines`; config files are process/env boundaries",
    status: ["linted"],
    followUp: "—",
  },
  {
    id: "stryker-config-mjs",
    globs: [
      "stryker.config.mjs",
      "stryker.config.server.mjs",
      "stryker.shared.mjs",
      "scripts/stryker-scripts.mjs",
      "tools/stryker-lint-ratchet.mjs",
    ],
    files: "5 .mjs",
    normalLint: { covered: true, note: "config-surface manifest exact re-includes" },
    ratchets: "normal ESLint dedicated root JS config block",
    parser: "Espree",
    proposed:
      "JS recommended + `no-unused-vars`; JSDoc deferred because `eslint-plugin-jsdoc` is not a dependency",
    status: ["linted"],
    followUp: "Shared factory plus four Stryker mutation lane entrypoints.",
  },
  {
    id: "packages-client-vite-config-ts",
    globs: [
      "packages/client/vite.config.ts",
      "packages/client/vitest.config.ts",
      "packages/server/vitest.config.ts",
      "packages/server/vitest.mutation.config.ts",
      "packages/server/vitest.unit.config.ts",
      "packages/server/prisma.config.ts",
      "packages/shared/vitest.config.ts",
    ],
    files: "7 .ts",
    normalLint: { covered: true, note: "exact re-include from `**/*.config.*`" },
    ratchets: "normal ESLint TS config block",
    parser: "typescript-eslint project service via `tsconfig.configs.json` default project",
    proposed: "strict-tier minus `local/max-lines`; config files are process/env boundaries",
    status: ["linted"],
    followUp:
      "`vitest.mutation.config.ts` is the Stryker-only server scope project (`stryker.config.server.mjs`), in the typed-lint config set and `tsconfig.configs.json` like its siblings",
  },
  {
    id: "scripts-vitest-config-ts",
    globs: ["scripts/vitest.config.ts", "eslint-rules/vitest.config.ts"],
    files: "2 .ts",
    normalLint: {
      covered: true,
      note: "exact config-file re-includes; `scripts/vitest.config.ts` stays out of the runtime-script project",
    },
    ratchets: "normal ESLint TS config block",
    parser: "typescript-eslint project service via `tsconfig.configs.json` default project",
    proposed:
      "strict-tier minus `local/max-lines`; both are active Vitest project configs per `vitest.config.ts`",
    status: ["linted"],
    followUp: "—",
  },
  {
    id: "tsconfig-json",
    globs: [
      "tsconfig.json",
      "tsconfig.base.json",
      "tsconfig.configs.json",
      "tsconfig.e2e.json",
      "tsconfig.eslint-js.json",
      "tsconfig.scripts.json",
    ],
    files: "6 root .json",
    normalLint: { covered: true, note: "jsonc track" },
    ratchets: "none",
    parser: "—",
    proposed:
      "none — `@eslint/json` covers no-duplicate-keys/etc.; `tsconfig.configs.json` is generated from `eslint-config/config-surface-manifest.json` by `bun run harness:config-surfaces`; `tsconfig.eslint-js.json` is the checkJs gate over `eslint-config/*.js` except `local-plugin.generated.js`, and `tsconfig.e2e.json` is the `e2e/**` type gate",
    status: ["linted"],
    followUp: "—",
  },
  {
    id: "packages-client-server-shared-tsconfig-json",
    globs: [
      "packages/{client,server,shared}/tsconfig*.json",
      "packages/server/tsconfig.scripts.json",
    ],
    files: "4 .json",
    normalLint: { covered: true, note: "jsonc track" },
    ratchets: "none",
    parser: "—",
    proposed: "none",
    status: ["linted"],
    followUp: "—",
  },
  {
    id: "package-json",
    globs: [
      "package.json",
      "packages/{client,server,shared}/package.json",
      "packages/client/components.json",
    ],
    files: "5 .json",
    normalLint: { covered: true, note: "`@eslint/json` strict track" },
    ratchets: "none",
    parser: "—",
    proposed:
      "none — `@eslint/json` is the current floor; no additional package-manifest sensor is scheduled",
    status: ["linted"],
    followUp: "—",
  },
  {
    id: "drift-ai-config-json",
    globs: [
      "drift-ai.config.json",
      "drift-ai.config.example.json",
      "semgrep-rules.example.json",
      "harness.controls.json",
      "harness.controls.lint-rules.generated.json",
      "schemas/harness.controls.schema.json",
      "suppression-ledger.json",
      "eslint-config/config-surface-manifest.json",
      "lint-ratchet.baseline.json",
      "sensor-knip-unused-exports.baseline.json",
      "sensor-near-duplicates.baseline.json",
      "eslint-config/max-lines-exceptions.baseline.json",
      "eslint-rules/restricted-syntax-resolution.snapshot.json",
      "eslint-rules/concurrency-guard-direct-corpus.json",
      "eslint-rules/concurrency-guard-nested-corpus.json",
    ],
    files: "15 .json",
    normalLint: { covered: true },
    ratchets: "none",
    parser: "—",
    proposed:
      "none — `@eslint/json` covers structural correctness; `config-surface-manifest.json` single-sources root/package config registration for shared ESLint policy, `tsconfig.configs.json`, and coverage-map status checking; generated baselines hold ratcheted debt/cap identities; `restricted-syntax-resolution.snapshot.json` pins resolved `no-restricted-syntax` composition, `suppression-ledger.json` holds the tree's suppression-directive identities, and the two concurrency corpora pin direct- and nested-write lint behavior; `harness.controls.lint-rules.generated.json` is the generated lint-rule control include merged by `scripts/harness/harness-manifest.ts`, and `schemas/harness.controls.schema.json` is the published JSON Schema projected from that manifest's Zod contract",
    status: ["linted"],
    followUp: "—",
  },
  {
    id: "claude-settings-json",
    globs: [
      ".claude/settings.json",
      ".codex/hooks.json",
      ".github/hooks/copilot.json",
      ".playwright/cli.config.json",
      ".cursor/cli.json",
    ],
    files: "5 .json",
    normalLint: {
      covered: true,
      note: "`.playwright/cli.config.json` and `.cursor/cli.json` are matched by `**/*.json` since not under any ignore",
    },
    ratchets: "none",
    parser: "—",
    proposed: "none",
    status: ["linted"],
    followUp: "—",
  },
  {
    id: "packages-server-src-seed-data-5e-srd-json",
    globs: [
      "packages/server/src/seed/data/5e-srd-*.json",
      "packages/server/src/seed/data/PROVENANCE.json",
    ],
    files: "5 .json (large Markdown-derived SRD data + its provenance manifest)",
    normalLint: { covered: true },
    ratchets: "none",
    parser: "—",
    proposed:
      "none — strict JSON is enough; semantic checks live in seed pipeline, and the `PROVENANCE.json` checksums are enforced by `seed-derived-provenance.test.ts`",
    status: ["linted"],
    followUp: "—",
  },
  {
    id: "packages-server-src-seed-data-reference-5e-srd-json",
    globs: [
      "packages/server/src/seed/data/reference/5e-SRD-*.json",
      "packages/server/src/seed/data/reference/PROVENANCE.json",
    ],
    files: "16 .json (vendored verbatim SRD 5.2.1 reference data + provenance manifest)",
    normalLint: { covered: true },
    ratchets: "none",
    parser: "—",
    proposed:
      "none — vendored byte-for-byte from pinned upstream (prettier-ignored for checksum integrity); structural JSON validity is enough",
    status: ["linted"],
    followUp: "—",
  },
];
