import type { CoverageEntry } from "./lint-coverage-map-manifest-schema.js";

export const webAssetAndMiscEntries: readonly CoverageEntry[] = [
  {
    id: "packages-client-index-html",
    globs: ["packages/client/index.html"],
    files: "1 .html",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`excluded` — Vite entry HTML; semantic checks happen via Vite/React at build time",
    status: ["excluded"],
    followUp: "—",
  },
  {
    id: "packages-client-src-app-css",
    globs: ["packages/client/src/app.css"],
    files: "1 .css",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`excluded` — Tailwind v4 entry; `prettier --check` covers formatting",
    status: ["excluded"],
    followUp: "—",
  },
  {
    id: "bun-lock",
    globs: ["bun.lock"],
    files: "1",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`not-code` — lockfile",
    status: ["not-code"],
    followUp: "`bun install --frozen-lockfile` in CI is the integrity check",
  },
  {
    id: "lint-ratchet-debt-log-jsonl",
    globs: ["lint-ratchet.debt-log.jsonl"],
    files: "1 .jsonl",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`not-code` — append-only ratchet debt history consumed by the debt-log renderer",
    status: ["not-code"],
    followUp: "—",
  },
  {
    id: "gitattributes",
    globs: [
      ".gitattributes",
      ".gitignore",
      ".prettierrc",
      ".prettierignore",
      ".worktreeinclude",
      ".blob-size-allowlist",
    ],
    files: "6",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`excluded` — repo metadata, hand-maintained",
    status: ["excluded"],
    followUp: "—",
  },
  {
    id: "packages-server-gitignore",
    globs: ["packages/server/.gitignore"],
    files: "1",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "—",
    proposed: "`excluded`",
    status: ["excluded"],
    followUp: "—",
  },
  {
    id: "examples-lint-ratchet-demo",
    globs: ["examples/lint-ratchet-demo/**"],
    files: "12 tracked files",
    normalLint: { covered: false },
    ratchets: "none",
    parser: "own ratchet gate",
    proposed:
      "`excluded` — workspace consumer of `@musi/lint-ratchet` with its own `eslint.config.js`, `tsconfig`, `package.json`, and `lint:ratchet` gate; the main repo does not lint it (ignored in `eslint-config/base-configs.js`), its own CI smoke does",
    status: ["excluded"],
    followUp:
      "Copyability proof for the public reference; only its two adopter-owned script files remain, and `smoke.sh` exercises the package-owned operational rail via `.github/workflows/lint-ratchet-demo.yml`.",
  },
];
