#!/usr/bin/env bun
// CLI for the max-lines per-file cap exceptions baseline
// (eslint-config/max-lines-exceptions.baseline.json). Default mode checks the
// committed baseline is normalized and framework-valid; --update re-derives the
// summary and re-sorts after a hand edit. eslint-config/max-lines-policy.js reads
// the same JSON directly at config-load time.

import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { forwardMissingMergeDriverWarning } from "@musi/lint-ratchet/git-rail/merge-driver-presence.js";

import { maxLinesPolicy } from "../eslint-config/max-lines-policy.js";
import { writeFileAtomicallySync } from "./lib/atomic-write.js";
import {
  type MaxLinesGeneratedExemptionPolicy,
  maxLinesPolicy as validatedMaxLinesPolicy,
} from "./lib/max-lines-policy.js";
import { isCliEntrypoint, PROCESS_ARGV_USER_ARGS_START } from "./lib/process-argv.js";
import { computeEffectiveLineCount } from "./max-lines-effective-lines.js";
import {
  checkMaxLinesExceptionsBaseline,
  formatMaxLinesExceptionsBaseline,
  type MaxLinesExceptionEntry,
  parseMaxLinesEntriesForUpdate,
  readMaxLinesExceptionsBaseline,
} from "./max-lines-exceptions-core.js";

const DEFAULT_BASELINE_RELATIVE = "eslint-config/max-lines-exceptions.baseline.json";
const CLI_USAGE = "Usage: bun scripts/max-lines-exceptions.ts [--check | --update | --help]";

// Honest about what the framework check alone proves: the JSON is normalized and
// structurally valid. It says nothing about whether each cap still covers its
// file — the per-entry audit below adds that, and ESLint local/max-lines is the
// gate that actually fails on an undersized cap.
const OK_STDOUT = "OK: max-lines exceptions baseline is normalized and framework-valid";

function repoRootFromModule(): string {
  return resolve(dirname(fileURLToPath(import.meta.url)), "..");
}

// The outcome of reading one exception's source file. "missing" is reserved for
// ENOENT — the only case that means a dead entry ESLint can never flag; every
// other failure (EISDIR, EACCES, a transient I/O error) is "unreadable" and must
// not be mistaken for a removable dead entry.
export type SourceRead =
  | { readonly kind: "content"; readonly text: string }
  | { readonly kind: "missing" }
  | { readonly kind: "unreadable"; readonly reason: string };

function readErrorIsEnoent(error: unknown): boolean {
  return error instanceof Error && "code" in error && error.code === "ENOENT";
}

function defaultReadSource(absolutePath: string): SourceRead {
  try {
    return { kind: "content", text: readFileSync(absolutePath, "utf8") };
  } catch (error) {
    if (readErrorIsEnoent(error)) return { kind: "missing" };
    return { kind: "unreadable", reason: error instanceof Error ? error.message : String(error) };
  }
}

// Verify every generator-owned max-lines exemption is still safe to keep. An
// exemption turns the per-file size gate OFF, so it must be unreachable for
// anything a human writes: this returns a hard error (not a warning) when a
// listed path is missing on disk, does not carry its declared generator's "Do
// not edit by hand." header, or still has a redundant cap entry in the baseline.
// The header check ties path→generator so an authored file cannot opt itself out
// even by pasting a header; the explicit allowlist in max-lines-policy.js is the
// primary guard, this is the fail-loud that keeps the allowlist honest.
export function checkGeneratedExemptions(input: {
  readonly exemptions: readonly MaxLinesGeneratedExemptionPolicy[];
  readonly baselineEntries: readonly MaxLinesExceptionEntry[];
  readonly sourceRoot: string;
  readonly readSource: (absolutePath: string) => SourceRead;
}): string | undefined {
  const baselinePaths = new Set(input.baselineEntries.map((entry) => entry.path));
  for (const exemption of input.exemptions) {
    if (baselinePaths.has(exemption.path)) {
      return `${exemption.path} is a generated-file max-lines exemption (eslint-config/max-lines-policy.js) and must not also carry a cap entry in eslint-config/max-lines-exceptions.baseline.json — remove the baseline entry so the file is exempt XOR capped, never both.`;
    }
    const read = input.readSource(resolve(input.sourceRoot, exemption.path));
    if (read.kind !== "content") {
      const detail = read.kind === "missing" ? "no file exists on disk" : read.reason;
      return `generated-file max-lines exemption ${exemption.path} is unreachable (${detail}) — the size gate is skipped for a file that is not there; remove the exemption from eslint-config/max-lines-policy.js or restore the generated output.`;
    }
    const header = `Generated by ${exemption.generator}. Do not edit by hand.`;
    if (!read.text.includes(header)) {
      return `generated-file max-lines exemption ${exemption.path} does not carry its generator header ("${header}") — the max-lines cap is only skipped for generator-owned files, so an authored file cannot opt itself out.`;
    }
  }
  return undefined;
}

type EntryAudit = {
  readonly detailWarnings: readonly string[];
  readonly summaryLines: readonly string[];
};

// Compare every committed cap against the file's live effective line count,
// counted through the same code path ESLint uses (max-lines-effective-lines).
// A cap below the current count means ESLint local/max-lines is already failing
// this run; an ENOENT-missing file means a dead entry ESLint can never flag; an
// otherwise-unreadable file means the cap could not be checked at all. All three
// are warnings only — this validator never fails on them (ESLint owns the cap
// gate); its job is to stop reporting an unqualified OK while any is true.
function auditEntryCaps(input: {
  readonly entries: readonly MaxLinesExceptionEntry[];
  readonly sourceRoot: string;
  readonly readSource: (absolutePath: string) => SourceRead;
}): EntryAudit {
  const counting = maxLinesPolicy.counting;
  const detailWarnings: string[] = [];
  let capBelow = 0;
  let missing = 0;
  let unreadable = 0;

  for (const entry of input.entries) {
    const read = input.readSource(resolve(input.sourceRoot, entry.path));
    if (read.kind === "missing") {
      missing += 1;
      detailWarnings.push(
        `WARN: ${entry.path} has a max-lines exception but no file exists on disk — remove the dead entry (ESLint local/max-lines will never flag it).`,
      );
      continue;
    }
    if (read.kind === "unreadable") {
      unreadable += 1;
      detailWarnings.push(
        `WARN: ${entry.path} could not be read (${read.reason}) — its cap was not checked; fix access or remove the entry if the file is gone.`,
      );
      continue;
    }
    const effective = computeEffectiveLineCount(entry.path, read.text, counting);
    if (effective !== undefined && effective > entry.cap) {
      capBelow += 1;
      detailWarnings.push(
        `WARN: ${entry.path} cap ${String(entry.cap)} is below its current ${String(effective)} effective lines — raise the cap in eslint-config/max-lines-exceptions.baseline.json (then run 'bun run lint:max-lines-exceptions:update' to normalize) or split the file.`,
      );
    }
  }

  const summaryLines: string[] = [];
  if (capBelow > 0) {
    summaryLines.push(
      `WARN: ${String(capBelow)} cap(s) below current effective lines — ESLint local/max-lines will fail on these files.`,
    );
  }
  if (missing > 0) {
    summaryLines.push(
      `WARN: ${String(missing)} exception path(s) missing on disk — remove the dead entr${missing === 1 ? "y" : "ies"}.`,
    );
  }
  if (unreadable > 0) {
    summaryLines.push(
      `WARN: ${String(unreadable)} exception path(s) could not be read — their caps were not checked.`,
    );
  }
  return { detailWarnings, summaryLines };
}

export type MaxLinesExceptionsCliResult = {
  readonly exitCode: number;
  readonly stdout: string;
};

export type RunMaxLinesExceptionsCliOptions = {
  readonly argv: readonly string[];
  readonly baselinePath: string;
  readonly cwd?: string;
  readonly env?: NodeJS.ProcessEnv;
  readonly warn?: (message: string) => void;
  readonly sourceRoot?: string;
  readonly readSource?: (absolutePath: string) => SourceRead;
  // The generator-owned exemption allowlist to guard. Defaults to empty so the
  // pure CLI never reaches into production state on its own; the real entrypoint
  // wires the validated `maxLinesPolicy.generatedExemptions`, and tests pass a
  // fixture list explicitly.
  readonly generatedExemptions?: readonly MaxLinesGeneratedExemptionPolicy[];
};

type CliMode = "check" | "update" | "help";

function parseCliMode(argv: readonly string[]): CliMode | undefined {
  if (argv.length === 0) return "check";
  if (argv.length !== 1) return undefined;
  if (argv[0] === "--check") return "check";
  if (argv[0] === "--update") return "update";
  if (argv[0] === "--help") return "help";
  return undefined;
}

// The missing-merge-driver probe is a courtesy warning; skip it entirely when no
// observer is wired (tests that omit `warn`), matching the pre-audit behavior.
function forwardMergeDriverWarningIfObserved(options: RunMaxLinesExceptionsCliOptions): void {
  if (options.warn === undefined) return;
  forwardMissingMergeDriverWarning({
    checkScriptPath: resolve(import.meta.dirname, "git/check-max-lines-exceptions-merge-driver.sh"),
    cwd: options.cwd ?? process.cwd(),
    env: options.env ?? {},
    warn: options.warn,
  });
}

// Attach the per-entry cap/dead-entry audit to a successful result. Both the
// per-entry detail lines AND the scope summary go through the observer (stderr),
// never stdout: a caller that redirects stderr must not find warning text mixed
// into the nominal success output. stdout stays exactly the base result line and
// the exit code stays 0 — ESLint local/max-lines is the gate that fails.
function withAudit(
  options: RunMaxLinesExceptionsCliOptions,
  baseStdout: string,
  entries: readonly MaxLinesExceptionEntry[],
): MaxLinesExceptionsCliResult {
  const audit = auditEntryCaps({
    entries,
    sourceRoot: options.sourceRoot ?? resolve(dirname(options.baselinePath), ".."),
    readSource: options.readSource ?? defaultReadSource,
  });
  if (options.warn !== undefined) {
    for (const warning of audit.detailWarnings) options.warn(warning);
    for (const summary of audit.summaryLines) options.warn(summary);
  }
  return { exitCode: 0, stdout: baseStdout };
}

// Run the generated-exemption guard with the same source resolution the cap
// audit uses, so a listed path is checked against the exact tree ESLint lints.
function guardGeneratedExemptions(
  options: RunMaxLinesExceptionsCliOptions,
  baselineEntries: readonly MaxLinesExceptionEntry[],
): string | undefined {
  return checkGeneratedExemptions({
    exemptions: options.generatedExemptions ?? [],
    baselineEntries,
    sourceRoot: options.sourceRoot ?? resolve(dirname(options.baselinePath), ".."),
    readSource: options.readSource ?? defaultReadSource,
  });
}

export function runMaxLinesExceptionsCli(
  options: RunMaxLinesExceptionsCliOptions,
): MaxLinesExceptionsCliResult {
  const mode = parseCliMode(options.argv);
  if (mode === undefined) return { exitCode: 2, stdout: `ERROR: invalid arguments\n${CLI_USAGE}` };
  if (mode === "help") return { exitCode: 0, stdout: CLI_USAGE };
  const { baselinePath } = options;

  forwardMergeDriverWarningIfObserved(options);

  if (!existsSync(baselinePath)) {
    return {
      exitCode: 2,
      stdout: `ERROR: baseline missing at ${baselinePath}; restore eslint-config/max-lines-exceptions.baseline.json`,
    };
  }
  const text = readFileSync(baselinePath, "utf8");

  if (mode === "update") {
    const parsed = parseMaxLinesEntriesForUpdate(text);
    if (!parsed.ok) return { exitCode: 2, stdout: `ERROR: ${parsed.error}` };
    const exemptionError = guardGeneratedExemptions(options, parsed.value);
    if (exemptionError !== undefined) return { exitCode: 2, stdout: `ERROR: ${exemptionError}` };
    const formatted = formatMaxLinesExceptionsBaseline(parsed.value);
    writeFileAtomicallySync(baselinePath, formatted);
    return withAudit(
      options,
      `max-lines-exceptions -- normalized ${String(parsed.value.length)} exception(s)`,
      parsed.value,
    );
  }

  const check = checkMaxLinesExceptionsBaseline(text);
  if (!check.ok) return { exitCode: 2, stdout: `ERROR: ${check.error}` };
  const parsed = readMaxLinesExceptionsBaseline(text);
  const entries = parsed.ok ? parsed.value : [];
  const exemptionError = guardGeneratedExemptions(options, entries);
  if (exemptionError !== undefined) return { exitCode: 2, stdout: `ERROR: ${exemptionError}` };
  return withAudit(options, OK_STDOUT, entries);
}

if (isCliEntrypoint(import.meta.url)) {
  const result = runMaxLinesExceptionsCli({
    argv: process.argv.slice(PROCESS_ARGV_USER_ARGS_START),
    baselinePath: resolve(repoRootFromModule(), DEFAULT_BASELINE_RELATIVE),
    cwd: process.cwd(),
    env: process.env,
    generatedExemptions: validatedMaxLinesPolicy.generatedExemptions,
    warn: (message) => {
      console.error(message);
    },
  });
  if (result.stdout) console.log(result.stdout);
  if (result.exitCode !== 0) process.exitCode = result.exitCode;
}
