#!/usr/bin/env bun
// CLI for the max-lines per-file cap exceptions baseline
// (eslint-config/max-lines-exceptions.baseline.json). Default mode checks the
// committed baseline is normalized and framework-valid; --update re-derives the
// summary and re-sorts after a hand edit. eslint-config/max-lines-policy.js reads
// the same JSON directly at config-load time.

import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { forwardMissingMergeDriverWarning } from "@musi/lint-ratchet/git-rail/merge-driver-presence.js";
import { minimatch } from "minimatch";

import { maxLinesPolicy } from "../eslint-config/max-lines-policy.js";
import { writeFileAtomicallySync } from "./lib/atomic-write.js";
import {
  type MaxLinesGeneratedExemptionPolicy,
  maxLinesPolicy as validatedMaxLinesPolicy,
} from "./lib/max-lines-policy.js";
import { isCliEntrypoint, PROCESS_ARGV_USER_ARGS_START } from "./lib/process-argv.js";
import { computeEffectiveLineCount } from "./max-lines-effective-lines.js";
import {
  checkMaxLinesExceptionsBaseline,
  formatMaxLinesExceptionsBaseline,
  type MaxLinesExceptionEntry,
  parseMaxLinesEntriesForUpdate,
  readMaxLinesExceptionsBaseline,
} from "./max-lines-exceptions-core.js";

const DEFAULT_BASELINE_RELATIVE = "eslint-config/max-lines-exceptions.baseline.json";
const CLI_USAGE = "Usage: bun scripts/max-lines-exceptions.ts [--check | --update | --help]";

// Honest about what the framework check alone proves: the JSON is normalized and
// structurally valid. It says nothing about whether each cap still covers its
// file — the per-entry audit below adds that, and ESLint local/max-lines is the
// gate that actually fails on an undersized cap.
const OK_STDOUT = "OK: max-lines exceptions baseline is normalized and framework-valid";

function repoRootFromModule(): string {
  return resolve(dirname(fileURLToPath(import.meta.url)), "..");
}

// The outcome of reading one exception's source file. "missing" is reserved for
// ENOENT — the only case that means a dead entry ESLint can never flag; every
// other failure (EISDIR, EACCES, a transient I/O error) is "unreadable" and must
// not be mistaken for a removable dead entry.
export type SourceRead =
  | { readonly kind: "content"; readonly text: string }
  | { readonly kind: "missing" }
  | { readonly kind: "unreadable"; readonly reason: string };

function readErrorIsEnoent(error: unknown): boolean {
  return error instanceof Error && "code" in error && error.code === "ENOENT";
}

function defaultReadSource(absolutePath: string): SourceRead {
  try {
    return { kind: "content", text: readFileSync(absolutePath, "utf8") };
  } catch (error) {
    if (readErrorIsEnoent(error)) return { kind: "missing" };
    return { kind: "unreadable", reason: error instanceof Error ? error.message : String(error) };
  }
}

// Verify every generator-owned max-lines exemption is still safe to keep. An
// exemption turns the per-file size gate OFF, so it must be unreachable for
// anything a human writes: this returns a hard error (not a warning) when a
// listed path is missing on disk, does not carry its declared generator's "Do
// not edit by hand." header, or still has a redundant cap entry in the baseline.
// The header check ties path→generator so an authored file cannot opt itself out
// even by pasting a header; the explicit allowlist in max-lines-policy.js is the
// primary guard, this is the fail-loud that keeps the allowlist honest.
export function checkGeneratedExemptions(input: {
  readonly exemptions: readonly MaxLinesGeneratedExemptionPolicy[];
  readonly baselineEntries: readonly MaxLinesExceptionEntry[];
  readonly sourceRoot: string;
  readonly readSource: (absolutePath: string) => SourceRead;
}): string | undefined {
  const baselinePaths = new Set(input.baselineEntries.map((entry) => entry.path));
  for (const exemption of input.exemptions) {
    if (baselinePaths.has(exemption.path)) {
      return `${exemption.path} is a generated-file max-lines exemption (eslint-config/max-lines-policy.js) and must not also carry a cap entry in eslint-config/max-lines-exceptions.baseline.json — remove the baseline entry so the file is exempt XOR capped, never both.`;
    }
    const read = input.readSource(resolve(input.sourceRoot, exemption.path));
    if (read.kind !== "content") {
      const detail = read.kind === "missing" ? "no file exists on disk" : read.reason;
      return `generated-file max-lines exemption ${exemption.path} is unreachable (${detail}) — the size gate is skipped for a file that is not there; remove the exemption from eslint-config/max-lines-policy.js or restore the generated output.`;
    }
    const header = `Generated by ${exemption.generator}. Do not edit by hand.`;
    if (!read.text.includes(header)) {
      return `generated-file max-lines exemption ${exemption.path} does not carry its generator header ("${header}") — the max-lines cap is only skipped for generator-owned files, so an authored file cannot opt itself out.`;
    }
  }
  return undefined;
}

type EntryAudit = {
  readonly detailWarnings: readonly string[];
  readonly summaryLines: readonly string[];
};

// The cap a path would get with no baseline entry at all: the engine-zone cap
// for paths matching the lint-ratchet engine globs, otherwise the repo-wide
// ratchet floor. dot:true mirrors how ESLint flat config resolves the same
// `files` globs. Deliberately local — only two zones exist today, so this is
// not worth a public zone-resolution API.
function defaultCapForPath(relativePath: string): number {
  const zone = validatedMaxLinesPolicy.engineZone;
  if (zone.files.some((glob) => minimatch(relativePath, glob, { dot: true }))) return zone.cap;
  return validatedMaxLinesPolicy.ratchetFloor.cap;
}

type CapAuditFinding = {
  readonly kind: "capBelow" | "missing" | "unreadable" | "unneeded";
  readonly warning: string;
};

// Classify one entry against its source read. "unneeded" is deliberately not
// the generated-exemption guard's "redundant cap entry" (an exempt path that
// also carries a baseline entry) — this one compares the cap against the file's
// live line count and fires only when the no-exception default already covers
// it. A cap-below entry is never also reported unneeded.
function auditOneEntryCap(
  entry: MaxLinesExceptionEntry,
  read: SourceRead,
): CapAuditFinding | undefined {
  if (read.kind === "missing") {
    return {
      kind: "missing",
      warning: `WARN: ${entry.path} has a max-lines exception but no file exists on disk — remove the dead entry (ESLint local/max-lines will never flag it).`,
    };
  }
  if (read.kind === "unreadable") {
    return {
      kind: "unreadable",
      warning: `WARN: ${entry.path} could not be read (${read.reason}) — its cap was not checked; fix access or remove the entry if the file is gone.`,
    };
  }
  const effective = computeEffectiveLineCount(entry.path, read.text, maxLinesPolicy.counting);
  if (effective === undefined) return undefined;
  if (effective > entry.cap) {
    return {
      kind: "capBelow",
      warning: `WARN: ${entry.path} cap ${String(entry.cap)} is below its current ${String(effective)} effective lines — raise the cap in eslint-config/max-lines-exceptions.baseline.json (then run 'bun run lint:max-lines-exceptions:update' to normalize) or split the file.`,
    };
  }
  const defaultCap = defaultCapForPath(entry.path);
  // Only a cap above the default can be unneeded: an entry that tightens the
  // cap below its default is load-bearing (removing it would loosen the gate).
  if (entry.cap > defaultCap && effective <= defaultCap) {
    return {
      kind: "unneeded",
      warning: `WARN: ${entry.path} cap ${String(entry.cap)} is unneeded — its ${String(effective)} effective lines are at or under the ${String(defaultCap)}-line default that applies with no exception; remove the entry from eslint-config/max-lines-exceptions.baseline.json (or keep a smaller cap if renewed growth is expected).`,
    };
  }
  return undefined;
}

// Compare every committed cap against the file's live effective line count,
// counted through the same code path ESLint uses (max-lines-effective-lines).
// A cap below the current count means ESLint local/max-lines is already failing
// this run; an ENOENT-missing file means a dead entry ESLint can never flag; an
// otherwise-unreadable file means the cap could not be checked at all; a cap
// whose file has shrunk to at or under its no-exception default is unneeded
// headroom that will never expire on its own. All four are warnings only — this
// validator never fails on them (ESLint owns the cap gate); its job is to stop
// reporting an unqualified OK while any is true.
function auditEntryCaps(input: {
  readonly entries: readonly MaxLinesExceptionEntry[];
  readonly sourceRoot: string;
  readonly readSource: (absolutePath: string) => SourceRead;
}): EntryAudit {
  const detailWarnings: string[] = [];
  const counts = { capBelow: 0, missing: 0, unreadable: 0, unneeded: 0 };

  for (const entry of input.entries) {
    const finding = auditOneEntryCap(
      entry,
      input.readSource(resolve(input.sourceRoot, entry.path)),
    );
    if (finding === undefined) continue;
    counts[finding.kind] += 1;
    detailWarnings.push(finding.warning);
  }

  const summaryLines: string[] = [];
  if (counts.capBelow > 0) {
    summaryLines.push(
      `WARN: ${String(counts.capBelow)} cap(s) below current effective lines — ESLint local/max-lines will fail on these files.`,
    );
  }
  if (counts.missing > 0) {
    summaryLines.push(
      `WARN: ${String(counts.missing)} exception path(s) missing on disk — remove the dead entr${counts.missing === 1 ? "y" : "ies"}.`,
    );
  }
  if (counts.unreadable > 0) {
    summaryLines.push(
      `WARN: ${String(counts.unreadable)} exception path(s) could not be read — their caps were not checked.`,
    );
  }
  if (counts.unneeded > 0) {
    summaryLines.push(
      `WARN: ${String(counts.unneeded)} cap(s) unneeded — effective lines are at or under the default cap; remove the stale entr${counts.unneeded === 1 ? "y" : "ies"}.`,
    );
  }
  return { detailWarnings, summaryLines };
}

export type MaxLinesExceptionsCliResult = {
  readonly exitCode: number;
  readonly stdout: string;
};

export type RunMaxLinesExceptionsCliOptions = {
  readonly argv: readonly string[];
  readonly baselinePath: string;
  readonly cwd?: string;
  readonly env?: NodeJS.ProcessEnv;
  readonly warn?: (message: string) => void;
  readonly sourceRoot?: string;
  readonly readSource?: (absolutePath: string) => SourceRead;
  // The generator-owned exemption allowlist to guard. Defaults to empty so the
  // pure CLI never reaches into production state on its own; the real entrypoint
  // wires the validated `maxLinesPolicy.generatedExemptions`, and tests pass a
  // fixture list explicitly.
  readonly generatedExemptions?: readonly MaxLinesGeneratedExemptionPolicy[];
};

type CliMode = "check" | "update" | "help";

function parseCliMode(argv: readonly string[]): CliMode | undefined {
  if (argv.length === 0) return "check";
  if (argv.length !== 1) return undefined;
  if (argv[0] === "--check") return "check";
  if (argv[0] === "--update") return "update";
  if (argv[0] === "--help") return "help";
  return undefined;
}

// The missing-merge-driver probe is a courtesy warning; skip it entirely when no
// observer is wired (tests that omit `warn`), matching the pre-audit behavior.
function forwardMergeDriverWarningIfObserved(options: RunMaxLinesExceptionsCliOptions): void {
  if (options.warn === undefined) return;
  forwardMissingMergeDriverWarning({
    checkScriptPath: resolve(import.meta.dirname, "git/check-max-lines-exceptions-merge-driver.sh"),
    cwd: options.cwd ?? process.cwd(),
    env: options.env ?? {},
    warn: options.warn,
  });
}

// Attach the per-entry cap/dead-entry audit to a successful result. Both the
// per-entry detail lines AND the scope summary go through the observer (stderr),
// never stdout: a caller that redirects stderr must not find warning text mixed
// into the nominal success output. stdout stays exactly the base result line and
// the exit code stays 0 — ESLint local/max-lines is the gate that fails.
function withAudit(
  options: RunMaxLinesExceptionsCliOptions,
  baseStdout: string,
  entries: readonly MaxLinesExceptionEntry[],
): MaxLinesExceptionsCliResult {
  const audit = auditEntryCaps({
    entries,
    sourceRoot: options.sourceRoot ?? resolve(dirname(options.baselinePath), ".."),
    readSource: options.readSource ?? defaultReadSource,
  });
  if (options.warn !== undefined) {
    for (const warning of audit.detailWarnings) options.warn(warning);
    for (const summary of audit.summaryLines) options.warn(summary);
  }
  return { exitCode: 0, stdout: baseStdout };
}

// Run the generated-exemption guard with the same source resolution the cap
// audit uses, so a listed path is checked against the exact tree ESLint lints.
function guardGeneratedExemptions(
  options: RunMaxLinesExceptionsCliOptions,
  baselineEntries: readonly MaxLinesExceptionEntry[],
): string | undefined {
  return checkGeneratedExemptions({
    exemptions: options.generatedExemptions ?? [],
    baselineEntries,
    sourceRoot: options.sourceRoot ?? resolve(dirname(options.baselinePath), ".."),
    readSource: options.readSource ?? defaultReadSource,
  });
}

export function runMaxLinesExceptionsCli(
  options: RunMaxLinesExceptionsCliOptions,
): MaxLinesExceptionsCliResult {
  const mode = parseCliMode(options.argv);
  if (mode === undefined) return { exitCode: 2, stdout: `ERROR: invalid arguments\n${CLI_USAGE}` };
  if (mode === "help") return { exitCode: 0, stdout: CLI_USAGE };
  const { baselinePath } = options;

  forwardMergeDriverWarningIfObserved(options);

  if (!existsSync(baselinePath)) {
    return {
      exitCode: 2,
      stdout: `ERROR: baseline missing at ${baselinePath}; restore eslint-config/max-lines-exceptions.baseline.json`,
    };
  }
  const text = readFileSync(baselinePath, "utf8");

  if (mode === "update") {
    const parsed = parseMaxLinesEntriesForUpdate(text);
    if (!parsed.ok) return { exitCode: 2, stdout: `ERROR: ${parsed.error}` };
    const exemptionError = guardGeneratedExemptions(options, parsed.value);
    if (exemptionError !== undefined) return { exitCode: 2, stdout: `ERROR: ${exemptionError}` };
    const formatted = formatMaxLinesExceptionsBaseline(parsed.value);
    writeFileAtomicallySync(baselinePath, formatted);
    return withAudit(
      options,
      `max-lines-exceptions -- normalized ${String(parsed.value.length)} exception(s)`,
      parsed.value,
    );
  }

  const check = checkMaxLinesExceptionsBaseline(text);
  if (!check.ok) return { exitCode: 2, stdout: `ERROR: ${check.error}` };
  const parsed = readMaxLinesExceptionsBaseline(text);
  const entries = parsed.ok ? parsed.value : [];
  const exemptionError = guardGeneratedExemptions(options, entries);
  if (exemptionError !== undefined) return { exitCode: 2, stdout: `ERROR: ${exemptionError}` };
  return withAudit(options, OK_STDOUT, entries);
}

if (isCliEntrypoint(import.meta.url)) {
  const result = runMaxLinesExceptionsCli({
    argv: process.argv.slice(PROCESS_ARGV_USER_ARGS_START),
    baselinePath: resolve(repoRootFromModule(), DEFAULT_BASELINE_RELATIVE),
    cwd: process.cwd(),
    env: process.env,
    generatedExemptions: validatedMaxLinesPolicy.generatedExemptions,
    warn: (message) => {
      console.error(message);
    },
  });
  if (result.stdout) console.log(result.stdout);
  if (result.exitCode !== 0) process.exitCode = result.exitCode;
}
