export type ScriptSmokeSubjects = Record<string, readonly string[]>;

export const SCRIPT_SMOKE_SUBJECTS = {
  "test-verify": [
    "scripts/verify.sh",
    "scripts/verify-metadata.sh",
    "scripts/path-policy-query.ts",
    "scripts/path-policy-query-core.ts",
    "scripts/path-policy.ts",
    "scripts/process-tree.sh",
    "scripts/parallel-step.sh",
    "scripts/test-git-env.sh",
    "scripts/test-verify.sh",
    "scripts/ai-hooks/cache.sh",
    "scripts/ai-hooks/output-filter.sh",
  ],
  "test-verify-async": [
    "scripts/verify-async.sh",
    "scripts/test-verify-async.sh",
    "scripts/process-tree.sh",
    "scripts/verify.sh",
    "scripts/verify-metadata.sh",
    "scripts/ai-hooks/cache.sh",
  ],
  "test-verify-logs": [
    "scripts/verify-logs.sh",
    "scripts/test-verify-logs.sh",
    "scripts/ai-hooks/cache.sh",
    "scripts/ai-hooks/output-filter.sh",
    "scripts/harness-emit-envelope.ts",
    "packages/shared/src/schemas/harness-diagnostics.ts",
  ],
  "test-verify-history": [
    "scripts/verify-history.sh",
    "scripts/test-verify-history.sh",
    "scripts/verify-metadata.sh",
    "scripts/path-policy-query.ts",
    "scripts/path-policy-query-core.ts",
    "scripts/path-policy.ts",
    "scripts/path-policy-smoke-subjects.ts",
    "scripts/test-git-env.sh",
    ".husky/pre-commit",
    "package.json",
  ],
  "test-worktree-db": [
    "scripts/worktree-db.sh",
    "scripts/worktree-new.sh",
    "scripts/worktree-drift-hook.sh",
    "scripts/dev.sh",
    "scripts/test-worktree-db.sh",
  ],
  "test-dependency-freshness": [
    "scripts/dependency-freshness.sh",
    "scripts/prisma-client-freshness.sh",
    "scripts/doc-length-policy.sh",
    "scripts/verify-metadata.sh",
    "scripts/process-tree.sh",
    "scripts/ai-hooks/output-filter.sh",
    ".husky/pre-commit",
    "scripts/test-git-env.sh",
    "scripts/test-dependency-freshness.sh",
  ],
  "test-ai-hooks": [
    "scripts/test-ai-hooks.sh",
    "scripts/ai-hooks/test.sh",
    "scripts/ai-hooks/common.sh",
    "scripts/ai-hooks/cache.sh",
    "scripts/verify-metadata.sh",
    "scripts/ai-hooks/policy.sh",
    "scripts/ai-hooks/protected-files.sh",
    "scripts/ai-hooks/doc-length.sh",
    "scripts/ai-hooks/tidy-edited-file.sh",
    "scripts/ai-hooks/lint-coverage-check.sh",
    "scripts/ai-hooks/output-filter.sh",
    "scripts/ai-hooks/process-runner.sh",
    "scripts/ai-hooks/commit-output.sh",
    "scripts/ai-hooks/commit-timeout-status.sh",
    "scripts/ai-hooks/stop-policy.sh",
    "scripts/ai-hooks/stop-reminder.sh",
    "scripts/test-git-env.sh",
    ".claude/hooks/",
    ".codex/hooks/pre-tool-use.sh",
    ".codex/hooks/post-tool-use.sh",
    ".codex/hooks/stop-reminder.sh",
    ".codex/hooks/tidy-edited-file.sh",
    ".codex/hooks/lint-coverage-check.sh",
    ".claude/settings.json",
    ".codex/hooks.json",
  ],
  "test-eslint-disable-register": [
    "scripts/eslint-disable-register.sh",
    "scripts/test-git-env.sh",
    "scripts/test-eslint-disable-register.sh",
  ],
  "test-suppression-register": [
    "scripts/suppression-register.sh",
    "scripts/test-git-env.sh",
    "scripts/test-suppression-register.sh",
  ],
  "test-codemod-structured-logging-fix": [
    "scripts/codemods/structured-logging-fix-transforms.ts",
    "scripts/codemods/structured-logging-fix.ts",
    "scripts/codemods/lib/",
    "scripts/test-codemod-structured-logging-fix.sh",
    "package.json",
    "tsconfig.scripts.json",
  ],
  "test-codemod-trpc-shared-input": [
    "scripts/codemods/trpc-shared-input-candidates.ts",
    "scripts/codemods/trpc-shared-input.ts",
    "scripts/codemods/lib/",
    "scripts/test-codemod-trpc-shared-input.sh",
    "package.json",
    "tsconfig.scripts.json",
  ],
  "test-codemod-trpc-shared-output": [
    "scripts/codemods/trpc-shared-output-candidates.ts",
    "scripts/codemods/trpc-shared-output.ts",
    "scripts/codemods/lib/",
    "scripts/test-codemod-trpc-shared-output.sh",
    "package.json",
    "tsconfig.scripts.json",
  ],
  "test-codemod-expand-barrel": [
    "scripts/codemods/expand-barrel.ts",
    "scripts/codemods/expand-barrel/",
    "scripts/codemods/lib/",
    "scripts/codemods/fixtures/expand-barrel/",
    "scripts/test-codemod-expand-barrel.sh",
    "package.json",
    "tsconfig.scripts.json",
  ],
  "test-codemod-concurrency-guard": [
    "scripts/codemods/concurrency-guard.ts",
    "scripts/codemods/concurrency-guard/",
    "scripts/codemods/lib/",
    "scripts/codemods/fixtures/concurrency-guard/",
    "scripts/test-codemod-concurrency-guard.sh",
    "package.json",
    "tsconfig.scripts.json",
  ],
  "test-code-intel": [
    "scripts/code-intel.ts",
    "scripts/code-intel-server.ts",
    "scripts/code-intel/",
    "scripts/code-intel.test.ts",
    "scripts/test-code-intel.sh",
    "scripts/vitest.config.ts",
    "package.json",
    "tsconfig.scripts.json",
    "packages/shared/package.json",
    "packages/server/package.json",
    "packages/client/tsconfig.json",
  ],
  "test-format-changed": [
    ".prettierignore",
    ".prettierrc",
    "scripts/format-changed.sh",
    "scripts/path-policy-query.ts",
    "scripts/path-policy-query-core.ts",
    "scripts/path-policy.ts",
    "scripts/path-policy-smoke-subjects.ts",
    "scripts/test-git-env.sh",
    "scripts/test-format-changed.sh",
  ],
  "test-lint-changed": [
    "scripts/lint-changed.sh",
    "scripts/lint-shell.sh",
    "scripts/parallel-runner.sh",
    "scripts/verify-metadata.sh",
    "scripts/path-policy-query.ts",
    "scripts/path-policy-query-core.ts",
    "scripts/path-policy.ts",
    "scripts/test-git-env.sh",
    "scripts/test-lint-changed.sh",
    "eslint-config/",
  ],
  "test-lint-shell": [
    "scripts/lint-shell.sh",
    "scripts/parallel-runner.sh",
    "scripts/path-policy-query.ts",
    "scripts/path-policy-query-core.ts",
    "scripts/path-policy.ts",
    "scripts/test-git-env.sh",
    "scripts/test-lint-shell.sh",
    "package.json",
    "bun.lock",
  ],
  "test-lint-config-sensors": [
    "scripts/lint-config-sensors.sh",
    "scripts/test-lint-config-sensors.sh",
    "scripts/lint-changed.sh",
    "scripts/verify-metadata.sh",
    "scripts/path-policy-query.ts",
    "scripts/path-policy-query-core.ts",
    "scripts/path-policy.ts",
    "scripts/test-git-env.sh",
    ".yamllint.yml",
    "package.json",
    "bun.lock",
    ".github/workflows/",
    "docker-compose.yml",
    ".devcontainer/docker-compose.yml",
    ".devcontainer/Dockerfile",
    ".codex/config.toml",
    ".codex/skills/",
    "bunfig.toml",
  ],
  "test-test-changed": [
    "scripts/test-changed.sh",
    "scripts/vitest.sh",
    "scripts/ai-hooks/output-filter.sh",
    "scripts/test-git-env.sh",
    "scripts/test-test-changed.sh",
  ],
  "test-test-slow": [
    "scripts/test-slow.sh",
    "scripts/test-changed.sh",
    "scripts/vitest.sh",
    "scripts/ai-hooks/output-filter.sh",
    "scripts/test-git-env.sh",
    "vitest.slow.config.ts",
    "packages/shared/vitest.config.ts",
    "packages/server/vitest.config.ts",
    "packages/client/vitest.config.ts",
    "packages/shared/src/test-tier-sentinel.test.ts",
    "packages/shared/src/test-tier-sentinel.slow.test.ts",
    "scripts/test-test-slow.sh",
  ],
  "test-generate-module-index": [
    "scripts/generate-module-index.sh",
    "scripts/test-git-env.sh",
    "scripts/test-generate-module-index.sh",
    "scripts/harness-emit-envelope.ts",
    "packages/shared/src/schemas/harness-diagnostics.ts",
  ],
  "test-generate-lint-guidance": [
    "scripts/generate-lint-guidance.ts",
    "scripts/lint-rule-docs.ts",
    "scripts/test-generate-lint-guidance.sh",
    "scripts/fixtures/generate-lint-guidance/",
    "eslint.config.js",
    "eslint-config/",
    "package.json",
    "tsconfig.scripts.json",
    "docs/generated/local-lint-rules.md",
    "eslint-rules/",
  ],
  "test-generate-harness-controls": [
    "scripts/generate-harness-controls.ts",
    "scripts/generate-harness-controls-validation.ts",
    "scripts/lint-rule-docs.ts",
    "scripts/test-generate-harness-controls.sh",
    "scripts/fixtures/generate-harness-controls/",
    "harness.controls.json",
    "eslint.config.js",
    "eslint-config/",
    "package.json",
    "tsconfig.scripts.json",
    "docs/generated/harness-controls.md",
    "eslint-rules/",
  ],
  "test-harness-check": [
    "scripts/harness-check.ts",
    "scripts/harness-check-validation.ts",
    "scripts/harness-wrapper-slot-parity.ts",
    "scripts/harness-wrapper-slot-parser.ts",
    "scripts/ratchet-manifest-message.ts",
    "scripts/test-harness-check.sh",
    "harness.controls.json",
    "eslint.config.js",
    "eslint-config/",
    "package.json",
    "tsconfig.scripts.json",
    "eslint-rules/",
  ],
  "test-lint-agent": [
    "scripts/lint-agent.ts",
    "scripts/lint-rule-docs.ts",
    "scripts/test-lint-agent.sh",
    "packages/shared/src/schemas/harness-diagnostics.ts",
    "package.json",
    "tsconfig.scripts.json",
    "eslint.config.js",
    "eslint-config/",
    "eslint-rules/",
  ],
  "test-lint-agent-changed": [
    "scripts/lint-agent-changed.sh",
    "scripts/lint-agent.ts",
    "scripts/harness-emit-envelope.ts",
    "scripts/path-policy-query.ts",
    "scripts/path-policy-query-core.ts",
    "scripts/path-policy.ts",
    "scripts/test-git-env.sh",
    "scripts/test-lint-agent-changed.sh",
    "packages/shared/src/schemas/harness-diagnostics.ts",
    "package.json",
    "eslint-config/",
  ],
  "test-harness-emit-envelope": [
    "scripts/harness-emit-envelope.ts",
    "scripts/test-harness-emit-envelope.sh",
    "packages/shared/src/schemas/harness-diagnostics.ts",
  ],
  "test-lint-ratchet": [
    "scripts/lint-ratchet.ts",
    "scripts/lint-ratchet/",
    "scripts/lint-ratchet-config.ts",
    "scripts/lint-ratchet-metrics.ts",
    "scripts/lint-ratchet-baseline-compare.ts",
    "scripts/lint-ratchet-baseline-parse.ts",
    "scripts/lint-ratchet-baseline.ts",
    "scripts/lint-ratchet-baseline.test.ts",
    "scripts/lint-ratchet-check-registry.ts",
    "scripts/lint-ratchet-check-registry.test.ts",
    "scripts/lint-ratchet-output.ts",
    "scripts/lint-ratchet-output.test.ts",
    "scripts/lint-ratchet-registry-builders.ts",
    "scripts/lint-ratchet-report.ts",
    "scripts/lint-ratchet-report.test.ts",
    "scripts/lint-ratchet-summary.ts",
    "scripts/lint-ratchet-summary.test.ts",
    "scripts/lint-ratchet-zero-baseline.ts",
    "scripts/lint-ratchet-zero-baseline.test.ts",
    "scripts/lint-rule-docs.ts",
    "scripts/ratchet-manifest-message.ts",
    "scripts/test-git-env.sh",
    "scripts/test-lint-ratchet.sh",
    "lint-ratchet.baseline.json",
    "packages/shared/src/schemas/harness-diagnostics.ts",
    "package.json",
    "tsconfig.scripts.json",
    "eslint.config.js",
    "eslint-config/",
    "eslint-rules/",
  ],
  "test-migration-safety-scan": [
    "scripts/migration-safety-scan.sh",
    "scripts/test-git-env.sh",
    "scripts/test-migration-safety-scan.sh",
    "scripts/harness-emit-envelope.ts",
    "packages/shared/src/schemas/harness-diagnostics.ts",
  ],
  "test-doctor-json": [
    "scripts/doctor.sh",
    "scripts/dependency-freshness.sh",
    "scripts/harness-emit-envelope.ts",
    "scripts/test-git-env.sh",
    "scripts/test-doctor-json.sh",
    "harness.controls.json",
    "packages/shared/src/schemas/harness-diagnostics.ts",
  ],
  "test-parallel-runner": ["scripts/parallel-runner.sh", "scripts/test-parallel-runner.sh"],
  "test-verify-metadata": [
    "scripts/verify-metadata.sh",
    "scripts/path-policy-query.ts",
    "scripts/path-policy-query-core.ts",
    "scripts/path-policy.ts",
    "scripts/test-git-env.sh",
    "scripts/test-verify-metadata.sh",
  ],
  "test-test-scripts": [
    "scripts/test-scripts.sh",
    "scripts/test-git-env.sh",
    "scripts/test-test-scripts.sh",
    "scripts/path-policy-query.ts",
    "scripts/path-policy-query-core.ts",
    "scripts/path-policy.ts",
    "scripts/path-policy-smoke-subjects.ts",
  ],
} as const satisfies ScriptSmokeSubjects;
