# shellcheck shell=bash
# shellcheck disable=SC2034
# Generated by scripts/harness/generate-verify-steps.ts. Do not edit by hand.
# Classifier slices live in harness.controls.json (generatedSurface bunHook
# facets); regenerate with `bun run verify:steps`.

AI_GENERATED_WRAPPED_BUN_SCRIPTS='
docs:baseline-conflict-recipes:check
docs:harness-controls:check
docs:lint-guidance:check
harness:config-surfaces
harness:config-surfaces:check
harness:hook-timeouts:check
harness:wiring:check
lint:restricted-disable-rules
lint:restricted-disable-rules:check
mutation:survivors
sensor:context-budget
test:scripts:subjects
test:scripts:subjects:check
verify:steps:check
'

AI_GENERATED_BYPASS_BUN_SCRIPTS='
docs:baseline-conflict-recipes
docs:harness-controls
docs:lint-guidance
harness:hook-timeouts
harness:wiring
verify:steps
'
