# shellcheck shell=bash
# shellcheck disable=SC2034
# Generated by scripts/harness/generate-verify-steps.ts. Do not edit by hand.
# Classifier slices live in harness.controls.json (generatedSurface bunHook
# facets); regenerate with `bun run verify:steps`.

AI_GENERATED_WRAPPED_BUN_SCRIPTS='
concurrency:relation-graph:check
docs:backlog-catalog:check
docs:baseline-conflict-recipes:check
docs:command-catalog:check
docs:harness-controls:check
docs:harness-porting:check
docs:lint-coverage-map:generate:check
docs:lint-guidance:check
harness:command-policy:check
harness:config-surfaces
harness:config-surfaces:check
harness:hook-timeouts:check
harness:lint-rule-controls
harness:lint-rule-controls:check
harness:manifest-schema
harness:manifest-schema:check
harness:pre-push-trigger:check
harness:skills:check
harness:skills:refresh
harness:wiring:check
lint:local-plugin
lint:local-plugin:check
lint:restricted-disable-rules
lint:restricted-disable-rules:check
mutation:survivors
sensor:context-budget
test:scripts:subjects
test:scripts:subjects:check
verify:steps:check
'

AI_GENERATED_BYPASS_BUN_SCRIPTS='
concurrency:relation-graph
docs:backlog-catalog
docs:baseline-conflict-recipes
docs:command-catalog
docs:harness-controls
docs:harness-porting
docs:lint-coverage-map:generate
docs:lint-guidance
harness:command-policy
harness:hook-timeouts
harness:pre-push-trigger
harness:wiring
verify:steps
'
