# shellcheck shell=bash
# shellcheck disable=SC2034
# Generated by scripts/harness/generate-hook-timeout-constants.ts. Do not edit by hand.

BUN_RUN_QUIET_HOOK_TIMEOUT=2460
GIT_COMMIT_QUIET_HOOK_TIMEOUT=2460
