# shellcheck shell=bash
# shellcheck disable=SC2034
# Generated by scripts/harness/generate-command-policy.ts. Do not edit by hand.
# Rule rows live in harness.controls.json (root commandPolicy array);
# regenerate with `bun run harness:command-policy`.
#
# AI_POLICY_RULE_IDS is the scan order: first hard match wins; otherwise the first soft match advises. Pattern
# matchers keep ${AI_POLICY_GIT_CMD} / $AI_POLICY_CMD_END symbolic, so a
# consumer expands them at match time. Matcher blocks are newline-separated
# `<kind><TAB><value>` lines in evaluation order.

declare -g AI_POLICY_HOOK_BYPASS='Hook bypass is not allowed. Pre-commit hooks must always run.'
declare -g AI_POLICY_POSTGRES='Do not use PostgreSQL CLI tools directly. You are in a container - use Prisma for all DB operations: '\''bun run --filter @musi/server db:push'\'' for schema, '\''bun run --filter @musi/server db:seed'\'' for seeding, or Prisma CLI commands routed through the repo scripts. Credentials are in .devcontainer/.env.'
declare -g AI_POLICY_REDIS='Do not use redis-cli directly. You are in a container - Redis is managed by the app. If you need to inspect Redis state, read the app code or use '\''bun run'\'' scripts.'
declare -g AI_POLICY_DOCKER='Do not run docker or docker-compose commands. You are in a container - PostgreSQL and Redis are already running and managed by the dev container. Use Prisma CLI for database operations.'
declare -g AI_POLICY_CHANGEME='Wrong database credentials. '\''ThisIsNotTheRealDatabasePassword'\'' is not the password for this environment. Read .devcontainer/.env for the correct credentials.'
declare -g AI_POLICY_GIT_AMEND='Git commit amend is not allowed from agents because it rewrites local history. The amend did NOT run — HEAD and your staged changes are untouched. Stage your changes and create a NEW follow-up commit instead. If the previous commit genuinely must be amended, ask the user to do it manually.'
declare -g AI_POLICY_GIT_REBASE='Git rebase is not allowed from agents because it rewrites local history. Use merge or add follow-up commits; if a rebase is required, ask the user to run it.'
declare -g AI_POLICY_GIT_RESET='Dangerous git reset modes are not allowed from agents. Use path-scoped '\''git restore --staged <path>'\'' or ask the user to run the reset.'
declare -g AI_POLICY_GIT_WORKTREE_LOSS='Git worktree-discarding commands are not allowed from agents because they can destroy uncommitted work. Use non-destructive inspection commands, path-scoped staged-only restores, or ask the user to run the discard.'
declare -g AI_POLICY_GIT_STASH='Git stash mutations are not allowed from repository agents because stash ownership cannot be proven across agent work. Commit the work, inspect it with '\''git diff'\'' or '\''git show HEAD:<path>'\'', copy a file aside for an A/B comparison, or ask the user.'
declare -g AI_POLICY_GIT_HISTORY_REWRITE='Git history rewrite and direct ref manipulation are not allowed from agents. Add a follow-up commit or ask the user to run the rewrite.'
declare -g AI_POLICY_GIT_FORCE_PUSH='Git force-push, remote ref pruning, and remote branch deletion are not allowed from agents. Push normal feature-branch updates only, or ask the user to perform the remote mutation.'
declare -g AI_POLICY_GIT_PUSH_MAIN='Pushing to main or master is not allowed from agents. Push a feature branch or ask the user to push the protected branch.'
declare -g AI_POLICY_GIT_BRANCH_FORCE_DELETE='Force-updating or force-deleting branches and tags, and force-removing worktrees, are not allowed from agents. Use non-force ref operations or '\''bun run worktree:drop'\'', or ask the user to perform the destructive update.'
declare -g AI_POLICY_GIT_CLEAN_FORCE='Git clean with force is not allowed from agents because it destroys untracked files. Remove specific generated files by name or ask the user to clean the tree.'
declare -g AI_POLICY_GH_AUTH='GitHub auth token output and auth reconfiguration are not allowed from agents. Use '\''gh auth status'\'' for read-only auth checks, or ask the user to manage authentication.'
declare -g AI_POLICY_GH_REMOTE_MUTATION='GitHub remote mutations are not allowed from agents. Use read-only '\''gh ... view/list/status'\'' commands, or ask the user to perform the mutation.'
declare -g AI_POLICY_GIT_COMMIT_ON_MAIN='Committing on main or master is not allowed from agents. Create a feature branch ('\''git switch -c feat/...'\'') and commit there; reviewers merge to the protected branch.'

declare -ga AI_POLICY_RULE_IDS=('hook-bypass' 'postgres-cli' 'redis-cli' 'docker-cli' 'database-password-literal' 'protected-file-write' 'git-commit-amend' 'git-rebase' 'git-dangerous-reset' 'git-worktree-loss' 'git-stash' 'git-history-rewrite' 'git-force-push' 'git-push-to-main' 'git-branch-force-delete' 'git-clean-force' 'gh-auth' 'gh-remote-mutation' 'git-commit-on-main')

declare -gA AI_POLICY_RULE_CLASS=()
AI_POLICY_RULE_CLASS['hook-bypass']='hard'
AI_POLICY_RULE_CLASS['postgres-cli']='hard'
AI_POLICY_RULE_CLASS['redis-cli']='hard'
AI_POLICY_RULE_CLASS['docker-cli']='hard'
AI_POLICY_RULE_CLASS['database-password-literal']='hard'
AI_POLICY_RULE_CLASS['protected-file-write']='hard'
AI_POLICY_RULE_CLASS['git-commit-amend']='hard'
AI_POLICY_RULE_CLASS['git-rebase']='hard'
AI_POLICY_RULE_CLASS['git-dangerous-reset']='hard'
AI_POLICY_RULE_CLASS['git-worktree-loss']='hard'
AI_POLICY_RULE_CLASS['git-stash']='hard'
AI_POLICY_RULE_CLASS['git-history-rewrite']='hard'
AI_POLICY_RULE_CLASS['git-force-push']='hard'
AI_POLICY_RULE_CLASS['git-push-to-main']='hard'
AI_POLICY_RULE_CLASS['git-branch-force-delete']='hard'
AI_POLICY_RULE_CLASS['git-clean-force']='hard'
AI_POLICY_RULE_CLASS['gh-auth']='hard'
AI_POLICY_RULE_CLASS['gh-remote-mutation']='hard'
AI_POLICY_RULE_CLASS['git-commit-on-main']='hard'

declare -gA AI_POLICY_RULE_SCOPE=()
AI_POLICY_RULE_SCOPE['hook-bypass']='command'
AI_POLICY_RULE_SCOPE['postgres-cli']='command'
AI_POLICY_RULE_SCOPE['redis-cli']='command'
AI_POLICY_RULE_SCOPE['docker-cli']='command'
AI_POLICY_RULE_SCOPE['database-password-literal']='command'
AI_POLICY_RULE_SCOPE['protected-file-write']='checkout'
AI_POLICY_RULE_SCOPE['git-commit-amend']='command'
AI_POLICY_RULE_SCOPE['git-rebase']='command'
AI_POLICY_RULE_SCOPE['git-dangerous-reset']='command'
AI_POLICY_RULE_SCOPE['git-worktree-loss']='command'
AI_POLICY_RULE_SCOPE['git-stash']='command'
AI_POLICY_RULE_SCOPE['git-history-rewrite']='command'
AI_POLICY_RULE_SCOPE['git-force-push']='command'
AI_POLICY_RULE_SCOPE['git-push-to-main']='checkout'
AI_POLICY_RULE_SCOPE['git-branch-force-delete']='command'
AI_POLICY_RULE_SCOPE['git-clean-force']='command'
AI_POLICY_RULE_SCOPE['gh-auth']='command'
AI_POLICY_RULE_SCOPE['gh-remote-mutation']='command'
AI_POLICY_RULE_SCOPE['git-commit-on-main']='checkout'

declare -gA AI_POLICY_RULE_MESSAGE=()
AI_POLICY_RULE_MESSAGE['hook-bypass']='Hook bypass is not allowed. Pre-commit hooks must always run.'
AI_POLICY_RULE_MESSAGE['postgres-cli']='Do not use PostgreSQL CLI tools directly. You are in a container - use Prisma for all DB operations: '\''bun run --filter @musi/server db:push'\'' for schema, '\''bun run --filter @musi/server db:seed'\'' for seeding, or Prisma CLI commands routed through the repo scripts. Credentials are in .devcontainer/.env.'
AI_POLICY_RULE_MESSAGE['redis-cli']='Do not use redis-cli directly. You are in a container - Redis is managed by the app. If you need to inspect Redis state, read the app code or use '\''bun run'\'' scripts.'
AI_POLICY_RULE_MESSAGE['docker-cli']='Do not run docker or docker-compose commands. You are in a container - PostgreSQL and Redis are already running and managed by the dev container. Use Prisma CLI for database operations.'
AI_POLICY_RULE_MESSAGE['database-password-literal']='Wrong database credentials. '\''ThisIsNotTheRealDatabasePassword'\'' is not the password for this environment. Read .devcontainer/.env for the correct credentials.'
AI_POLICY_RULE_MESSAGE['git-commit-amend']='Git commit amend is not allowed from agents because it rewrites local history. The amend did NOT run — HEAD and your staged changes are untouched. Stage your changes and create a NEW follow-up commit instead. If the previous commit genuinely must be amended, ask the user to do it manually.'
AI_POLICY_RULE_MESSAGE['git-rebase']='Git rebase is not allowed from agents because it rewrites local history. Use merge or add follow-up commits; if a rebase is required, ask the user to run it.'
AI_POLICY_RULE_MESSAGE['git-dangerous-reset']='Dangerous git reset modes are not allowed from agents. Use path-scoped '\''git restore --staged <path>'\'' or ask the user to run the reset.'
AI_POLICY_RULE_MESSAGE['git-worktree-loss']='Git worktree-discarding commands are not allowed from agents because they can destroy uncommitted work. Use non-destructive inspection commands, path-scoped staged-only restores, or ask the user to run the discard.'
AI_POLICY_RULE_MESSAGE['git-stash']='Git stash mutations are not allowed from repository agents because stash ownership cannot be proven across agent work. Commit the work, inspect it with '\''git diff'\'' or '\''git show HEAD:<path>'\'', copy a file aside for an A/B comparison, or ask the user.'
AI_POLICY_RULE_MESSAGE['git-history-rewrite']='Git history rewrite and direct ref manipulation are not allowed from agents. Add a follow-up commit or ask the user to run the rewrite.'
AI_POLICY_RULE_MESSAGE['git-force-push']='Git force-push, remote ref pruning, and remote branch deletion are not allowed from agents. Push normal feature-branch updates only, or ask the user to perform the remote mutation.'
AI_POLICY_RULE_MESSAGE['git-push-to-main']='Pushing to main or master is not allowed from agents. Push a feature branch or ask the user to push the protected branch.'
AI_POLICY_RULE_MESSAGE['git-branch-force-delete']='Force-updating or force-deleting branches and tags, and force-removing worktrees, are not allowed from agents. Use non-force ref operations or '\''bun run worktree:drop'\'', or ask the user to perform the destructive update.'
AI_POLICY_RULE_MESSAGE['git-clean-force']='Git clean with force is not allowed from agents because it destroys untracked files. Remove specific generated files by name or ask the user to clean the tree.'
AI_POLICY_RULE_MESSAGE['gh-auth']='GitHub auth token output and auth reconfiguration are not allowed from agents. Use '\''gh auth status'\'' for read-only auth checks, or ask the user to manage authentication.'
AI_POLICY_RULE_MESSAGE['gh-remote-mutation']='GitHub remote mutations are not allowed from agents. Use read-only '\''gh ... view/list/status'\'' commands, or ask the user to perform the mutation.'
AI_POLICY_RULE_MESSAGE['git-commit-on-main']='Committing on main or master is not allowed from agents. Create a feature branch ('\''git switch -c feat/...'\'') and commit there; reviewers merge to the protected branch.'

declare -gA AI_POLICY_RULE_HAYSTACK_TRANSFORM=()
AI_POLICY_RULE_HAYSTACK_TRANSFORM['git-rebase']='ai_policy_strip_allowed_rebase_controls'

declare -gA AI_POLICY_RULE_MATCHERS=()
AI_POLICY_RULE_MATCHERS['hook-bypass']='predicate	ai_policy_has_husky_zero_prefix
predicate	ai_policy_has_git_commit_hook_bypass_flag
predicate	ai_policy_has_git_push_hook_bypass_flag'
AI_POLICY_RULE_MATCHERS['postgres-cli']='pattern	(psql|pgcli|pg_dump|pg_restore|pg_isready|createdb|dropdb)$AI_POLICY_CMD_END'
AI_POLICY_RULE_MATCHERS['redis-cli']='pattern	redis-cli$AI_POLICY_CMD_END'
AI_POLICY_RULE_MATCHERS['docker-cli']='pattern	docker(-compose)?$AI_POLICY_CMD_END'
AI_POLICY_RULE_MATCHERS['database-password-literal']='literal	ThisIsNotTheRealDatabasePassword'
AI_POLICY_RULE_MATCHERS['protected-file-write']='predicate	ai_policy_bash_protected_file_violation_reason'
AI_POLICY_RULE_MATCHERS['git-commit-amend']='pattern	${AI_POLICY_GIT_CMD}commit[^;&|]*[[:space:]]--amend$AI_POLICY_CMD_END'
AI_POLICY_RULE_MATCHERS['git-rebase']='pattern	${AI_POLICY_GIT_CMD}rebase$AI_POLICY_CMD_END
pattern	${AI_POLICY_GIT_CMD}rebase[[:space:]]+'
AI_POLICY_RULE_MATCHERS['git-dangerous-reset']='predicate	ai_policy_has_dangerous_git_reset'
AI_POLICY_RULE_MATCHERS['git-worktree-loss']='predicate	ai_policy_has_git_worktree_loss'
AI_POLICY_RULE_MATCHERS['git-stash']='predicate	ai_policy_has_disallowed_git_stash'
AI_POLICY_RULE_MATCHERS['git-history-rewrite']='pattern	${AI_POLICY_GIT_CMD}(filter-branch|filter-repo|replace|update-ref)$AI_POLICY_CMD_END
pattern	${AI_POLICY_GIT_CMD}reflog[[:space:]]+expire[^;&|]*--expire=now[^;&|]*--all'
AI_POLICY_RULE_MATCHERS['git-force-push']='pattern	${AI_POLICY_GIT_CMD}push[^;&|]*[[:space:]]((--force|--force-with-lease)(=[^[:space:];|&'\''"]*)?|--mirror|--delete|--prune)$AI_POLICY_CMD_END
pattern	${AI_POLICY_GIT_CMD}push[^;&|]*[[:space:]]-[A-Za-z]*[fd][A-Za-z]*$AI_POLICY_CMD_END
pattern	${AI_POLICY_GIT_CMD}push[^;&|]*[[:space:]]\+[^[:space:];|&'\''"]+
pattern	${AI_POLICY_GIT_CMD}push[^;&|]*[[:space:]]:[^[:space:];|&'\''"]+'
AI_POLICY_RULE_MATCHERS['git-push-to-main']='predicate	ai_policy_has_git_push_to_main'
AI_POLICY_RULE_MATCHERS['git-branch-force-delete']='pattern	${AI_POLICY_GIT_CMD}branch[^;&|]*[[:space:]]-D$AI_POLICY_CMD_END
pattern	${AI_POLICY_GIT_CMD}branch[^;&|]*[[:space:]]-[A-Za-z]*D[A-Za-z]*$AI_POLICY_CMD_END
pattern	${AI_POLICY_GIT_CMD}branch[^;&|]*[[:space:]]-[A-Za-z]*d[A-Za-z]*f[A-Za-z]*$AI_POLICY_CMD_END
pattern	${AI_POLICY_GIT_CMD}branch[^;&|]*[[:space:]]-[A-Za-z]*f[A-Za-z]*d[A-Za-z]*$AI_POLICY_CMD_END
pattern	${AI_POLICY_GIT_CMD}branch[^;&|]*[[:space:]]-[A-Za-z]*d[A-Za-z]*[^;&|]*[[:space:]]-[A-Za-z]*f[A-Za-z]*
pattern	${AI_POLICY_GIT_CMD}branch[^;&|]*[[:space:]]-[A-Za-z]*f[A-Za-z]*[^;&|]*[[:space:]]-[A-Za-z]*d[A-Za-z]*
pattern	${AI_POLICY_GIT_CMD}branch[^;&|]*--delete[^;&|]*--force
pattern	${AI_POLICY_GIT_CMD}branch[^;&|]*--force[^;&|]*--delete
pattern	${AI_POLICY_GIT_CMD}branch[^;&|]*--delete[^;&|]*[[:space:]]-[A-Za-z]*f[A-Za-z]*
pattern	${AI_POLICY_GIT_CMD}branch[^;&|]*[[:space:]]-[A-Za-z]*f[A-Za-z]*[^;&|]*--delete
pattern	${AI_POLICY_GIT_CMD}branch[^;&|]*[[:space:]](--force|-[A-Za-z]*[fMC][A-Za-z]*)$AI_POLICY_CMD_END
pattern	${AI_POLICY_GIT_CMD}tag[^;&|]*[[:space:]]+(-[A-Za-z]*d[A-Za-z]*|--delete)$AI_POLICY_CMD_END
pattern	${AI_POLICY_GIT_CMD}tag[^;&|]*[[:space:]]+(--force|-[A-Za-z]*f[A-Za-z]*)$AI_POLICY_CMD_END
pattern	${AI_POLICY_GIT_CMD}worktree[[:space:]]+remove[^;&|]*[[:space:]]--force$AI_POLICY_CMD_END
pattern	${AI_POLICY_GIT_CMD}worktree[[:space:]]+remove[^;&|]*[[:space:]]-[A-Za-z]*f[A-Za-z]*$AI_POLICY_CMD_END'
AI_POLICY_RULE_MATCHERS['git-clean-force']='pattern	${AI_POLICY_GIT_CMD}clean[^;&|]*[[:space:]](--force|-[A-Za-z]*f[A-Za-z]*)$AI_POLICY_CMD_END'
AI_POLICY_RULE_MATCHERS['gh-auth']='pattern	gh[[:space:]]+auth[[:space:]]+(token|login|logout|refresh|setup-git)$AI_POLICY_CMD_END'
AI_POLICY_RULE_MATCHERS['gh-remote-mutation']='pattern	gh[[:space:]]+pr[[:space:]]+(create|comment|merge|close|reopen|ready|edit|lock|unlock|review)$AI_POLICY_CMD_END
pattern	gh[[:space:]]+issue[[:space:]]+(create|comment|close|reopen|edit|delete|develop|lock|unlock|transfer|pin|unpin)$AI_POLICY_CMD_END
pattern	gh[[:space:]]+repo[[:space:]]+(create|fork|delete|archive|rename|transfer|edit|sync|set-default)$AI_POLICY_CMD_END
pattern	gh[[:space:]]+repo[[:space:]]+deploy-key[[:space:]]+(add|delete)$AI_POLICY_CMD_END
pattern	gh[[:space:]]+release[[:space:]]+(create|edit|delete|delete-asset|upload)$AI_POLICY_CMD_END
pattern	gh[[:space:]]+workflow[[:space:]]+(disable|enable|run)$AI_POLICY_CMD_END
pattern	gh[[:space:]]+run[[:space:]]+(cancel|rerun|delete)$AI_POLICY_CMD_END
pattern	gh[[:space:]]+cache[[:space:]]+delete$AI_POLICY_CMD_END
pattern	gh[[:space:]]+secret[[:space:]]+(set|delete)$AI_POLICY_CMD_END
pattern	gh[[:space:]]+variable[[:space:]]+(set|delete)$AI_POLICY_CMD_END
predicate	ai_policy_has_gh_api_mutation
pattern	gh[[:space:]]+codespace[[:space:]]+(create|delete|edit|rebuild|stop)$AI_POLICY_CMD_END
pattern	gh[[:space:]]+gist[[:space:]]+(create|edit|delete)$AI_POLICY_CMD_END
pattern	gh[[:space:]]+(gpg-key|ssh-key)[[:space:]]+(add|delete)$AI_POLICY_CMD_END
pattern	gh[[:space:]]+label[[:space:]]+(create|edit|delete|clone)$AI_POLICY_CMD_END
pattern	gh[[:space:]]+alias[[:space:]]+(set|delete)$AI_POLICY_CMD_END
pattern	gh[[:space:]]+config[[:space:]]+set$AI_POLICY_CMD_END
pattern	gh[[:space:]]+extension[[:space:]]+(install|remove|upgrade)$AI_POLICY_CMD_END'
AI_POLICY_RULE_MATCHERS['git-commit-on-main']='predicate	ai_policy_has_git_commit_on_main'

declare -gA AI_POLICY_RULE_NATIVE_MATCHERS=()
AI_POLICY_RULE_NATIVE_MATCHERS['hook-bypass']='Bash(git commit *--no-verify*)
Bash(git commit --no-verify*)
Bash(git -c * commit *--no-verify*)'
AI_POLICY_RULE_NATIVE_MATCHERS['git-commit-amend']='Bash(git commit *--amend*)
Bash(git commit --amend*)
Bash(git -c * commit *--amend*)'
AI_POLICY_RULE_NATIVE_MATCHERS['git-dangerous-reset']='Bash(git reset *--hard*)
Bash(git reset *--soft*)
Bash(git reset *--merge*)
Bash(git reset *--keep*)
Bash(git reset HEAD~*)
Bash(git reset * HEAD~*)
Bash(git reset HEAD^*)
Bash(git reset * HEAD^*)
Bash(git reset ORIG_HEAD*)
Bash(git reset * ORIG_HEAD*)'
AI_POLICY_RULE_NATIVE_MATCHERS['git-worktree-loss']='Bash(git checkout *--force*)
Bash(git checkout -f*)
Bash(git checkout * -f*)
Bash(git checkout -- *)
Bash(git checkout * -- *)
Bash(git checkout .)
Bash(git switch *--force*)
Bash(git switch -f*)
Bash(git switch * -f*)
Bash(git restore *--worktree*)
Bash(git restore -W*)
Bash(git restore * -W*)
Bash(git restore -- .)
Bash(git restore .)'
AI_POLICY_RULE_NATIVE_MATCHERS['git-history-rewrite']='Bash(git filter-branch*)
Bash(git filter-repo*)
Bash(git replace*)
Bash(git update-ref*)
Bash(git reflog expire *--expire=now*--all*)'
AI_POLICY_RULE_NATIVE_MATCHERS['git-force-push']='Bash(git push *--force*)
Bash(git push *--mirror*)
Bash(git push *--delete*)
Bash(git push *--prune*)
Bash(git push -f*)
Bash(git push * -f*)
Bash(git push -d*)
Bash(git push * -d*)
Bash(git push +*)
Bash(git push * +*)
Bash(git push :*)
Bash(git push * :*)'
AI_POLICY_RULE_NATIVE_MATCHERS['git-branch-force-delete']='Bash(git branch *--force*)
Bash(git branch *--delete*--force*)
Bash(git branch *--force*--delete*)
Bash(git branch -D*)
Bash(git branch * -D*)
Bash(git branch -f*)
Bash(git branch * -f*)
Bash(git branch -df*)
Bash(git branch * -df*)
Bash(git branch -fd*)
Bash(git branch * -fd*)
Bash(git branch -M*)
Bash(git branch * -M*)
Bash(git branch -C*)
Bash(git branch * -C*)
Bash(git tag *--delete*)
Bash(git tag *--force*)
Bash(git tag -d*)
Bash(git tag * -d*)
Bash(git tag -f*)
Bash(git tag * -f*)
Bash(git worktree remove *--force*)
Bash(git worktree remove -f*)
Bash(git worktree remove * -f*)'
AI_POLICY_RULE_NATIVE_MATCHERS['git-clean-force']='Bash(git clean -f*)
Bash(git clean -df*)
Bash(git clean * -f*)
Bash(git clean * -df*)
Bash(git clean *--force*)'
AI_POLICY_RULE_NATIVE_MATCHERS['gh-auth']='Bash(gh auth login:*)
Bash(gh auth logout:*)
Bash(gh auth token:*)
Bash(gh auth refresh:*)
Bash(gh auth setup-git:*)'

declare -gA AI_POLICY_RULE_NATIVE_EXCLUSION=()
AI_POLICY_RULE_NATIVE_EXCLUSION['postgres-cli']='Not projected: the whole value of this rule is the shared policy'\''s remediation text (which Prisma or repo script replaces the CLI), and a native deny preempts it with a bare refusal. A rule is projected only where denying before the hook can speak is worth losing its message; here the message is the rule.'
AI_POLICY_RULE_NATIVE_EXCLUSION['redis-cli']='Not projected, for the same reason as postgres-cli: the shared policy'\''s message is the remediation, and native denial would replace it with a bare refusal.'
AI_POLICY_RULE_NATIVE_EXCLUSION['docker-cli']='Not projected, for the same reason as postgres-cli: the shared policy'\''s message is the remediation, and native denial would replace it with a bare refusal.'
AI_POLICY_RULE_NATIVE_EXCLUSION['database-password-literal']='Not projected: this rule matches a credential literal anywhere in the command text rather than a command prefix, and Claude'\''s Bash(...) matchers are prefix-anchored globs with no faithful bare-substring form.'
AI_POLICY_RULE_NATIVE_EXCLUSION['protected-file-write']='Not projected: checkout-scoped. The protected-path table itself is static (the case block in scripts/ai-hooks/protected-files.sh), but the verdict flips on whether the checkout the hook resolves carries the repo-wide .allow-protected-edits override marker, which no static command matcher can see.'
AI_POLICY_RULE_NATIVE_EXCLUSION['git-rebase']='Not projected: the rule matches only the residue left after ai_policy_strip_allowed_rebase_controls removes the deliberately allowed --continue/--abort/--skip/--quit forms, so a static `git rebase*` matcher would deny commands this policy allows.'
AI_POLICY_RULE_NATIVE_EXCLUSION['git-stash']='Not projected, and pinned as such by scripts/ai-hooks/test.sh: a native stash deny fires before the shared hook can speak, and this rule'\''s whole point is the contextual reason it supplies (stash refs are shared by every linked worktree, so ownership cannot be proven, and the message names the commit / git diff / copy-aside alternatives). The record-level corpus fails if this row gains native matchers; harness:check fails if the native deny array stops matching the projection.'
AI_POLICY_RULE_NATIVE_EXCLUSION['git-push-to-main']='Not projected: checkout-scoped. Beyond the explicit main/master refspecs, the verdict depends on the branch of the resolved target checkout, which a static command matcher cannot resolve.'
AI_POLICY_RULE_NATIVE_EXCLUSION['gh-remote-mutation']='Not projected: the rule'\''s `gh api` arm is flag-contextual — an explicit --method GET and a visible GraphQL query= payload are deliberately allowed — so projecting only the subcommand arms would split one rule across two authorities and leave its contextual arm silently unprojected.'
AI_POLICY_RULE_NATIVE_EXCLUSION['git-commit-on-main']='Not projected: checkout-scoped. A plain `git commit` is allowed everywhere except the protected branch of the resolved target checkout, and a static command matcher cannot see that branch.'

# Completion sentinel: policy.sh resets this before sourcing and fails closed
# unless the fragment reaches this final statement with the expected rule count.
declare -g AI_POLICY_RULES_COMPLETE=19
